### ISSUE TITLE
Possible versioning issue

### ISSUE THREAD

**Issue by holiman** [Proxmark/proxmark3#10]
I think there may be a problem with my versioning-fix. I changed the size of version_info-struct, in order to fit more info in there. At the time, I didn't think it would be a problem, but it struck me later that if someone flashes the pm3 with "github-version", and then uses a "svn-version" of the client and does "hw version" or vice versa, there will probably be problems. 

I don't know the best way to fix that. 
- Crop git info more, to fit within 9 characters? 
- Change versioning magic-number, so old clients and new clients are officially incompatible?

**Comment by yadadamean** [comment]
Hi,when i put hf tune then it's say sending bytes to proxmark failed.And when I try to flash all then it's say #db#button press detected but no storage tag play. I buy the proxmark from elechouse .

**Comment by merlokk** [comment]
http://www.proxmark.org/forum/index.php
