### ISSUE TITLE
Malicious URLs on Wiki

### ISSUE THREAD

**Issue by ayancey** [Proxmark/proxmark3#1001]
Hey,

It looks like multiple people are persistently changing the URL on the wiki page for Windows installation from ProxSpace to a malicious remote access trojan.

https://github.com/Proxmark/proxmark3/wiki/Windows

Someone changed the URL from https://github.com/Gator96100/ProxSpace/archive/master.zip to `https://github.com/lampii/VideoCaptureUtility/releases/download/42/master.zip`

The user keeps changing their name to cover up their tracks.

**Comment by pwpiwi** [comment]
@0xFFFF (owner of this repository): Would it make sense to allow Wiki changes to contributors only?

**Comment by ayancey** [comment]
Hello everyone.

**Comment by ayancey** [comment]
FYI, this continues to be an issue. The attacker has gone and tried to revert the change I made, re-enabling the malicious link. https://github.com/Proxmark/proxmark3/wiki/Windows/_history

**Comment by AkechiShiro** [comment]
Some maintainers of Proxmark3 need to step in ASAP, this is a joke that someone is toying with a security researcher project like this

**Comment by 0xFFFF** [comment]
In response to this particular issue I have enabled:
- `General` / `Require contributors to sign off on web-based commits`
- `General` / `Features` / `Wikis` / `Restrict editing to users in teams with push access only`

Please inform me (just as @pwpiwi has done) if additional changes are required.

**Comment by ayancey** [comment]
Thank you. If anyone downloaded and ran that executable, I would highly recommend you nuke your system. The attacker got access to my password manager, and GitHub account while I was away from my computer. I opened an abuse case with GitHub to get the account terminated.


<img width="1014" alt="Screen Shot 2022-06-19 at 5 29 29 PM" src="https://user-images.githubusercontent.com/10055792/174692459-76603612-ad14-41cc-b6d9-864b31c4d7e3.png">
