### ISSUE TITLE
HID update instructions tweak

### ISSUE THREAD

**Issue by JohnDMcMaster** [Proxmark/proxmark3#1020]
On: https://github.com/Proxmark/proxmark3/wiki/Ubuntu-Linux#flashing-hid

```
cd client/hid-flasher
make
./flasher -b ../../bootrom/obj/bootrom.elf
./flasher ../../armsrc/obj/fullimage.elf 
cd ../..
```

However the fulliamge update appears to fail because its now a ttyACM device after the bootloader update. So what worked for me was:

```
cd client/hid-flasher
make
./flasher -b ../../bootrom/obj/bootrom.elf
cd ..
# Hold pm3 button during flash
./flasher ../armsrc/obj/fullimage.elf 
cd ..
```

**Comment by hornet-hacker** [comment]
This software is not recommended for use as it is not updated anymore.  Please use [the iceman firmware](https://github.com/RfidResearchGroup/proxmark3) instead.
