### ISSUE TITLE
armsrc compile error

### ISSUE THREAD

**Issue by JiounDai** [Proxmark/proxmark3#124]
when compile armsrc in mac OSX, error happend, the error is:

../client/fpga_compress ../fpga/fpga_lf.bit ../fpga/fpga_hf.bit obj/fpga_all.bit.z  
Input files too big (total > 84672 bytes). These are probably not PM3 FPGA config files.make: *** [obj/fpga_all.bit.z] Error 255

**Comment by marshmellow42** [comment]
See #123 pull request
