### ISSUE TITLE
Error when compiling on archlinux

### ISSUE THREAD

**Issue by t3zla** [Proxmark/proxmark3#151]
I get this error when installing on arch

    In file included from ./string.h:15:0,
                     from ../common/protocols.c:2:
    ./stdint.h:16:18: error: conflicting types for 'int32_t'
     typedef int      int32_t;
                      ^
    In file included from /usr/arm-none-eabi/include/sys/types.h:62:0,
                     from /usr/arm-none-eabi/include/strings.h:13,
                     from ../common/protocols.c:1:
    /usr/arm-none-eabi/include/sys/_stdint.h:31:19: note: previous declaration of 'int32_t' was here
     typedef __int32_t int32_t ;
                       ^
    In file included from ./string.h:15:0,
                     from ../common/protocols.c:2:
    ./stdint.h:21:24: error: conflicting types for 'uint32_t'
     typedef unsigned int   uint32_t;
                        ^
    In file included from /usr/arm-none-eabi/include/sys/types.h:62:0,
                     from /usr/arm-none-eabi/include/strings.h:13,
                     from ../common/protocols.c:1:
    /usr/arm-none-eabi/include/sys/_stdint.h:32:20: note: previous declaration of 'uint32_t' was here
     typedef __uint32_t uint32_t ;
                    ^
    ../common/Makefile.common:81: recipe for target 'obj/protocols.o' failed
    make[1]: *** [obj/protocols.o] Error 1
    make[1]: Leaving directory '/home/t3zla/Documents/Projects/AUR/proxmark/proxmark3/armsrc' 
    Makefile:10: recipe for target 'armsrc/all' failed
    make: *** [armsrc/all] Error 2

**Comment by t3zla** [comment]
It works when I compile in the client directory

**Comment by iceman1001** [comment]
thats because you only compiled the client....

The error states your armsrc (firmware) didn't get compiled.

Try comment the offensive #include in protocols.c

**Comment by ikarus23** [comment]
As an archlinux user I've got this issue too. Removing the line `#include <strings.h>` from `common/protocols.c` did the trick.

Are there any downsides? Should we remove this include from the `master`?

**Comment by iceman1001** [comment]
it compiles on mingw / win  enviornment without this include.

**Comment by ikarus23** [comment]
Thanks for the reply, iceman. I will wait for some more days and remove the include if nobody complains.

**Comment by iceman1001** [comment]
I also just tried it on Ubuntu 1404,  it compiles fine.

**Comment by ikarus23** [comment]
Thanks for testing. I think it's fairly save to remove this include it it works for those two platforms. At least most of the proxmark3 people are using Windows or Ubuntu, I think.
