### ISSUE TITLE
RF Power ON between REQA. HF tag

### ISSUE THREAD

**Issue by pablito12** [Proxmark/proxmark3#155]
Hi
I want to get the information between the RF power ON and the first RQA send by a reader. I am using a Mifare Classic  tag and a i wonder if Proxmark3 allow to get this information.

**Comment by iceman1001** [comment]
I think questions like this is more suitable on the forum.
And read the wiki for answers to your question

**Comment by pablito12** [comment]
well I allready read the wiki and that's the reason why I am asking it. I am not sure if Proxmark3 give this kind of information (time between RF Power On and REQA message sen by a reader)

**Comment by iceman1001** [comment]
let me guess, you don't have pm3 device?

**Comment by W8M2Hg9lLmWqXSGC** [comment]
Use the forum. It's there for a reason.
http://www.proxmark.org/forum/index.php

**Comment by pablito12** [comment]
Actually I do have a Proxmark3 device. Probably Iceman do not understand me
