### ISSUE TITLE
Can PM3 support higher bit rates snoop?

### ISSUE THREAD

**Issue by koy0755** [Proxmark/proxmark3#157]
Can PM3 support higher bit rates(Exp:212kbps,424kbps,848kbps) snoop in future?.

**Comment by 0x6d617474** [comment]
There have been a few discussions on the forums: [[1]](http://www.proxmark.org/forum/viewtopic.php?id=1123) and [[2]](http://www.proxmark.org/forum/viewtopic.php?id=1361) and [[3]](http://www.proxmark.org/forum/viewtopic.php?id=1908) but they haven't really gotten anywhere. It would be a very handy feature... 

I assume we need to change the rate at which the fpga demodulates the signal. 3 suggests that there is already not much time for decoding at 106kbit/s, anything higher may be trouble? Any experts to chime in here please?
