### ISSUE TITLE
Compile error on Windows 10 (x64) @ /tools/mkversion.pl 

### ISSUE THREAD

**Issue by VinnieV** [Proxmark/proxmark3#169]
Hi!

Note: This error doesn't occur on a fresh installed Windows 10.

When compiling the proxmark3 firmware the compiler gives an error at the perlscript mkversion.pl.
The number before [main] increments until I get a BSOD.

If you want more information feel free to contact me.
Meanwhile I am searching for a solution. (updates will be posted)

**Compile Error:**
```
make -C bootrom all
make[1]: Entering directory `/pm3/bootrom'
perl ../tools/mkversion.pl .. > version.c || cp ../common/default_version.c version.c
      2 [main] perl 17168 child_copy: linked dll data write copy failed, 0xC2000..0xC2370, done 0, windows pid 17168, Win32 error 87
5096694 [main] perl 17168 child_copy: linked dll data write copy failed, 0xC2000..0xC2370, done 0, windows pid 17168, Win32 error 87
10103219 [main] perl 17168 child_copy: linked dll data write copy failed, 0xC2000..0xC2370, done 0, windows pid 17168, Win32 error 87
```

[BSOD dump file](http://s000.tinyupload.com/?file_id=34383980811182412077 )
(Github didn't allow my zip for some reason..)

**Comment by iceman1001** [comment]
The win32 error 87 could be a hint. Quick search gives "the parameter is wrong" as suggestion.

Do you have git installed?

**Comment by VinnieV** [comment]
Yes, git is installed.

Error 487 is also given when compiling:
`1 [main] perl 16176 child_copy: linked dll data write copy failed, 0x652000..0x652370, done 0, windows pid 16176, Win32 error 487`

**Comment by iceman1001** [comment]
git fetch --all
git describe --dirty
git rev-parse --abbrev-ref HEAD

Can you run these three git commands?  They are the basis in mkversion.pl

**Comment by VinnieV** [comment]
Jep those commands work fine.

![git](https://cloud.githubusercontent.com/assets/8697647/14022050/4fa8e542-f1de-11e5-9287-b037fe8f72ea.png)

**Comment by iceman1001** [comment]
leans towards something with perl and win10-64b...  
Which version of perl?

**Comment by VinnieV** [comment]
v5.22.1 (newest version)

![perl](https://cloud.githubusercontent.com/assets/8697647/14024055/d5da887e-f1e7-11e5-94e0-4069224bd97f.png)

**Comment by marshmellow42** [comment]
http://stackoverflow.com/questions/18502999/git-extensions-win32-error-487-couldnt-reserve-space-for-cygwins-heap-win32

**Comment by iceman1001** [comment]
if its the 'msys-1.0.dll' then a upgrade of git and mingw is needed.

**Comment by VinnieV** [comment]
Apparently adding /C/ProxSpace/msys/bin to the front of my path variable helped the perl error.
It compiles perfectly now. 
Thanks to Marshmellow and Iceman!
