### ISSUE TITLE
missing apt-get

### ISSUE THREAD

**Issue by dtest505** [Proxmark/proxmark3#186]
I'm doing it in kali (figured Ubuntu was close enough)
But apt-get install needed : gcc-arm-none-eabi

(I didn't feel cool with editing the wiki myself)

**Comment by iceman1001** [comment]
Wasn't it a seperate instruction on how to install the GCC-ARM-NONE-EABI further down in the Wiki / Ubuntu page?

Anyway,  I added your suggestion to the page,  and the 'ncurses-dev'  aswell.
