### ISSUE TITLE
LF search

### ISSUE THREAD

**Issue by theyhavelanded** [Proxmark/proxmark3#188]
Upgraded from 2.4 to 2.5
lf search
Indala E8 keeps changing UIDs
went back to 2.4 works fine. Has to be a new bug.

Thanks.

**Comment by iceman1001** [comment]
Thanks for notice,
We do need more details than this. If you set  the debug mode,  it will be more helpful

data setdebugmode 2
lf search

Use a pastebin service like  www.pastebin.com to attach the log output.

**Comment by theyhavelanded** [comment]
Unfortunately I don't have the key anymore.



On Aug 25, 2016, at 3:20 AM, Iceman <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for notice,
We do need more details than this. If you set the debug mode, it will be more helpful

data setdebugmode 2
lf search

Use a pastebin service like www.pastebin.com<http://www.pastebin.com> to attach the log output.

-

**Comment by iceman1001** [comment]
Not much to do then, until someone with an indala tag can test things out.
