### ISSUE TITLE
LF t55xx read commands broken

### ISSUE THREAD

**Issue by iceman1001** [Proxmark/proxmark3#19]
I was fiddling around in the LF t55xx commands and was always suprised with not getting some values outputted with issuing a  "lf t55xx readblock 1"..   
At least it should have given more then the  "db: done"  message.

I looked into the code in "cmdlft55x.c"  and realized that all functions only calls  "sendcommand"  but never waits for a response.
I looked into the lfops.c  in the ARMSRC,  and sure enough,  the read values is never sent back to the client.

LF T55xx read commands are flawed.

**Comment by iceman1001** [comment]
Lets see,  I'm refactoring it again to use @marshmellow42  new demods and also it will try to use more demods than before.  It used to only work with FSK,   but hopefully I can get the PSK also onboard.

**Comment by marshmellow42** [comment]
Are you able to use the startup timing of the ata55x7 to know where the datastream starts?

**Comment by iceman1001** [comment]
It uses the old way of reading / writing,   I only changed on the armsrc to be stricter with t55x7 timings.   When it comes to decoding the data stream,   it is right now just of with one bit,  which I skip ahead when I analyse the stream.  The signal has a repeating pattern and with the new timings we get the start kind of good.   This pattering is repeating all block data from 0-n, where n is configured earlier.   To divide the data into block, is not easy.  So the solution is to read individually a block n,   since the repeating pattern will start with it and the start we kind of have down to the exact spot.    
If the t55x7 tag is configured with "sequence markers"  it is easier to spot the individual blocks of data. However this setting is optional hence we can't depend on it for detection of start.

**Comment by iceman1001** [comment]
pm3 --> lf t55xx rd 0
Reading 12000 bytes from device memory

Data fetched
Samples @ 8 bits/smpl, decimation 1:1
0000000000001010
0100000000100000
0000000000001010
0100000000100000
0000000000001010
0100000000100000
0000000000001010
0100000000100000
0000000000001010
0100000000100000
0000000000001010
 Block 0    : 0x00148040  00000000000101001000000001000000



This is how it looks today,  you can see the repeating pattern quite easily but where to start..

00000000000101001000000001000000 - correct decode value ( one bit off )
00000000000010100100000000100000 - raw signal data

**Comment by iceman1001** [comment]
its about time but it seems like my remake of the T55XX commands is done.

I need some testing done from the community before I make pullrequest to the PM3 Master.


---- in short

New commands:
LF T55XX DETECT    -  reads configuration block 0 and tries to figure out the demodulation.
LF T55XX CONFIG    -  gets / sets  the new T55XX configuration setting.

LF T55XX TRACE    - reads trace (page1 block 0)  and print details
LF T55XX INFO       - reads configuration (page 0 block 0 ) and print details.
LF T55XX DUMP     -  Dumps all tag data

--- Renamed 
LF T55XX READ     - there is now only one read command :)
LF T55XX WRITE    - there is now only one write command :)

------

HOW TO USE IT:

Normally the configuration defaults to  ASK - non-inversed data.

:::    lf t55xx detect
:::    lf t55xx read 0

**Comment by marshmellow42** [comment]
minor warnings:
cmdlft55xx.c: In function 'CmdT55xxSetConfig':
cmdlft55xx.c:122: warning: 'len' may be used uninitialized in this function
cmdlft55xx.c:123: warning: 'inverse' may be used uninitialized in this
function

**Comment by iceman1001** [comment]
The selection for modulation should be an enum.
but until that day, I pushed minor fixes to remove those warnings.

**Comment by marshmellow42** [comment]
may want to be more descriptive for modulation #:
Found [2] possible matches for modulation.
Modulation: 2  Inverse: 1
Modulation: 3  Inverse: 0

the lf t5 read seems to work for some modulations some of the time.
seems there are still some timing issues. (maybe antenna dependent?)

after a successful ask/man rf/64
reading a fsk tag doesn't seem to update the output (without setting the
config) just keeps outputting the same ask/man output even though the graph
changes.

I'll have a look at the code next.  not sure when i'll get time to get far
though.

**Comment by iceman1001** [comment]
Your wish is granted,  a nicer printout for the configuration :)

You can't just swap different modulated tags and expect it to work.

just to be clear:
If you detect a  ASK tag, and read it,  
then swap to a FSK tag,  you either need to do a new detect or manually set it via config.

**Comment by marshmellow42** [comment]
I got that, but we know it will happen anyway :) , I was just confused when it outputted the same data as before even though the graph updated.  I figured a buffer needs to be cleared before reading again maybe.

**Comment by iceman1001** [comment]
Besides the PSKdemod seems off,   there is also the issue with finding where a block starts in the t55x7 sending repeating pattern.   With a SST you can find it,  but its not mandatory to set that flag....

**Comment by marshmellow42** [comment]
it will be especially difficult to know where the data starts with the current pskdemod, as it skips to the first phase change to "align" itself.
(the same can also actually be true of the ask demods, but should be significantly less and should only affect poor reads)

**Comment by marshmellow42** [comment]
for the pskdemod, I've thought about attempting to get first phase and then back up clock cycles until I hit the beginning again...
sounds like for this project that would be necessary to have any chance.

**Comment by iceman1001** [comment]
at this moment, I kind of happy that I can switch between modulations for the t55xx commands.
We can always use the "data rawdemod" command,  to get better reads..

**Comment by iceman1001** [comment]
maybe if I rotate a configuration block 32times and check to see if certain bits is correct set,  then I'll get a  "bit-offset" where it should start...

**Comment by marshmellow42** [comment]
For psk the offset will change with each read with different data. Since the first phase change moves with the data.

For the ask and FSK mods that might work.

**Comment by marshmellow42** [comment]
i just pushed an adjustment to PSKDemod and is waiting in my pull request that adds back in the skipped bits.  it should now be able to be used along with the t55xx commands now with some consistency.
NOTE: it no longer returns the number of errors found but returns 1 for success and 0 for failed.

**Comment by iceman1001** [comment]
Got it,   However the whole PSK demod and t55x7 doesn't seem to like eachother. 
The FSK, ASK works decent,  together now with the offset in bitstream it is possible for find a correct value kind of fast.  Not like before :)

But the PSK demods, just looks crazy.

**Comment by iceman1001** [comment]
And the detect-modulation code kind of narrows it kind of well at the moment. Feels like I should be able to push it to PM3.  I wait until @marshmellow42  PR is commited.

**Comment by iceman1001** [comment]
@marshmellow42  and I have tested the remake of t55xx commands and they work pretty well.
Plenty of demod options, works with loaded traces.  Try it and enjoy it. 

Only one thing missing,  that is the new  DETECT/INFO/TRACE commands doesn't work when there t55x7 tag is password protected. 

For the configuration block, (INFO) a workaround would be the following. 
Do normal read block 0 with password,  use the INFO with "1",  to use the previous loaded blockdata from graphbuffer.  This does not work for the TRACE. :(  

However its not a hug thing to implement password usage for DETECT/INFO/TRACE.

**Comment by iceman1001** [comment]
And again I've issue with creating a PR..

**Comment by marshmellow42** [comment]
I can from mine if you'd like.  I'm still working on expanding the implantation a little and testing heavily.

**Comment by marshmellow42** [comment]
After that it would be easy from my fork.

**Comment by iceman1001** [comment]
@marshmellow42  Go for it,
You can test the new lua scripts aswell.  It give you an oversight on where / when some demods doesnt work.

**Comment by marshmellow42** [comment]
I have some fixes to nrz, psk and FSK  and I'm looking at others.  The demods were not originally designed for critical start positions.

**Comment by marshmellow42** [comment]
I am struggling a bit with FSK when there are either a lot of zeros or ones it tends to add an extra bit.  It is a rounding error and how the chip creates the the clock from a field clock that doesn't divide into it.  Anyone have a better idea.  Specifically the aggregate_bits function.

**Comment by marshmellow42** [comment]
Seems to affect fsk2 and fsk1a a little more than others

**Comment by iceman1001** [comment]
I undestand that, and I apprecate your efforts a lot. 
With the possibility to set starting position in the bitstream, it is more up to the user now to know how a valid configuration block looks like. :)  

But with different bitrates/clockrates for PSK  and the different modulations it is bound to have some stupid setting which we can't read.  But we can always write to a t55x7 tag regardless what we configured it
---
Is the packing of bits fixed length ?  

1111111100000000111 -> 10
or
1110001111111100011 -> 10101

**Comment by marshmellow42** [comment]
For FSK it changes per FSK type and bit value

**Comment by marshmellow42** [comment]
This problem with FSK creates some blocks read well and others are incorrect if there are a lot of leading zeros, and there is no way to know it isn't correct. Try putting something in the last byte of a block leaving the others 0s and it the results vary with clock values and FSK types.

**Comment by marshmellow42** [comment]
For FSK 2a  10/8 RF/50 it should take something like:
1111110000011111111111100000111111100000
Turns into
0100101
Notice the fourth set of 1s above has an extra bit (wave . This is to compensate for 8 not dividing into 50.  Every fourth 8fc wave will have an extra wave.  But fsk1a seems to handle this differently creating a partial wave.
 To

**Comment by iceman1001** [comment]
So for FSK2a 10/8 RF/50  you need to count the zeros,
and for  FSK2 8/10 RF/50 you need to count the ones to fit into the 50.

**Comment by marshmellow42** [comment]
You count both but the 10 devides evenly into 50 so 5 0s =1 1 for fsk2a but yes for fsk2 it is opposite.

**Comment by marshmellow42** [comment]
When it goes to RF/64 the 10 no longer divides evenly into 64 so it has to make up the difference somewhere

**Comment by iceman1001** [comment]
With this PR #82  we can close this issue.  Finally.

**Comment by jzp113** [comment]
I found the lf t55xx config can't set the decode of Manchester Encoding

**Comment by jzp113** [comment]
@iceman1001 me too I aslo found the bug

**Comment by iceman1001** [comment]
Its not possible to set manchester encoding with "lf t55xx config".
If you know the signal is man-encoded,   then try the "data rawdemod" commands instead.

the config commands deals with signal modulation/demodulation of signal,  not  decode/encode of data.   There is a difference. 

However, which bug have you found?   Open a new issue so it gets the proper attention

**Comment by jzp113** [comment]
@iceman1001 fine, but it make me feel puzzled.why not add the manchester encoding with "lf t55xx config".

**Comment by jzp113** [comment]
@iceman1001 and it's my fault  I want to say that  lf t55xx config can't set the modulation of Manchester

**Comment by marshmellow42** [comment]
You both appear to be confused...  
@jzp113 The lf t55xx config command configures the lf t55xx read commands, it does not configure a t55xx chip.

@iceman1001 the t55xx does not distinguish between modulation and encoding it sets both with some of its modes.  Manchester mode sets both modulation to ASK and encoding to Manchester, same with BIPHASE mode - sets both modulation and encoding.

**Comment by jzp113** [comment]
@marshmellow42 I know the t5557 block 0 config which is modulator＝Manchester  Bit Rate＝RF/32.But I don't know how to use proxmark to read the data of card. above it the if t55xx command see doesn't work.realy?or try then try the "data manrawdecode" or "data rawdemod" commands instead.

**Comment by iceman1001** [comment]
Yes, the t55xx has many possibilites and as you say it mixes things up just to keep us on our toes. 
Reading on the net about modulation and encoding of LF signal,  then read the t55xx documentation and you get confused.  It would have been easier if it didn't mix up the different concepts.

@jzp113  You can read the tag data in two different ways.  Either you read the "raw" blocks from the t55xx via the  "lf t55xx read" commands.  Or you read the data which the t55xx tries to pretend to be with the normal  "lf search"  "lf read" "data sample"  "data rawdemod"

You don't need to set the configuration if you want to use the "lf t55xx write" command.

**Comment by marshmellow42** [comment]
And with the latest versions the t55xx config command shouldn't be necessary but use the LF t5 detect command to auto set the config before reading t55xx blocks.   (There are a few config settings that are known to not work... Like if the tag is configured to use a sequence terminator.)
