### ISSUE TITLE
`lf hid fskdemod` continues to TX a CW

### ISSUE THREAD

**Issue by samyk** [Proxmark/proxmark3#203]
Running d1057e7a2105d5e2696df185482176f22a5bd669

When ending `lf hid fskdemod` by pressing the button and confirm the light turns off and getting`#db# Stopped` in pm3 client, an oscilloscope reveals the antenna is still transmitting a carrier wave.

**Comment by iceman1001** [comment]
You are correct and thanks!

There is no call to **FpgaWriteConfWord(FPGA_MAJOR_MODE_OFF);**
inside lfops.c  methods CmdHIDdemodFSK  nor CmdAWIDdemodFSK ..  I've added it to my fork. I'm guessing @marshmellow42  will add them and push a PR to Pm3 Master soon.

**Comment by iceman1001** [comment]
There was also the same problem with 'lf io fskdemod' 
also fixed and pushed.

**Comment by marshmellow42** [comment]
this is addressed for the master in #202 pull request.

**Comment by iceman1001** [comment]
fixed, merged and now closed.

**Comment by samyk** [comment]
Sweet!
