### ISSUE TITLE
Proxmark.org hijacked?

### ISSUE THREAD

**Issue by pwpiwi** [Proxmark/proxmark3#210]
Forwards to aviationmegastore.com.

**Comment by iceman1001** [comment]
its been noted.

**Comment by Xoib** [comment]
If the administrator needs help, I can offer some sysadmin skills.

**Comment by iceman1001** [comment]
Thank you for the offer,  but at this moment it is more of getting hold of the Webhosting company.

**Comment by iceman1001** [comment]
Seems like the site is actually up,  but the aviationmegastore redirect is caused from a local installed virus(?!)
Running on another browser,  I can reach the forum.
Its on my firefox I have this problem. 
Restarting my computer, I can get access also for ftp.

**Comment by dylangerdaly** [comment]
I can get to the site from a Linux box:
```
[user@personal-web ~]$ dig @8.8.8.8 A www.proxmark.org

; <<>> DiG 9.10.4-P5-RedHat-9.10.4-3.P5.fc24 <<>> @8.8.8.8 A www.proxmark.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43297
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.proxmark.org.		IN	A

;; ANSWER SECTION:
www.proxmark.org.	14399	IN	A	37.44.12.83

;; Query time: 895 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Feb 04 00:17:54 AEDT 2017
;; MSG SIZE  rcvd: 61

[user@personal-web ~]$ curl http://www.proxmark.org/forum/viewforum.php?id=33 | grep \<title\>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 19252    0 19252    0     0   7360      0 --:--:--  0:00:02 --:--:--  7362
<title>iClass / Proxmark developers community</title>
```

**Comment by iceman1001** [comment]
yes, its up.   But if you were hit by that local redirect,  you need to clean it out from web browser.

**Comment by dylangerdaly** [comment]
Yikes :/ maybe put out a tweet?

**Comment by zhovner** [comment]
I was get redirected too. So it's not a local virus.

**Comment by pwpiwi** [comment]
Redirected on Windows, Linux and Android. And only proxmark.org is affected. Either it is the Mega-Virus of the centry or no local virus at all. I would bet on the latter.

**Comment by iceman1001** [comment]
Must have been local,  since I use multiple computers from same IP,  and those who surfed site when mega-hit,  always got redirected. 
But those computers who didn't, can surf direct to site. 
Cleaning out webcache, sorted it out.

My guess is javascript-based crap and a bug in fluxBB ..  Im guessing the user "signature" bug.
