### ISSUE TITLE
Error loop using "lf t55 wakeup" without "p" param

### ISSUE THREAD

**Issue by masterix21** [Proxmark/proxmark3#267]
Hi dears, 

if you use "lf t55 wakeup 11223344" without p param, software stop working with in a loop.

Example, that works:
`proxmark3> lf t55 wakeup p 11223344
Wake up command sent. Try read now
proxmark3>`

Example with infine loop:
`proxmark3> lf t55 wakeup 11223344
Unknown parameter '1'
Unknown parameter '1'
Unknown parameter '1'
Unknown parameter '1'
Unknown parameter '1'
Unknown parameter '1'
Unknown parameter '1'
...
...
LOOP
...
...
Unknown parameter '1'
Unknown parameter '1'
Unknown parameter '1'
Unknown parameter '1'
Unknown parameter '1'
Unknown parameter '1'
Unknown parameter '1'`

**Comment by marshmellow42** [comment]
the while loop is missing "&& !errors"

I'll fix it in my next pull.  i'm working on the t55xx commands anyway.

**Comment by masterix21** [comment]
Great :) 

i think could be simplified the usage with:
`lf t55xx wakeup [h] <password>`
exactly like dump command, because a wakeup is possible only with password.

Anyway, thanks.
