### ISSUE TITLE
HID Prox Standalone Mode is Broken

### ISSUE THREAD

**Issue by digitalentropy** [Proxmark/proxmark3#29]
I've noticed that in the last few builds the standalone mode is broken.  I've gone back and recompiled every version back to the merge from 9/19 (92d255d3) and have found that that is the last known-good version of the code that functions correctly.  The merge from 10/24 breaks it.

Thoughts on what's happening?

**Comment by marshmellow42** [comment]
I've found the issue and will patch it soon

**Comment by marshmellow42** [comment]
pull request #51 has the fix

**Comment by marshmellow42** [comment]
this now functions in my testing.
