### ISSUE TITLE
hf mf dump 2 File reading error. 

### ISSUE THREAD

**Issue by thesle3p** [Proxmark/proxmark3#296]
Hi I get a ```File Reading error.``` bug when ever I try and dump a mifare 2k card. I have no trouble cracking the card or  reading individual blocks 
but when ever I run ```hf mf dump 2``` on the card I get that error. I confirmed that my dumpkeys.bin file is reachable etc. Here is the info on the card
```
proxmark3> hf search
          
 UID : db b4 a8 79           
ATQA : 00 04          
 SAK : 08 [2]          
TYPE : NXP MIFARE CLASSIC 1k | Plus 2k SL1          
proprietary non iso14443-4 card found, RATS not supported          
Answers to chinese magic backdoor commands: NO          

Valid ISO14443A Tag Found - Quiting Search
```

**Comment by iceman1001** [comment]
That error message shows when the client fails to read the dumpkeys.bin file.
How did you create the dumpkeys file?

**Comment by thesle3p** [comment]
Tried doing manual ```hf mf chk * ? ``` followed by ```hf mf nested 1 0 A <key>   d ```  as well as by running ```script run mfkeys ``` same result both times.

**Comment by iceman1001** [comment]
and the results was?

**Comment by thesle3p** [comment]
That's what got me here.......

**Comment by thesle3p** [comment]
Update: when I do ```hf mf dump``` it is able to dump blocks (but not write to file) and tries to iterate past  the number of blocks on the card, I am guessing because it does not know it's a 2k card. it's only when I run ```hf mf dump 2```  that it fails to read dumpkeys.bin.

**Comment by pwpiwi** [comment]
`hf mf dump` withou a size parameter assumes a 1K card, i.e. it shouldn't iterate past the number of blocks on a 2K card. What error messages do you get in this case?

`hf mf chk * d` without a size parameter assumes a 1K card and would write a dumpkeys.bin file with keys for the first half of a 2K card only.

`hf mf nested 1` : The 1 indicates 1K memory. You get only half of the keys of a 2K card.

It would really help if you paste the commands and the responses here.

**Comment by pwpiwi** [comment]
BTW: How do you know that you have a 2K card?

**Comment by iceman1001** [comment]
@thesle3p   how did it go?  You solved your issue?  Time to close?

**Comment by iceman1001** [comment]
Since @thesle3p  has not answered the questions, I will close this one.  Open a new issue with more information if needed
