### ISSUE TITLE
compile issues on ubuntu 14.04

### ISSUE THREAD

**Issue by marshmellow42** [Proxmark/proxmark3#305]
ubuntu 14.04 inside vm (no other method of testing atm)
gcc 4.8.2

error:
```
gcc -MT obj/hardnested/hardnested_bf_core_NOSIMD.o -MMD -MP -MF obj/hardnested/hardnested_bf_core.Td -std=c99 -D_ISOC99_SOURCE -I. -I../include -I../common -I../zlib -I/opt/local/include -I../liblua -Wall  -g -O3 -DHAVE_GUI -mno-mmx -mno-sse2 -mno-avx -mno-avx2 -mno-avx512f -c -o obj/hardnested/hardnested_bf_core_NOSIMD.o hardnested/hardnested_bf_core.c
gcc: error: unrecognized command line option ‘-mno-avx512f’
make[1]: *** [obj/hardnested/hardnested_bf_core_NOSIMD.o] Error 1
make[1]: Leaving directory `/home/user/master/client'
make: *** [client/all] Error 2

**Comment by marshmellow42** [comment]
i believe i have a fix for this i'll publish after piwi's makefile changes are pushed.

**Comment by pwpiwi** [comment]
The avx512 compiler options have been added in GCC 4.9

**Comment by marshmellow42** [comment]
i found it was odd that my windows gcc 4.9.2 didn't complain about the make file switches but it did complain about the `__builtin_cpu_supports("avx512f"))` which evidently wasn't supported until 5.3

so i'll have some makefile tests coming.  :(
