### ISSUE TITLE
v3.0.1

### ISSUE THREAD

**Issue by iceman1001** [Proxmark/proxmark3#314]
Since the compilation errors for some envs has been fixed;  I suggest a minor new release.
I've started the draft,  feel free to update it with text.  I also think we can add the "hitag2" PR before we release.

Link to draft
https://github.com/Proxmark/proxmark3/releases/tag/untagged-0101d2f2c7af775951c4

**Comment by pwpiwi** [comment]
I thought as well. This would finally be a working release for the homebrew tap.

CHANGELOG.md should be up to date before releasing.

**Comment by iceman1001** [comment]
Something you will sort out now?

**Comment by marshmellow42** [comment]
There are some new severe coverity issues with the hardnested and some other code I think should be addressed first.

**Comment by marshmellow42** [comment]
The more I think on it fixing all the coverity scan issues will take time, once complete we should do another release, but the recent fixes warrants a release now as well.

**Comment by pwpiwi** [comment]
CHANGELOG.md updated. Regarding the hitag2 PR I would prefer to have it tested by someone before merging.

**Comment by iceman1001** [comment]
Neither marshmellow or I have access to hitag2 tags.   If you (piwi) don't,  we have to find someone who has.  I believe someone contacted me about it.  I'll check and see if I can get hold of that user to test it out for us.

**Comment by iceman1001** [comment]
So, with @marshmellow42  latest PR merge.  Where are we on this one?

**Comment by marshmellow42** [comment]
I'm not aware of any other compatibility issues.  I'm going to work on a few coverity issues, but they aren't high impact.

**Comment by iceman1001** [comment]
and @pwpiwi ?  

Still no news about Hitag2 write PR.

**Comment by marshmellow42** [comment]
before potentially breaking(low probability) the repo with new functionality (hitag2 write) i think we should go ahead with 3.0.1 release and then update the homebrew tap to use that release by default.

then we can go from there.

**Comment by marshmellow42** [comment]
unless pwpiwi has something more to add/fix first..

**Comment by iceman1001** [comment]
I've some minor fixes to hardnested..   But with my fork, I can't push PRs.  
I mailed @pwpiwi  about it.

**Comment by marshmellow42** [comment]
you need a branch that is at the master head.  :p

**Comment by iceman1001** [comment]
Despite what ppl think of me, I'm not that good at Git.  So I can make a branch based on pm3 master?!?  I didn't know that.  Third thing I learned today

**Comment by pwpiwi** [comment]
Let's go for it. Seems to be quite settled as it is.

**Comment by iceman1001** [comment]
Ok.  tag v3.0.1 is created. 
I've also made a PR for the homebrew repo.
