### ISSUE TITLE
How decode iso14443 protocol ?

### ISSUE THREAD

**Issue by maxben14** [Proxmark/proxmark3#323]
How to decode the protocol of communication between the reader and the card? In my file recorded this protocol through the radio at the frequency of the mifare. I want to translate this into the format of the command's proxmark. Tell me how to do this?
I think use function `MillerDecoding`
https://github.com/Proxmark/proxmark3/blob/master/armsrc/iso14443a.c

**Comment by marshmellow42** [comment]
You have a lot more research to do.  There is no direct answer for you.  ISO14443 has many protocols under it.  And you have not specified any hardware this is for, or if you are working on an open source project as is supported here.

Therefore there is no direct answer for you.  

Ultimately this would be a discussion to have on the forum as it doesn't appear to have anything to do with the further development of the proxmark3.

**Comment by maxben14** [comment]
I read this atile http://anyram.net/blog_ru/?p=814 about sniffer mifare protocol.
In aticle there is file is sniff prototcol mifare iso14443a. I want from this file get command for example ataq, reqa. How this do ? Can me write how from file get Miller and Manchester cod ?

File sniff protocol mifare: https://yadi.sk/d/WJ5Wi-4h3KFxHt

**Comment by marshmellow42** [comment]
I'm not sure any code there would be helpful to a SDR project.  There are many factors to consider.  But again this discussion is better suited to the proxmark3 forum.  http://www.proxmark.org/forum/index.php

**Comment by marshmellow42** [comment]
The main reason I say the code may not help is the proxmark3 has an FPGA (hardware) that does preprocessing of the signal before it gets to the code you are looking at.  You can't just run raw signal through it.

**Comment by pwpiwi** [comment]
With a radio you will pick up the reader signals only. The tag doesn't send actively.
