### ISSUE TITLE
confusion in fdx command help content

### ISSUE THREAD

**Issue by ntkntk** [Proxmark/proxmark3#324]
Incorrect help: 
"proxmark3> lf fdx clone
Clone a FDX-B animal tag to a T55x7 tag.
Usage: lf animal clone [h] <country id> <animal id> <Q5>
Options:
      h            : This help
      <country id> : Country id
      <animal id>  : Animal id
      <Q5>        : Specify write to Q5 (t5555 instead of t55x7)

Sample: lf animal clone 999 112233
"
the reality:
"proxmark3> lf fdx clone 999 112233
Preparing to clone FDX-B to T55x7 with animal ID: 0999-112233
Blk | Data
----+------------
 00 | 0x00098080
 01 | 0x0032d6dc
 02 | 0x0402079f
 03 | 0xc0402338
 04 | 0x28040201
proxmark3>
"

**Comment by iceman1001** [comment]
Thanks for pointing this out,  there is a PR which solves this one. 
https://github.com/Proxmark/proxmark3/pull/328/commits/aa6a9849697c455cb6f08f8f12362bf8e01adc43
