### ISSUE TITLE
HID is broken in R301

### ISSUE THREAD

**Issue by ntkntk** [Proxmark/proxmark3#327]
input format of FC is not correct.

Gentlemen 
following andy reported that using iceman fork, HID card copied but not working on the real reader. I see similar fault too while working on updating the PM3 command in the GUI, I found the new HID command also breaks the r3.01 main repo.

The reason was . the fault sleaks in since the confusion in the format of input,  I think since our study with AWID,  IOprox, XFS or Kantech...where the imprint on abel is HEX and the real FC actually in DEC so how to interpret them we have to be careful. @Jason or @Iceman pointed out at that time.

Using the basic excel calculation table I knew for FC 118 (in DEC) and Card ID 2348
lf t55xx wr b 0 d   00107060
lf t55xx wr b 1 d   1D555955
lf t55xx wr b 2 d   5569A9A5
lf t55xx wr b 3 d   56596695

so if having done that to t55x7 I can check
[code]
proxmark3> lf sea
NOTE: some demods output possible binary
  if it finds something that looks like a tag
False Positives ARE possible

Checking for known tags:

HID Prox TAG ID: 2006ec1258 (2348) - Format Len: 26bit - FC: 118 - Card: 2348
Valid HID Prox ID Found!

[/code]
this is correct, as expected.

Now using direct clone command
[code]
proxmark3> lf hid clone 118 2348
Cloning tag with ID 011822348
#db# DONE!
proxmark3> 
proxmark3> lf hid dem
HID Prox TAG ID: 011822348 (4516) - Format Len: 37bit - FC: 280 - Card: 70052

proxmark3>lf sea
NOTE: some demods output possible binary
  if it finds something that looks like a tag
False Positives ARE possible

Checking for known tags:

HID Prox TAG ID: 011822348 (4516) - Format Len: 37bit - FC: 280 - Card: 70052

Valid HID Prox ID Found!

[/code]

that is wrong. definitely not what I want.

... and  the cause is: 

Because the command thought we give it the HEX 118 equal 280 in DEC so it interprets that "wrong way round" and pull everything following in wiegand sequence aparted.

As this FC format input is fundamental we need to check all tag types using this input code, ask people for testing and release quickly a r3.0.2.

**Comment by marshmellow42** [comment]
The master repo doesn't take fc or card number as inputs for the lf hid cmds.  Nor should it.  If you use it wrong it will not work.
