### ISSUE TITLE
IO command merged issues

### ISSUE THREAD

**Issue by ntkntk** [Proxmark/proxmark3#331]
Firstly when run lf io clone command, the report seems to mix with a simulation command
"proxmark3> lf io clone 1 7 53156
Cloning tag with ID 00000001 77553156          
Press pm3-button to abort simulation  "

Secondly, in the command help file, the format and range of parameter for the argument should  be informative. I thought I recall it was there last year. Now is:
"lf io clone h
Cloning tag with ID 00000000 00000000          
Press pm3-button to abort simulation          "

**Comment by marshmellow42** [comment]
the io clone command has not been changed since @penturalabs first implemented it.

feel free to enhance it if you desire.
