### ISSUE TITLE
Make a "snap" for Ubuntu and other Linux distros

### ISSUE THREAD

**Issue by jonpolak** [Proxmark/proxmark3#353]
Was wondering if anyone tried to make a [snap](https://snapcraft.io/create/) of this? If not, I've started to make one.

**Comment by iceman1001** [comment]
Go for it!  Btw, what is snap and how do you use it?

**Comment by jonpolak** [comment]
@iceman1001  [What is a SNAP](https://www.ubuntu.com/desktop/snappy)

**Comment by pwpiwi** [comment]
A homebrew for Linux?

**Comment by iceman1001** [comment]
...so it distributes binaries?  or?   since pm3 project has a tendency to want users to use the latest source code, which is not always the latest release

And how is it going for you?

**Comment by jonpolak** [comment]
I'm not in the mac world...so don't know about homebrew. It is a way to
have the latest source compiled automatically and people on linux can
update all their snaps with a single command. The client wont need to
download any dependencies -- it's a self contained binary that's
automatically compiled for each supported OS.

**Comment by iceman1001** [comment]
time to close?

Since this not a issue,  
and the question is asked is "No,  noone has done a snap for pm3".
this might aswell be closed

**Comment by jonpolak** [comment]
yes close.
