### ISSUE TITLE
Simulate a special 14a card

### ISSUE THREAD

**Issue by maozhenyu123** [Proxmark/proxmark3#360]
I got a special 14a card. The UID saves in block 1 

Communications between Reader and Card:

Reader: WUPA 0x 52
Card Answer: 03 00  as  ATQA
Reader: 30 01 (Read Block 1 as UID)
Card Answer: XX XX XX XX CRC CRC
XX XX XX XX stands for UID

So....
How can I simulate this kind of cards? Should I build my own firmware to do do?

**Comment by iceman1001** [comment]
On the top of my head,  you can write a lua-script and using **hf 14a raw** commands to simulate this tag.
or you can add it to **hf 14a sim** code on the deviceside,  where you input identify type / uid to be used as simulation.  in armsrc you make this specific behavior.  Quite easy I say

**Comment by maozhenyu123** [comment]
Ehh. I edited some codes, recompiled the firmware and flashed it to my PM3. But......
It seems not working well.

Not responding on Mac///// On Windows, I got 0.00V after using "hw tune"

But other functions work

**Comment by iceman1001** [comment]
thats strange..  are you sure you have the same firmware and client from the same repo?  
Don't mix them!

And look if the usbmodem### has changed

**Comment by maozhenyu123** [comment]
I am pretty sure.....
And I use the new code(####). Failed.

I am gonna do that again.

**Comment by maozhenyu123** [comment]
Cool! Done.

**Comment by iceman1001** [comment]
close?
