### ISSUE TITLE
proxmark.org is down?

### ISSUE THREAD

**Issue by jsoiluva** [Proxmark/proxmark3#363]
Hi Guys,

I know here is not a good place to post this question, but I just noticed proxmark.org or promark.nl are not reachable anymore. seems the site is totally down.

does anyone know what happened to our playground?
It would be a shame to see a lot of excellent topics disappeared like this.

**Comment by iceman1001** [comment]
It happens sometimes.  It was up this morning,  down some time,  then up,  and now it seems to be down again.   Could be the webhosting company doing things with the server.
Its not like the site is gone forever,  I'm sure it will be up again soon.

**Comment by jsoiluva** [comment]
@iceman1001 great to hear that. thank you for your reply. cheers
