### ISSUE TITLE
Why is Mac OS 10.11.3 unable to read tag?(question)

### ISSUE THREAD

**Issue by johnreese2017** [Proxmark/proxmark3#368]
<img width="262" alt="1" src="https://user-images.githubusercontent.com/30405267/28784466-64240366-75c8-11e7-9327-c82548671fee.png">
always come up with invalid serial port
why?totally new on rfid 
ask for help

**Comment by marshmellow42** [comment]
Because lf search is not the port your device is attached to.  Read the wiki.

**Comment by johnreese2017** [comment]
sorry,still don't understand

**Comment by johnreese2017** [comment]
sorry,where can I find the wiki of this?

**Comment by iceman1001** [comment]
...when you read this thread...  raise your eyes up,  above your title row "why is mac os 10.11.3..",  there you see  **Code Issues Pull Requests Projects Wiki Insights**

Try clicking **Wiki** and start reading it.

**Comment by johnreese2017** [comment]
This time it shows<img width="241" alt="2" src="https://user-images.githubusercontent.com/30405267/28785340-f80b5cee-75ca-11e7-9f55-dda1235f8f64.png">

**Comment by johnreese2017** [comment]
Thank You@iceman1001
And what I want to ask is which part of the wiki "definitely"

**Comment by iceman1001** [comment]
how about we start from the beginning. 
*  hw version
*  hw tune
* lf search

Run those commands, and paste the output here so we can have a baseline of information.

**Comment by johnreese2017** [comment]
no problems for now,thank you
