### ISSUE TITLE
FPGA lo_simulate.v purpose / use

### ISSUE THREAD

**Issue by iceman1001** [Proxmark/proxmark3#375]
FPGA code,   the file lo_simulate.v  indicates that its use is for  low frequency simulation. 
However I fail to see its ever been call inside fpga_lf.v,  not even referenced.  
There is no mode for it on the armside either.  

What has happend it?  Out of date because of izsh's improved edge_detect?   Since on arm,  we use the 
mode FPGA_MAJOR_MODE_LF_EDGE_DETECT when simulating LF.

Not to forget to mention that its not even called in the fpga/makefile

ref:
https://github.com/Proxmark/proxmark3/blob/master/fpga/lo_simulate.v
https://github.com/Proxmark/proxmark3/blob/master/fpga/Makefile

**Comment by pwpiwi** [comment]
Correct. It has been replaced by lo_edge_detect.v

**Comment by iceman1001** [comment]
ok
