### ISSUE TITLE
What is this iclass_dump.bin file?

### ISSUE THREAD

**Issue by ikarus23** [Proxmark/proxmark3#39]
A binary file in a source folder?
What is its purpose?

Commit: 6f101995b633112d092b4f61b9fb2345f85ba353
File: https://github.com/Proxmark/proxmark3/blob/master/client/loclass/iclass_dump.bin

**Comment by holiman** [comment]
It's a file which contains the dump from an elite system. It is used for 'hf iclass loclass t', a self-test which verifies that the loclass crypto algos are intact/correct.

**Comment by ikarus23** [comment]
Thanks for clearing that up!

OT: Are the traces (https://github.com/Proxmark/proxmark3/tree/master/traces)  also for self testing? Or just for "scientific" analysis?

**Comment by holiman** [comment]
My impression is that they are for testing, but not as in "verify functionality via self-test", but instead example dumps of various tags, to be used in lack of real tags when doing development.
