### ISSUE TITLE
`lf em 410xsim` does not work without some other LF commands first

### ISSUE THREAD

**Issue by doegox** [Proxmark/proxmark3#390]
Hi,

When running `lf em 410xsim` immediately after power-up, the command acts as normal but a reader doesn't see the emulated tag.
Apparently there is some missing LF initialization.
If running e.g. `lf search` or `lf em 410xread 1` first, then the `lf em 410xsim` works properly.

**Comment by iceman1001** [comment]
that should work,  there was a fix some issue with that before. 
However,  if the FPGA was in HF mode before,   and you executed em sim,  the command FpgaDownloadAndGo(FPGA_BITSTREAM_LF)  will destroy your simulation data needed.
This is commented in the source code. 

If device was in LF mode,  the sim works on the first run.
in iceman fork there is a solution,  still pm3 offical might just need to do a single call to CmdSetDivisor("89") before CmdLFSim("0") in  cmdlfem4x.c

**Comment by pwpiwi** [comment]
Fix was PR #369. Which Version do you use?

**Comment by iceman1001** [comment]
...and I beg the diff.  The PR which piwi refers to has this problem I just mentioned.
The call to FpgaDownloadAndGo(FPGA_BITSTREAM_LF)
as seen here https://github.com/Proxmark/proxmark3/blob/master/armsrc/lfops.c#L390  is the cause to it.

**Comment by marshmellow42** [comment]
I'm not certain #369 fixed this call.  It fixed others but the em sim cmds are build differently.

**Comment by iceman1001** [comment]
luckily its quite easy to reproduce.  

1. make sure device is in HF mode.
2. lf em4x sim...
3. and the sim should fail..

vs.
1. lf search
2. lf em4x sim
3.. and the sim is ok (which is what @doegox points out)

**Comment by doegox** [comment]
FTR I was using official/v3.0.1-75-g1dae9811-suspect

**Comment by iceman1001** [comment]
Would you mind just verify it with

hf 14a read
lf em4x sim

**Comment by doegox** [comment]
indeed @iceman1001  lf em sim fails when the hf command is issued before.

In one single session:

```
lf search
lf em 410xsim => ok
hf 14a read
lf em 410xsim => fail
```

**Comment by iceman1001** [comment]
perfect. 
You can either patch in on the client side, in lfem4x.c ,  with a CmdSetDivisor("95") .
Or on deviceside..

iceman fork solves it on the deviceside.

**Comment by marshmellow42** [comment]
see #391 for a patch.

**Comment by marshmellow42** [comment]
this was on my list of things to do anyway, as i fixed the other sim commands but hadn't gotten to the raw lf sim command.  this just pushed it along.. ;)

**Comment by doegox** [comment]
it works fine now, thanks a lot @marshmellow42 and @iceman1001 !
