### ISSUE TITLE
hf mf hardnested error

### ISSUE THREAD

**Issue by merlokk** [Proxmark/proxmark3#404]
hf mf hardnested causes runtime error while compiled on windows10
proxmark3 just ended process by error.

**Comment by merlokk** [comment]
Unhandled exception [13056] and try to execute debugger

**Comment by merlokk** [comment]
hangs here:

brute_force_per_second = brute_force_benchmark();

**Comment by merlokk** [comment]
in float brute_force_benchmark()
here:
	brute_force_bs(&bf_rate, test_candidates, 0, 0, maximum_states, NULL, 0);

**Comment by merlokk** [comment]
in
bool brute_force_bs(...)

here:
	for(uint32_t i = 0; i < NUM_BRUTE_FORCE_THREADS; i++){
		thread_args[i].thread_ID = i;
		thread_args[i].silent = silent;
		thread_args[i].cuid = cuid;
		thread_args[i].num_acquired_nonces = num_acquired_nonces;
		thread_args[i].maximum_states = maximum_states;
		thread_args[i].nonces = nonces;
		thread_args[i].best_first_bytes = best_first_bytes;
		pthread_create(&threads[i], NULL, crack_states_thread, (void*)&thread_args[i]);
	}

**Comment by merlokk** [comment]
as i see maybe in thread here
static void* crack_states_thread(void* x){

**Comment by merlokk** [comment]
log like that
proxmark3>  hf mf hardnested 0 A A0A1A2A3A4A5 4 A FFFFFFFFFFFF
--target block no:  4, target key type:A, known target key: 0xffffffffffff, file action: none, Slow: No, Tests: 0
TThread 1 starts working on bucket 1
Thread 2 starts working on bucket 2
Thread 0 starts working on bucket 0
hread 3 starts working on bucket 3

**Comment by merlokk** [comment]
breaks here            
 const uint64_t key = crack_states_bitsliced(thread_arg->cuid, thread_arg->best_first_bytes, bucket, &keys_found, &num_keys_tested, nonces_to_bruteforce, bf_test_nonce_2nd_byte, thread_arg->nonces);

**Comment by marshmellow42** [comment]
I compile and run on Windows 10 and have no issues with hardnested.  Check that you have all the files required in the correct locations.  Check file permissions (admin elevated access).  Tell us your exact cpu

**Comment by merlokk** [comment]
CPU-Z version			1.81.0.x64
Processors
-------------------------------------------------------------------------
Number of sockets		1
Number of threads		4
APICs
-------------------------------------------------------------------------
Socket 0	
	-- Core 0	
		-- Thread 0	0
	-- Core 1	
		-- Thread 0	1
	-- Core 3	
		-- Thread 0	3
	-- Core 2	
		-- Thread 0	2
Timers
-------------------------------------------------------------------------
	ACPI timer		3.580 MHz
	Perf timer		2.943 MHz
	Sys timer		1.000 KHz
Processors Information
-------------------------------------------------------------------------
Socket 1			ID = 0
	Number of cores		4 (max 4)
	Number of threads	4 (max 4)
	Name			AMD Athlon II X4 640
	Codename		Propus
	Specification		AMD Athlon(tm) II X4 640 Processor
	Package 		Socket AM3 (938)
	CPUID			F.5.3
	Extended CPUID		10.5
	Brand ID		9
	Core Stepping		BL-C3
	Technology		45 nm
	TDP Limit		95.0 Watts
	Core Speed		3013.3 MHz
	Multiplier x Bus Speed	15.0 x 200.9 MHz
	HT Link speed		2008.8 MHz
	Stock frequency		3000 MHz
	Instructions sets	MMX (+), 3DNow! (+), SSE, SSE2, SSE3, SSE4A, x86-64, AMD-V
	L1 Data cache		4 x 64 KBytes, 2-way set associative, 64-byte line size
	L1 Instruction cache	4 x 64 KBytes, 2-way set associative, 64-byte line size
	L2 cache		4 x 512 KBytes, 16-way set associative, 64-byte line size
	Max CPUID level		00000005h
	Max CPUID ext. level	8000001Bh
	Cache descriptor	Level 1, I, 64 KB, 1 thread(s)
	Cache descriptor	Level 1, D, 64 KB, 1 thread(s)
	Cache descriptor	Level 2, U, 512 KB, 1 thread(s)
	FID/VID Control		yes
	FID range		4.0x - 15.0x
	Max VID			1.400 V
	# of P-States		4
	P-State			FID 0xE - VID 0x0C - IDD 19 (15.00x - 1.400 V)
	P-State			FID 0x7 - VID 0x14 - IDD 14 (11.50x - 1.300 V)
	P-State			FID 0x2 - VID 0x1C - IDD 13 (9.00x - 1.200 V)
	P-State			FID 0x100 - VID 0x28 - IDD 8 (4.00x - 1.050 V)


	Package Type		0x1
	Model			40
	String 1		0xA
	String 2		0x6
	Page			0x0
	CmpCap			4
	ApicIdCoreSize		4
	TDC Limit		76 Amps
	Boosted P-States	0
	Max non-turbo ratio	15.00x
	Max turbo ratio		15.00x
	Max CPU COF		30
	Core Performance Boost	no
	P-State			0, FID 0xE - VID 0x0C (15.00x - 1.400 V)
	P-State			1, FID 0x7 - VID 0x14 (11.50x - 1.300 V)
	P-State			2, FID 0x2 - VID 0x1C (9.00x - 1.200 V)
	P-State			3, FID 0x100 - VID 0x28 (4.00x - 1.050 V)
	Attached device		PCI device at bus 0, device 24, function 0
	Attached device		PCI device at bus 0, device 24, function 1
	Attached device		PCI device at bus 0, device 24, function 2
	Attached device		PCI device at bus 0, device 24, function 3
	Attached device		PCI device at bus 0, device 24, function 4
	PERFEVT			122652032.0 MHz

	Temperature 0		36 degC (95 degF) (Core #0)
	Temperature 1		35 degC (95 degF) (Core #1)
	Temperature 2		35 degC (95 degF) (Core #3)
	Temperature 3		35 degC (95 degF) (Core #2)
	Power 00		106.40 W (Package)
	Clock Speed 0		3013.26 MHz (Core #0)
	Clock Speed 1		3013.26 MHz (Core #1)
	Clock Speed 2		3013.26 MHz (Core #3)
	Clock Speed 3		3013.26 MHz (Core #2)
	Core 0 max ratio	15.0 (effective 15.0)
	Core 1 max ratio	15.0 (effective 15.0)
	Core 2 max ratio	15.0 (effective 15.0)
	Core 3 max ratio	15.0 (effective 15.0)

**Comment by merlokk** [comment]
file permissions is ok, files from repository.

**Comment by pwpiwi** [comment]
Any compilation or link warnings? Does it print anything before exiting? Which compiler do you use?

No problems here with Windows 10.

**Comment by merlokk** [comment]
There is no computer wahrnings. And I use proxspace from Gator96100

**Comment by merlokk** [comment]
Maybe it not works on AMD Athlon II X4 640 ?

**Comment by marshmellow42** [comment]
How recently did you get Gators proxspace?  He had an issue in his environment a while back that caused an issue with hardnested.  
Might need to re install it?

**Comment by marshmellow42** [comment]
See http://www.proxmark.org/forum/viewtopic.php?id=5034

**Comment by pwpiwi** [comment]
@merlokk: do you use precompiled binaries? Or did you compile yourself?

**Comment by merlokk** [comment]
I compile myself with latest Gator's proxspace from github.  Its like my problem. Ill look.

**Comment by merlokk** [comment]
There is no rights problem, UAC disabled and so on. Compiling ok, no problem with perl(

**Comment by merlokk** [comment]
tried to put this to run bat
powershell -Command "Start-Process 'msys\msys.bat' -Verb runAs

no result.

**Comment by merlokk** [comment]
how do you start it?  
cd client
proxmark3 com1 
?

**Comment by pwpiwi** [comment]
yes (if your proxmark is on com1), Or `client/proxmark3 com1`

**Comment by iceman1001** [comment]
very rarely is a device connected to com1 on a windows-based computer.  Normally com3 or upwards

**Comment by merlokk** [comment]
mine com6. usually, i run to from client folder, i have tried to run id your way, but not succeed.

**Comment by pwpiwi** [comment]
Does it print anything before exiting?

**Comment by merlokk** [comment]
no, windows just kills the process

**Comment by pwpiwi** [comment]
Before you can type any command?

**Comment by merlokk** [comment]
before it works. no its not serial. its like the process need somewhat and dont found.

**Comment by merlokk** [comment]
on appveyor works( strange....

**Comment by iceman1001** [comment]
@merlokk   whats the status with this one?   Does hardnested work for you or not?

**Comment by merlokk** [comment]
from my pc it not works(  maybe lets close it and i will open it when i have time to check

**Comment by iceman1001** [comment]
well,  a non-working hardnested command is a showstopper for a new release.

**Comment by merlokk** [comment]
ill look in it tomorrow

**Comment by merlokk** [comment]
as i see it hangs here
https://github.com/Proxmark/proxmark3/blob/master/client/hardnested/hardnested_bf_core.c#L292

`bitsliced_even_feedback[bitsliced_blocks] = `
here `bitsliced_blocks == 0`

but it looks that memory is assigned....

**Comment by merlokk** [comment]
MAX_BITSLICES == 128

**Comment by merlokk** [comment]
OK, it works but with decrease MAX_BITSLICES for __SSE2__
```
#elif defined(__SSE2__)
#define MAX_BITSLICES 64
```

**Comment by merlokk** [comment]
```
       0 |       0 | Start using 4 threads and SSE2 SIMD core                |                 |
       0 |       0 | Brute force benchmark: 24 million (2^24,5) keys/s       | 140737488355328 |   67d
       0 |       0 | Starting Test #1 ...                                    | 140737488355328 |   67d
       2 |       0 | Using 235 precalculated bitflip state tables            | 140737488355328 |   67d

```

**Comment by merlokk** [comment]
What we should do?
check why it happens? it looks it not compiled with SSE2 or SSE2 cant work with 128 bytes vectors...

or just change this value and thats all?

**Comment by pwpiwi** [comment]
SSE2 can work with 128bit vectors. What is your CPU type?

**Comment by merlokk** [comment]
AMD Athlon II X4 640

**Comment by marshmellow42** [comment]
Sounds like a cpu bug.

**Comment by merlokk** [comment]
maybe gcc have `__SSE2__` define bunt dont generate SSE2 code in mentioned place

**Comment by pwpiwi** [comment]
Supports SSE2. What is the command used to compile the *_SSE2.o files?

**Comment by merlokk** [comment]
```
gcc -MT obj/hardnested/hardnested_bf_core_SSE2.o -MMD -MP -MF obj/hardnested/hardnested_bf_core.Td  -std=c99 -D_ISOC99_SOURCE -I. -I../include -I../common -I../common/polarssl -I../zlib -I../uart -I/opt/local/include -I../liblua -Wall -g -O3 -DHAVE_GUI -mmmx -msse2 -mno-avx -mno-avx2 -mno-avx512f -c -o obj/hardnested/hardnested_bf_core_SSE2.o hardnested/hardnested_bf_core.c
gcc -MT obj/hardnested/hardnested_bitarray_core_SSE2.o -MMD -MP -MF obj/hardnested/hardnested_bitarray_core.Td  -std=c99 -D_ISOC99_SOURCE -I. -I../include -I../common -I../common/polarssl -I../zlib -I../uart -I/opt/local/include -I../liblua -Wall -g -O3 -DHAVE_GUI -mmmx -msse2 -mno-avx -mno-avx2 -mno-avx512f -c -o obj/hardnested/hardnested_bitarray_core_SSE2.o hardnested/hardnested_bitarray_core.c
```

**Comment by merlokk** [comment]
ok, found it.
but.....
```
#define MAX_BITSLICES 64
#define VECTOR_SIZE (MAX_BITSLICES/8)
result:
      0 |       0 | Brute force benchmark: 25 million (2^24,6) keys/s       | 140737488355328 |   65d
```

and

```
#define MAX_BITSLICES 128
#define VECTOR_SIZE (MAX_BITSLICES/4)
result:
 0 |       0 | Brute force benchmark: 6 million (2^22,4) keys/s        | 140737488355328 |  290d
```


strange.....

but there is a bug....

```
#define VECTOR_SIZE (MAX_BITSLICES/8)
typedef unsigned int __attribute__((aligned(VECTOR_SIZE))) __attribute__((vector_size(VECTOR_SIZE))) bitslice_value_t;

```
length of int == 4
MAX_BITSLICES in bytes so....
correct one

```
#define MAX_BITSLICES 128
#define VECTOR_SIZE (MAX_BITSLICES/4)
```

**Comment by pwpiwi** [comment]
`MAX_BITSLICES` is in Bits. `VECTOR_SIZE` is in Bytes.

**Comment by pwpiwi** [comment]
Travis xcode8.3 and later uses SSE2. No issues.

**Comment by merlokk** [comment]
sounds like compiler not compiled SSE2 on my platform or bug in CPU

**Comment by merlokk** [comment]
It really launches SSE2 code and really goes to XOR's.

i looked into ASM. it looks good.

but it stops and show try to read from FFFFF... 
![image](https://user-images.githubusercontent.com/807634/34441308-7bbdb8ba-ecc3-11e7-89ca-fcfab0ed8d03.png)

it looks like its CPU bug(

**Comment by merlokk** [comment]
![image](https://user-images.githubusercontent.com/807634/34441773-9982d13e-ecc6-11e7-839e-b9b730cd0f57.png)

as i see there is no FFFFs. it lokks like cpu bug(

**Comment by pwpiwi** [comment]
... or a compiler bug. Did you try another version?

**Comment by merlokk** [comment]
i have tried several PC and looks like only my have this error

**Comment by merlokk** [comment]
Ill try another version of gcc but maybe after NY

**Comment by Gator96100** [comment]
I finally did update my Proxspace environment to gcc 5.3 in order to have support for AVX-512 optimizations. This might also solve your problem. [https://github.com/Gator96100/ProxSpace/tree/NewGCC](url)

**Comment by merlokk** [comment]
Thanks! Ill try

**Comment by merlokk** [comment]
it not helps (


and it have strange double prompts for me...  but it offtopic)
```
pm3 ~/client$ gcc --version
gcc.exe (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

pm3 ~/client$                                                                                                                     
pm3 ~/client$
```

**Comment by merlokk** [comment]
OK,
this works
`bitslice_value_t t = lstate_p[(47- 0)/2].value;`
this works
`bitslice_value_t t = lstate_p[(47- 0)/2].value ^ 0xFF;`
this works
`bitslice_value_t t = lstate_p[(47- 10)/2].value ^ 0xff;`
this works (maybe because of compiler optimization)
`bitslice_value_t t = lstate_p[(47- 0)/2].value ^ lstate_p[(47- 0)/2].value;`
this not(
`bitslice_value_t t = lstate_p[(47- 0)/2].value ^ lstate_p[(47- 10)/2].value;`

**Comment by merlokk** [comment]
OK. im pass(
![image](https://user-images.githubusercontent.com/807634/34485803-11f1166a-efd5-11e7-980f-10afa7900b5d.png)

there are 2 mov instructions. program hangs on 2nd.
as i see all is OK with memory alignment and access..
this code successfully executes on another CPU and travis
so it looks that this bug in very low level. maybe in compiling SSE2 with gcc. 
I cant fix it.

Maybe it needs to add key to `hardnested` command not to use any of optimization. and thats all(

**Comment by iceman1001** [comment]
the first one moves from eax register,   the second from ebp-0x07e8 memory location.
Where does those registers point to?  is the memoryallocation too small?

**Comment by merlokk** [comment]
ebp-0x07e8 - memory is ok. there are 2 memory windows at top - with address of ptr, on the bottom - with memory

eax also contains address and it ok(

**Comment by merlokk** [comment]
iceman fork:
![image](https://user-images.githubusercontent.com/807634/34517837-6b84a9a2-f085-11e7-8237-3c0aa67e1786.png)
the same (

**Comment by iceman1001** [comment]
you have a strange computer...

**Comment by merlokk** [comment]
I found another pc with this cpu and it shows this error too.
maybe it depends on cpu(

**Comment by merlokk** [comment]
ok. #538 can make `hf mf hardnested` work without hardware acceleration
I cant fix it. maybe gcc compiles wrong code for this CPU

**Comment by pwpiwi** [comment]
> ebp-0x07e8 - memory is ok.

No, it is not. The address 0x45FF6A4 is not aligned at a 16Byte boundary.

From the x86 instruction set reference:
> When the source or destination operand is a memory operand, the operand must be aligned on a 16-byte (128-bit version) or 32-byte (VEX.256 encoded version) boundary or a general-protection exception (#GP) will be generated.

So there is either a compiler bug or an alignment statement is missing in the hardnested code.

**Comment by iceman1001** [comment]
The depth of both @merlokk  and @pwpiwi  knowledge is amazing.

**Comment by merlokk** [comment]
0x45FF6A4 aligned by 4 bytes.

Here is an indirect reading:
0x45FF6A4 - address 0x03af5d20
0x03af5d20 - data alugned by 16 bytes as it needs

and i look inho instruction reference and cant realize is this correct. It looks correct, but maybe not.

**Comment by pwpiwi** [comment]
Afaik there is only register indirect addressing in x86 instructions. I.e. the contents of a register (ebp in this case) plus some offset determine the memory address. The address is not correctly aligned.

**Comment by pwpiwi** [comment]
http://www.peterstock.co.uk/games/mingw_sse is an older post about this subject. Maybe it is still valid? Which compilers did you try?

**Comment by iceman1001** [comment]
The two possible solutions in the link seems like a good test for  @merlokk

**Comment by merlokk** [comment]
OK

adding this line to makefile works
`HARD_SWITCH_SSE2 = -mmmx -msse2 -mno-avx -mno-avx2 -mstackrealign`

but i dont know how does it affect performance. looks like not so bad.
and from this line it affected only on SSE2 hardnedted code. So it should be OK.

ill commit it.)

**Comment by merlokk** [comment]
@pwpiwi , if you want lets get rid of iX options, but i like to leave them because time from time it will be good to change command set and look....
