### ISSUE TITLE
can't find the proxmark on windows

### ISSUE THREAD

**Issue by Joni1987** [Proxmark/proxmark3#408]
1. I compail all the files with `make clean && make all`
i see on hid the proxmark on com 8
when i type `./client/flasher com8 -b ./bootrom/obj/bootrom.elf ` it search and search and not find my proxmark
what can i do please?

2) after i will done `./client/flasher com8 -b ./bootrom/obj/bootrom.elf ` and then i will done` ./client/flasher comx ./armsrc/obj/fullimage.elf`
then proxmark3 ready?
can i put tag and read itwith the terminal? how please?

thank

**Comment by pwpiwi** [comment]
This is not the audience for basic questions. Please use the forum instead.
