### ISSUE TITLE
iso14443b.c & iso14443b.h   file not good

### ISSUE THREAD

**Issue by jobika1lP** [Proxmark/proxmark3#416]
1- there are  function that in iso14443b.c and not on iso14443b.h like `SnoopIso14443b `and `ReadSTMemoryIso14443b`

2- on [this line](https://github.com/Proxmark/proxmark3/blob/master/armsrc/iso14443b.h#L10) this suppost to be  14443 type B

**Comment by pwpiwi** [comment]
Feel free to fix it.

**Comment by jobika1lP** [comment]
@pwpiwi I no so familiar with the code
i prefer someone else do it
