### ISSUE TITLE
MacOS Compilation Fix

### ISSUE THREAD

**Issue by ytisf** [Proxmark/proxmark3#428]
MacOS fails compilation due to deprecated function call in 'client/pm3_binlib.c' at line 110.
Change from `int i_read = luaL_optint(L,3,1)-1;` to `int i_read = luaL_optinteger(L,3,1)-1;` fixes the issue.

**Comment by iceman1001** [comment]
strange,  since luaL_optint is a #define inside lauxlib.h ,  which defines luaL_optinteger...

Does your pm3_binlib.c has a refence to <lauxlib.h> ?   Which it should,  are you linking in another lua-lib version?

**Comment by ytisf** [comment]
Yes.
It has. I used the instructions from the Wiki directly.
I guess liblua.5.3.3 changed the reference.

**Comment by pwpiwi** [comment]
Proxmark source includes 5.2.2.

**Comment by ytisf** [comment]
i guess it just didn't load them and overrode it with current liblua.

**Comment by pwpiwi** [comment]
This could happen if CFLAGS is defined in your environment with an -I option to the Lua 5.3.3 includes. I suggest you make a pull request with your fix.
