### ISSUE TITLE
Proxmark 3 simulation/emulation not working

### ISSUE THREAD

**Issue by gubagu** [Proxmark/proxmark3#429]
Hi guys,
I've said already but thanks for sharing your work with the mere mortals - great project. 
The emulation/simulation is not working. The client says its emulating but the other reader does not pick up anything. 
Reading cards works good.

Where should I look at or how can I debug it ?
Thanks in advance !!!
Forgot to mention just flashed the device with the newest build.
Cheerz,
Guby

**Comment by pwpiwi** [comment]
Emulating/Simulating which type of card? Which command do you try to use?

**Comment by gubagu** [comment]
Mifare classic.

**Comment by pwpiwi** [comment]
See Issue #412 and Pull Request #419
