### ISSUE TITLE
Win compilation warning

### ISSUE THREAD

**Issue by merlokk** [Proxmark/proxmark3#431]
There are 3 warnings (for windows):
g++ -MT obj/proxgui.o -MMD -MP -MF obj/proxgui.Td -I../include -Wall -O3 -std=c++11 -fPIC -I/qt/include -I/qt/include/QtCore -I/qt/include/QtGui -I/qt/include/QtWidgets -c -o obj/proxgui.o proxgui.cpp
proxgui.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 //-----------------------------------------------------------------------------
 ^

is this -fPIC needs for targets other than windows?

**Comment by merlokk** [comment]
https://stackoverflow.com/questions/5311515/gcc-fpic-option

**Comment by pwpiwi** [comment]
Yes, see issue #270.

**Comment by merlokk** [comment]
OK, then windows fixed in #432

**Comment by pwpiwi** [comment]
Issue is not related to Operating System. If Qt is compiled with PIC, we need -fPIC.

**Comment by merlokk** [comment]
so Gator's proxspace compiled without fPIC. And I need to check how Qt was compiled?

**Comment by merlokk** [comment]
https://stackoverflow.com/questions/966960/what-does-fpic-mean-when-building-a-shared-library

**Comment by merlokk** [comment]
I cant see how to check Qt fPIC option. Instead of that we can check OS or  maybe Gator's proxspace.
Do you know another way?

**Comment by pwpiwi** [comment]
The only way I see is to live with the warning.

**Comment by merlokk** [comment]
OK
