### ISSUE TITLE
proxmark3 flashing and running problem

### ISSUE THREAD

**Issue by cyberlion112** [Proxmark/proxmark3#433]
hey i have i proxmark3 (easy) and i am trying to set it up on kali linux on a raspberry pi3 i followed the wiki and i got through to till the upgrading part i ran the command (./flasher /dev/ttyACM0 ../armsrc/obj/fullimage.elf) and i got  bash: ./flasher: no such file or directory
and i tried to run (./proxmark3 /dev/ttyACM0) and i got bash: ./proxmark3: no such file or directory
can someone please help me with this problem as i am new to this.

**Comment by pwpiwi** [comment]
This is the github code repository. Your question is better suited for the forum http://www.proxmark.org/forum

**Comment by cyberlion112** [comment]
Thank you
