### ISSUE TITLE
hf search hangs since Comms refactor

### ISSUE THREAD

**Issue by Fl0-0** [Proxmark/proxmark3#449]
Since commit afdcb8c159a73aba95a017f1cfec98e8fa2b93c1 hf search detection hangs if no cards is present or with a ISO15693 card.

**Comment by pwpiwi** [comment]
Reverted.

**Comment by pwpiwi** [comment]
Issue solved after reverting #371?

**Comment by Fl0-0** [comment]
Yes issue solved.
