### ISSUE TITLE
pm3 lf interference?

### ISSUE THREAD

**Issue by marshmellow42** [Proxmark/proxmark3#469]
for some time i've noticed some sort of residual interference on the lf side.  maybe my device is dying but i don't think so (checked on 2 pm3's)  ..  or maybe it is picking up my heart beat...

when reading with no card on the antenna there is a pattern that is clear: 
![image](https://user-images.githubusercontent.com/9687156/32677280-cfdb70fe-c62b-11e7-9e43-afcaef5fc72f.png)

with weaker antennas it is not as clear (but still present), and with this 40+v antenna it is pretty strong.
(making the checks for "Just Noise" fail)

to reproduce i just run `lf read` - `data plot` with no tag on the antenna.

when i get time i will attempt to go back in time and identify where it first appears, because i know i didn't have this problem a few years ago...

**Comment by iceman1001** [comment]
I don't have that,   but then I'm also experimenting with a better noise-detection since the current one is a bit limited.

**Comment by marshmellow42** [comment]
what does a lf plot look like for you with no tag near the antenna?

**Comment by marshmellow42** [comment]
with a weaker antenna i see:
![image](https://user-images.githubusercontent.com/9687156/32678065-db1d59f2-c62e-11e7-980e-9c58a0009194.png)

**Comment by marshmellow42** [comment]
strong antenna's tune:
![image](https://user-images.githubusercontent.com/9687156/32678724-8634182e-c631-11e7-8340-6fa80062a0e8.png)

weaker antenna's tune:
![image](https://user-images.githubusercontent.com/9687156/32678754-ad0637a2-c631-11e7-87a4-1ea8a55c2658.png)

**Comment by pwpiwi** [comment]
My noise looks more random:
![unbenannt](https://user-images.githubusercontent.com/7026004/32679786-042126b0-c668-11e7-8b2c-b8e590c15b97.JPG)

antenna tune:
```
proxmark3> hw tune

Measuring antenna characteristics, please wait.........
# LF antenna: 41.11 V @   125.00 kHz
# LF antenna: 42.62 V @   134.00 kHz
# LF optimal: 45.10 V @   127.66 kHz
# HF antenna:  0.28 V @    13.56 MHz
# Your HF antenna is unusable.
Displaying LF tuning graph. Divisor 89 is 134khz, 95 is 125khz.



proxmark3>
```

Are you picking up some external signal? What if you are moving (far away)?

**Comment by iceman1001** [comment]
Mine goes between -2 and -10  with an amplitude of 8.  

![lf_read](https://user-images.githubusercontent.com/8577004/32680880-15740c20-c66d-11e7-810c-71008d608a13.PNG)


```
Measuring antenna characteristics, please wait......          
# LF antenna: 18,43 V @   125.00 kHz          
# LF antenna: 16,23 V @   134.00 kHz          
# LF optimal: 18,84 V @   126,32 kHz          
# HF antenna: 13,58 V @    13.56 MHz          
Displaying LF tuning graph. Divisor 89 is 134khz, 95 is 125khz.

```

**Comment by iceman1001** [comment]
it could be bad antenna cable,  bad capacitors, bad connectors,
since its you, I guess you already test it

**Comment by marshmellow42** [comment]
I went to different rooms, changed cables, pm3s.  Only common element is ms surface pro...    I'll try a different computer soon

**Comment by merlokk** [comment]
Have you checked the power of proxmark and maybe power near antenna amplifier?

**Comment by marshmellow42** [comment]
well it appears the interference is location dependent as in a different building i get:
![image](https://user-images.githubusercontent.com/9687156/32695100-e73a60e8-c720-11e7-9908-cc4060cc5c23.png)

so evidently the hvac or other large electronic device in the other building produces a patterned signal interference and a field large enough to be consistent throughout the building... 

sorry for wasting your time...
