### ISSUE TITLE
error to flash, how to restore??????!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by gearcapitan** [Proxmark/proxmark3#487]
fail to flash, unknown device, (device descriptor request error)

![captura de pantalla 130](https://user-images.githubusercontent.com/13740942/32976177-0eacdfe2-cbd7-11e7-9401-c1c505d0620a.png)
![captura de pantalla 131](https://user-images.githubusercontent.com/13740942/32976178-0ec050fe-cbd7-11e7-94a5-7dcc4bb0eb4e.png)
![captura de pantalla 132](https://user-images.githubusercontent.com/13740942/32976179-0ed45040-cbd7-11e7-8636-844ba8975576.png)
![captura de pantalla 133](https://user-images.githubusercontent.com/13740942/32976180-0ee851f8-cbd7-11e7-8055-eb7fcf660507.png)
![captura de pantalla 134](https://user-images.githubusercontent.com/13740942/32976181-0eff0812-cbd7-11e7-8ad4-85e6502875e4.png)
![captura de pantalla 135](https://user-images.githubusercontent.com/13740942/32976182-0f13dc4c-cbd7-11e7-928f-6d04edbf39db.png)

![captura de pantalla 136](https://user-images.githubusercontent.com/13740942/32976211-5b8ecbc2-cbd7-11e7-920a-2c02e11d82ba.png)
![photo4936245251354503119](https://user-images.githubusercontent.com/13740942/32976601-b589159e-cbdf-11e7-82e0-2738cf8f1b1b.jpg)

![Uploading photo4936245251354503119.jpg…]()

HELP!

**Comment by pwpiwi** [comment]
This is not a software issue. Please post your question in the forum.
