### ISSUE TITLE
How in android with nfc do Nr const ?

### ISSUE THREAD

**Issue by maxben14** [Proxmark/proxmark3#492]
How in android with nfc do Nr const ?
Can this do in android firmware ?

**Comment by pwpiwi** [comment]
This is the proxmark github repository.

**Comment by maxben14** [comment]
@pwpiwi , i understand, but me interest, i do emulator 1k and my emulator send At in reader about 700 microsec, in datasheet max 1 ms, proxmark read my device good, but android function Authentificate return false. Do you know about timing in android ?

**Comment by pwpiwi** [comment]
No. And afaik the other maintainers in this group develop proxmark software on and for Linux and Windows. Some Mac users are around as well. This is definitely the wrong group to ask for Android development.

**Comment by maxben14** [comment]
@pwpiwi , why does no one make the firmware of the proxmark for android? It is very uncomfortable to approach the turnstile with the proxmark along with the laptop, android is more convenient.

**Comment by pwpiwi** [comment]
There are forks with changes for android. We had provided the links already.

**Comment by iceman1001** [comment]
This Github repository is for the Proxmark device.  Not for Android apps,  nor iphone apps,  or other devices like chameleon mini,  emutag,   or other libs like libnfc or libfreefare.  
closed.
