### ISSUE TITLE
Improved ISO14443a card selection is buggy

### ISSUE THREAD

**Issue by aczid** [Proxmark/proxmark3#518]
Every commit after c95affa8d3d84f0bd5db7821f65c22e13870d4e2 results in unreliable ISO14443A card selection, especially when the card is woken up many times in quick succession, such as when running the hard nested attack.
The problems with the behavior were described in more detail in the comments here https://github.com/Proxmark/proxmark3/pull/491
The output of a few test commands + log can be found here:
https://p.6core.net/p/45yVhHqy8bpMMkq9ps9NukAc

**Comment by pwpiwi** [comment]
This seems to be a special card? I have not seen yet so many WUPA retries as in your trace.

Nevertheless the command should succeed in the end?

**Comment by pwpiwi** [comment]
Worst case is nearly 28ms before the card responds to WUPA. Please change `WUPA_RETRY_TIMEOUT` to 30 in iso14443a.c and try again.

**Comment by pwpiwi** [comment]
@aczid : Did you succeed?

**Comment by aczid** [comment]
I'm sorry, I was away from keyboard so couldn't test much. A quick test did not succeed.

**Comment by iceman1001** [comment]
hm,  this is a showstopper for a new release.

**Comment by pwpiwi** [comment]
@aczid: can you please provide new traces with `WUPA_RETRY_TIMEOUT` changed to 30 or 40?

**Comment by aczid** [comment]
Yes, sorry for taking an extended Christmas break guys.
Here it is with WUPA_RETRY_TIMEOUT set to 40:
https://p.6core.net/p/ntdczGptK74uXZ0c87yBolWz

In other words, it does not improve.

**Comment by pwpiwi** [comment]
Except for the card sometimes taking ages (maximum in this trace is 62ms!) to respond to WUPA, the trace looks OK. 

I can see that the PM3 successfully authenticates with key A = 000000000000 against block 0 and then tries a nested authentication against block 4, which doesn't succeed.  That is exactly what the PM3 does to collect nonces from the tag in an hardnested attack.

Can you please show us the output of the respective command as well? Be patient and let it run...

And it might be interesting to see the respective trace with a firmware version before commit  c95affa.

**Comment by aczid** [comment]
For reference here is the trace as before the changes, from `git checkout db68bcdb06618c97a45a39ff5ed6acf666da62e2 armsrc/iso14443a.c armsrc/mifarecmd.c`
https://p.6core.net/p/SDdP6zfrenpqtK3XBg9CyA7h

**Comment by pwpiwi** [comment]
This helps. Can you please test PR #547?

**Comment by aczid** [comment]
Yes! This fixes the problem completely!
