### ISSUE TITLE
EMV work. 

### ISSUE THREAD

**Issue by merlokk** [Proxmark/proxmark3#520]
I put here some plaining work in EMV area.
This work will be very interesting for people who work with bank cards and terminals. Now there are many commercial card emulators and sample terminals but they costs from $10000USD and plus yearly subscription...
This work will help expand the number of proxmark users and may attract new contributors.

EMV1-5,8 - merged)
EMV6 - EMV emulator - started here #513 
EMV7 -  working card emulator.

**Comment by iceman1001** [comment]
Wow!  @merlokk , I love your plan,  

EMV4 - with some luck if @pwpiwi finds time,   it would be nice still. 
--------
EMV5 - based on argtable,  hm, that might take some time.
EMV6 - 7  can be made individually.

With the amount of new EMV functions, I doubt there are many who tried them out more than yourself.
Its a bit of learning to do.  Just running commands and look at the output is not enough.
Reading up on it and understand whats happening will take time.

**Comment by merlokk** [comment]
As for JSON. I like to try https://github.com/akheron/jansson
What do you think? license MIT

**Comment by iceman1001** [comment]
don't know if the MIT license goes with GPL 2.0...

**Comment by pwpiwi** [comment]
Yes, it does. And BTW: GPL3 doesn't!

**Comment by iceman1001** [comment]
MIT goes with GPL2.0,  but not GPL3.0??  strange,  all these licenses..  Maybe ask Akheron for a license that fits for proxmark3 project?  I doubt that they dislike it.

**Comment by pwpiwi** [comment]
I meant: GPLv3 doesn't go with GPLv2.

**Comment by iceman1001** [comment]
Not sure about that,  
_if a user wants to combine code licensed under different versions of GPL, then this is only allowed if the code with the earlier GPL version includes an "or any later version" statement_

problem is all proxmark3 files has a somewhat incoherent GPL2 statements,  there not just one license file.   And then, the licens upholder (Westhues)  or (akheron) would need to talk with eachother complaining that the proxmark3 project is violating the license.    Long time I saw Westhues here.
It would come down to akheron,  to complain to Westhues to change the problems which might occured.

I strongly doubt someone is interested that.   And as a suggestion earlier,  if the worry of the open source license,  someone could ask the license holder of  **jansson** json lib and ask for a version of their license which would work with GPL2.0,  just like Adam Laure granted us.     

These discussions tends to be theoretical threats more than realistic ones.    So if you feel the GPL 3.0 parts of the current repo doesn't go with GPL2.0,  do please bring it up with Jonathan Westhues.

**Comment by pwpiwi** [comment]
Off topic. Opened new issue #527.

**Comment by iceman1001** [comment]
@merlokk   suggestion;  https://github.com/peterfillmore/emvkeytool  ,  dumping  found keys into a *.pem file?   And test key for ROCA  weakness,   https://github.com/crocs-muni/roca

**Comment by merlokk** [comment]
ill add dumping keys to EMV8. as for test ROCA - i see that all the code written on python( so maybe it have no sense to rewrite on C and include it to proxmark. it just needs to have this python file to check key.

**Comment by merlokk** [comment]
online test key for ROCA weakness https://keychest.net/roca#/
and its OK to put there key from json file in plain HEX format

**Comment by pwpiwi** [comment]
What about your plans? All done? Can we close this "todo list"?

**Comment by merlokk** [comment]
lets close. ill make emulator later( now i have no time(
