### ISSUE TITLE
my proxmark button does not change modes

### ISSUE THREAD

**Issue by scornofx** [Proxmark/proxmark3#539]
i am new to proxmark world........... with that being said when i connect my proxmark to a usb battery only the std and chr(flashing) turn on the push button does not change anything even when holding it for a few seconds the a,b,c,d lights only turn on when i plug it in (flash) after that they never turn on no matter what i press. i been trying to figure out how to enter standalone with no luck. this is how it came stock, i have flashed the boot to a newer version and also the flashed the full image but still my push button does not change modes. everything works when i do command line (hw tune) but push button does not change to stand alone mode. anyone have any idea what im doing wrong or something i overlooked? thanks in advance
![untitled](https://user-images.githubusercontent.com/35189139/34656479-6d9e4e38-f3e0-11e7-98ba-aa57487ee52f.jpg)

**Comment by pwpiwi** [comment]
Please ask this kind of questions in the forum. This is the software repository.
