### ISSUE TITLE
Magic Ultralight EV1

### ISSUE THREAD

**Issue by maxben14** [Proxmark/proxmark3#552]
Hi, friend.
Do you have mifare ultralight EV1 card with change uid ? I want card which can increase counter INCR_CNT and reset counter.
Do you have this card magic ?

**Comment by iceman1001** [comment]
Not quite an issue for Proxmark3 repo.  
To answer you question,  no,  I don't have such card.

I'm also closing this issue since it is not relevant to the firmware.  Such questions are better to ask on forum.
