### ISSUE TITLE
hf 14a snoop don't work.

### ISSUE THREAD

**Issue by maxben14** [Proxmark/proxmark3#567]
I try sniff between my device and android.
Why proxmark can't show date from Reader. I see in trace only answers from Tag.

proxmark3> hf 14a snoop
#db# cancelled by button
#db# COMMAND FINISHED
#db# maxDataLen=3, Uart.state=0, Uart.len=0
#db# traceLen=3592, Uart.output[0]=00000022
proxmark3> hf list 14a
Recorded Activity (TraceLen = 3592 bytes)

Start = Start of Start Bit, End = End of last modulation. Src = Source of Transfer
iso14443a - All times are in carrier periods (1/13.56Mhz)
iClass    - Timings are not as accurate

      Start |        End | Src | Data (! denotes parity error)                                   | CRC | Annotation         |
------------|------------|-----|-----------------------------------------------------------------|-----|--------------------|
          0 |       2368 | Tag | 04  00                                                          |     |
      14064 |      19952 | Tag | 01  02  03  04  04                                              |     |
      35696 |      39216 | Tag | 08  b6  dd                                                      |     |
     337536 |     339904 | Tag | 04  00                                                          |     |
     360672 |     364192 | Tag | 08  b6  dd                                                      |     |
     496448 |     498816 | Tag | 04  00                                                          |     |
     519584 |     523104 | Tag | 08  b6  dd                                                      |     |
     624960 |     627328 | Tag | 04  00                                                          |     |
     648112 |     651632 | Tag | 08  b6  dd                                                      |     |
     712688 |     717360 | Tag | 00  00  00  00                                                  |     |
     737840 |     742512 | Tag | f0  e7  2c  22                                                  |     |
     839536 |     841904 | Tag | 04  00                                                          |     |
     862688 |     866208 | Tag | 08  b6  dd                                                      |     |
     964320 |     966688 | Tag | 04  00                                                          |     |
     987488 |     991008 | Tag | 08  b6  dd                                                      |     |
    1090432 |    1092800 | Tag | 04  00                                                          |     |
    1113584 |    1117104 | Tag | 08  b6  dd                                                      |     |
    1221408 |    1223776 | Tag | 04  00                                                          |     |
    1244560 |    1248080 | Tag | 08  b6  dd                                                      |     |
    1346208 |    1348576 | Tag | 04  00                                                          |     |
    1369344 |    1372864 | Tag | 08  b6  dd                                                      |     |
    1481056 |    1483424 | Tag | 04  00                                                          |     |
    1504192 |    1507712 | Tag | 08  b6  dd                                                      |     |
    1603408 |    1608080 | Tag | 00  00  00  00                                                  |     |
    1628624 |    1633360 | Tag | 4d  47  ee  bc                                                  |     |
    1726592 |    1728960 | Tag | 04  00                                                          |     |
    1749728 |    1753248 | Tag | 08  b6  dd                                                      |     |
    1898512 |    1900880 | Tag | 04  00                                                          |     |
    1921648 |    1925168 | Tag | 08  b6  dd                                                      |     |
    2069808 |    2072176 | Tag | 04  00                                                          |     |
    2092960 |    2096480 | Tag | 08  b6  dd                                                      |     |
    2455072 |    2457440 | Tag | 04  00                                                          |     |
    2478224 |    2481744 | Tag | 08  b6  dd                                                      |     |
    4325504 |    4327872 | Tag | 04  00                                                          |     |
    4348688 |    4352208 | Tag | 08  b6  dd                                                      |     |
    6101980 |    6106748 | Rdr | 50  00  57  cd                                                  |  ok | HALT
    6151200 |    6153568 | Tag | 04  00                                                          |     |
    6174352 |    6177872 | Tag | 08  b6  dd                                                      |     |
    7981980 |    7982972 | Rdr | 52                                                              |     | WUPA
    7984224 |    7986592 | Tag | 04  00                                                          |     |
    8007392 |    8010912 | Tag | 08  b6  dd                                                      |     |
    9814560 |    9816928 | Tag | 04  00                                                          |     |
    9837728 |    9841248 | Tag | 08  b6  dd                                                      |     |
   11686912 |   11689280 | Tag | 04  00                                                          |     |
   11710080 |   11713600 | Tag | 08  b6  dd                                                      |     |
   13622928 |   13625296 | Tag | 04  00                                                          |     |
   13646096 |   13649616 | Tag | 08  b6  dd                                                      |     |
   15473472 |   15475840 | Tag | 04  00                                                          |     |
   15496640 |   15500160 | Tag | 08  b6  dd                                                      |     |
   17320028 |   17321020 | Rdr | 52                                                              |     | WUPA
   17322272 |   17324640 | Tag | 04  00                                                          |     |
   17345456 |   17348976 | Tag | 08  b6  dd                                                      |     |
   19223776 |   19226144 | Tag | 04  00                                                          |     |
   19246960 |   19250480 | Tag | 08  b6  dd                                                      |     |
   21149248 |   21151616 | Tag | 04  00                                                          |     |
   21160700 |   21171228 | Rdr | 93  70  01  02  03  04  04  8e  25                              |  ok | SELECT_UID     
   21172432 |   21175952 | Tag | 08  b6  dd                                                      |     |
   23016972 |   23017964 | Rdr | 52                                                              |     | WUPA
   23019216 |   23021584 | Tag | 04  00                                                          |     |
   23042400 |   23045920 | Tag | 08  b6  dd                                                      |     |
   24904336 |   24906704 | Tag | 04  00                                                          |     |
   24927520 |   24931040 | Tag | 08  b6  dd                                                      |     |
   26816368 |   26818736 | Tag | 04  00                                                          |     |
   26839536 |   26843056 | Tag | 08  b6  dd                                                      |     |
   28713328 |   28715696 | Tag | 04  00                                                          |     |
   28736512 |   28740032 | Tag | 08  b6  dd                                                      |     |
   30629248 |   30631616 | Tag | 04  00                                                          |     |
   30652464 |   30655984 | Tag | 08  b6  dd                                                      |     |
   32508992 |   32511360 | Tag | 04  00                                                          |     |
   32532192 |   32535712 | Tag | 08  b6  dd                                                      |     |
   34373772 |   34378540 | Rdr | 50  00  57  cd                                                  |  ok | HALT
   34423760 |   34426128 | Tag | 04  00                                                          |     |
   34446928 |   34450448 | Tag | 08  b6  dd                                                      |     |
   36267264 |   36269632 | Tag | 04  00                                                          |     |
   36278716 |   36289244 | Rdr | 93  70  01  02  03  04  04  8e  25                              |  ok | SELECT_UID     
   36290448 |   36293968 | Tag | 08  b6  dd                                                      |     |
   38074604 |   38079372 | Rdr | 50  00  57  cd                                                  |  ok | HALT
   38121628 |   38122620 | Rdr | 52                                                              |     | WUPA
   38123856 |   38126224 | Tag | 04  00                                                          |     |
   38147056 |   38150576 | Tag | 08  b6  dd                                                      |     |
   40057680 |   40060048 | Tag | 04  00                                                          |     |
   40080864 |   40084384 | Tag | 08  b6  dd                                                      |     |
   41893056 |   41895424 | Tag | 04  00                                                          |     |
   41916224 |   41919744 | Tag | 08  b6  dd                                                      |     |
   43756720 |   43759088 | Tag | 04  00                                                          |     |
   43779888 |   43783408 | Tag | 08  b6  dd                                                      |     |
   45597328 |   45599696 | Tag | 04  00                                                          |     |
   45608780 |   45619308 | Rdr | 93  70  01  02  03  04  04  8e  25                              |  ok | SELECT_UID     
   45620496 |   45624016 | Tag | 08  b6  dd                                                      |     |
   47431728 |   47434096 | Tag | 04  00                                                          |     |
   47454912 |   47458432 | Tag | 08  b6  dd                                                      |     |
   49283008 |   49285376 | Tag | 04  00                                                          |     |
   49294460 |   49304988 | Rdr | 93  70  01  02  03  04  04  8e  25                              |  ok | SELECT_UID     
   49306176 |   49309696 | Tag | 08  b6  dd                                                      |     |
   51131680 |   51134048 | Tag | 04  00                                                          |     |
   51154880 |   51158400 | Tag | 08  b6  dd                                                      |     |
   52954272 |   52956640 | Tag | 04  00                                                          |     |
   52977456 |   52980976 | Tag | 08  b6  dd                                                      |     |
   54810752 |   54813120 | Tag | 04  00                                                          |     |
   54822204 |   54832732 | Rdr | 93  70  01  02  03  04  04  8e  25                              |  ok | SELECT_UID     
   54833920 |   54837440 | Tag | 08  b6  dd                                                      |     |
   56649072 |   56651440 | Tag | 04  00                                                          |     |
   56672256 |   56675776 | Tag | 08  b6  dd                                                      |     |
   58512544 |   58514912 | Tag | 04  00                                                          |     |
   58524012 |   58534540 | Rdr | 93  70  01  02  03  04  04  8e  25                              |  ok | SELECT_UID     
   58535728 |   58539248 | Tag | 08  b6  dd                                                      |     |
   60366672 |   60369040 | Tag | 04  00                                                          |     |
   60389856 |   60393376 | Tag | 08  b6  dd                                                      |     |
   60568672 |   60573344 | Tag | 00  00  00  00                                                  |     |
   60593888 |   60598624 | Tag | 6f  08  46  40                                                  |     |
   62879772 |   62884540 | Rdr | 50  00  57  cd                                                  |  ok | HALT
   62929744 |   62932112 | Tag | 04  00                                                          |     |
   62952944 |   62956464 | Tag | 08  b6  dd                                                      |     |
   64755792 |   64758160 | Tag | 04  00                                                          |     |
   64778976 |   64782496 | Tag | 08  b6  dd                                                      |     |
   66583088 |   66585456 | Tag | 04  00                                                          |     |
   66606272 |   66609792 | Tag | 08  b6  dd                                                      |     |
   68512220 |   68513212 | Rdr | 52                                                              |     | WUPA
   68514464 |   68516832 | Tag | 04  00                                                          |     |
   68537648 |   68541168 | Tag | 08  b6  dd                                                      |     |
   70341356 |   70346124 | Rdr | 50  00  57  cd                                                  |  ok | HALT
   70390656 |   70393024 | Tag | 04  00                                                          |     |
   70402108 |   70412636 | Rdr | 93  70  01  02  03  04  04  8e  25                              |  ok | SELECT_UID     
   70413824 |   70417344 | Tag | 08  b6  dd                                                      |     |
   72271500 |   72272492 | Rdr | 52                                                              |     | WUPA
   72273744 |   72276112 | Tag | 04  00                                                          |     |
   72296928 |   72300448 | Tag | 08  b6  dd                                                      |     |
   74139008 |   74141376 | Tag | 04  00                                                          |     |
   74162208 |   74165728 | Tag | 08  b6  dd                                                      |     |
   76063040 |   76065408 | Tag | 04  00                                                          |     |
   76086224 |   76089744 | Tag | 08  b6  dd                                                      |     |
   77957120 |   77959488 | Tag | 04  00                                                          |     |
   77980320 |   77983840 | Tag | 08  b6  dd                                                      |     |
   79788544 |   79790912 | Tag | 04  00                                                          |     |
   79811728 |   79815248 | Tag | 08  b6  dd                                                      |     |
   80561100 |   80565804 | Rdr | 60  00  f5  7b                                                  |  ok | AUTH-A(0)      
   80567056 |   80571728 | Tag | 00  00  00  00                                                  |     |
   80575852 |   80585164 | Rdr | 0e  33 36! 91! 9e! 58! c0! c7!                                  | !crc| ?
   80592208 |   80596944 | Tag | 34  08  0a  b6                                                  |     |
   80833212 |   80837980 | Rdr | 30  00  02  a8                                                  |  ok | READBLOCK(0)   
   82745420 |   82750188 | Rdr | 50  00  57  cd                                                  |  ok | HALT
   82795424 |   82797792 | Tag | 04  00                                                          |     |
   82818608 |   82822128 | Tag | 08  b6  dd                                                      |     |
   84621984 |   84624352 | Tag | 04  00                                                          |     |
   84645184 |   84648704 | Tag | 08  b6  dd                                                      |     |
   86483696 |   86486064 | Tag | 04  00                                                          |     |
   86506880 |   86510400 | Tag | 08  b6  dd                                                      |     |
   88384384 |   88386752 | Tag | 04  00                                                          |     |
   88407600 |   88411120 | Tag | 08  b6  dd                                                      |     |
   90046880 |   90051552 | Tag | 00  00  00  00                                                  |     |
   90072048 |   90076720 | Tag | b4  86  0d  aa                                                  |     |
   92176876 |   92181644 | Rdr | 50  00  57  cd                                                  |  ok | HALT
   92226160 |   92228528 | Tag | 04  00                                                          |     |
   92237644 |   92248172 | Rdr | 93  70  01  02  03  04  04  8e  25                              |  ok | SELECT_UID     
   92249360 |   92252880 | Tag | 08  b6  dd                                                      |     |
   94081824 |   94084192 | Tag | 04  00                                                          |     |
   94105024 |   94108544 | Tag | 08  b6  dd                                                      |     |
   96012576 |   96014944 | Tag | 04  00                                                          |     |
   96035760 |   96039280 | Tag | 08  b6  dd                                                      |     |
   97843276 |   97848044 | Rdr | 50  00  57  cd                                                  |  ok | HALT
   97893280 |   97895648 | Tag | 04  00                                                          |     |
   97916464 |   97919984 | Tag | 08  b6  dd                                                      |     |
   99759648 |   99762016 | Tag | 04  00                                                          |     |
   99782832 |   99786352 | Tag | 08  b6  dd                                                      |     |
  101635760 |  101638128 | Tag | 04  00                                                          |     |
  101658960 |  101662480 | Tag | 08  b6  dd                                                      |     |
  103396444 |  103401148 | Rdr | 60  00  f5  7b                                                  |  ok | AUTH-A(0)      
  103402400 |  103407072 | Tag | 00  00  00  00                                                  |     |
  103427632 |  103432304 | Tag | 29  82  9a  aa                                                  |     |
  105998912 |  106001280 | Tag | 04  00                                                          |     |
  106022096 |  106025616 | Tag | 08  b6  dd                                                      |     |
  107830368 |  107832736 | Tag | 04  00                                                          |     |
  107853552 |  107857072 | Tag | 08  b6  dd                                                      |     |
  109668656 |  109671024 | Tag | 04  00                                                          |     |
  109691856 |  109695376 | Tag | 08  b6  dd                                                      |     |
  111560016 |  111562384 | Tag | 04  00                                                          |     |
  111583216 |  111586736 | Tag | 08  b6  dd                                                      |     |
  113435264 |  113437632 | Tag | 04  00                                                          |     |
  113458464 |  113461984 | Tag | 08  b6  dd                                                      |     |
  115240252 |  115245020 | Rdr | 50  00  57  cd                                                  |  ok | HALT
  115290976 |  115293344 | Tag | 04  00                                                          |     |
  115302444 |  115312972 | Rdr | 93  70  01  02  03  04  04  8e  25                              |  ok | SELECT_UID     
  115314160 |  115317680 | Tag | 08  b6  dd                                                      |     |
  117115436 |  117120204 | Rdr | 50  00  57  cd                                                  |  ok | HALT
  117164752 |  117167120 | Tag | 04  00                                                          |     |
  117187952 |  117191472 | Tag | 08  b6  dd                                                      |     |
  118425536 |  118430208 | Tag | 00  00  00  00                                                  |     |
  118450768 |  118455440 | Tag | a9  5f  19  55                                                  |     |
  120831372 |  120832364 | Rdr | 52                                                              |     | WUPA
  120833616 |  120835984 | Tag | 04  00                                                          |     |
  120856816 |  120860336 | Tag | 08  b6  dd                                                      |     |
  122676624 |  122678992 | Tag | 04  00                                                          |     |
  122699808 |  122703328 | Tag | 08  b6  dd                                                      |     |
  124530732 |  124535500 | Rdr | 50  00  57  cd                                                  |  ok | HALT
  124581440 |  124583808 | Tag | 04  00                                                          |     |
  124604640 |  124608160 | Tag | 08  b6  dd                                                      |     |
  126504448 |  126506816 | Tag | 04  00                                                          |     |
  126527648 |  126531168 | Tag | 08  b6  dd                                                      |     |
  128332192 |  128334560 | Tag | 04  00                                                          |     |
  128355392 |  128358912 | Tag | 08  b6  dd                                                      |     |
  130193648 |  130196016 | Tag | 04  00                                                          |     |
  130216848 |  130220368 | Tag | 08  b6  dd                                                      |     |
  130908908 |  130913612 | Rdr | 60  00  f5  7b                                                  |  ok | AUTH-A(0)      
  130914848 |  130919520 | Tag | 00  00  00  00                                                  |     |
  130923660 |  130933036 | Rdr | 20  57 38!  db 7f!  1c ad!  46                                  | !crc| ?
  130940080 |  130944752 | Tag | 15  c1  1b  99                                                  |     |
  133364716 |  133365708 | Rdr | 52                                                              |     | WUPA
  133366960 |  133369328 | Tag | 04  00                                                          |     |
  133390160 |  133393680 | Tag | 08  b6  dd                                                      |     |
  135192956 |  135193948 | Rdr | 52                                                              |     | WUPA
  135195200 |  135197568 | Tag | 04  00                                                          |     |
  135218400 |  135221920 | Tag | 08  b6  dd                                                      |     |
  137081152 |  137083520 | Tag | 04  00                                                          |     |
  137104336 |  137107856 | Tag | 08  b6  dd                                                      |     |
  138975328 |  138977696 | Tag | 04  00                                                          |     |
  138998528 |  139002048 | Tag | 08  b6  dd                                                      |     |
  140841360 |  140843728 | Tag | 04  00                                                          |     |
  140864544 |  140868064 | Tag | 08  b6  dd                                                      |     |
  142700336 |  142702704 | Tag | 04  00                                                          |     |
  142723536 |  142727056 | Tag | 08  b6  dd                                                      |     |
  144619568 |  144621936 | Tag | 04  00                                                          |     |
  144631036 |  144641564 | Rdr | 93  70  01  02  03  04  04  8e  25                              |  ok | SELECT_UID     
  144642752 |  144646272 | Tag | 08  b6  dd                                                      |     |
  146461776 |  146464144 | Tag | 04  00                                                          |     |
  146484960 |  146488480 | Tag | 08  b6  dd                                                      |     |
  146757632 |  146762304 | Tag | 00  00  00  00                                                  |     |
  146782784 |  146787520 | Tag | 4a  b1  1c  f2                                                  |     |
  149188992 |  149191360 | Tag | 04  00                                                          |     |
  149200460 |  149210988 | Rdr | 93  70  01  02  03  04  04  8e  25                              |  ok | SELECT_UID     
  149212176 |  149215696 | Tag | 08  b6  dd                                                      |     |
  151039248 |  151041616 | Tag | 04  00                                                          |     |
  151062448 |  151065968 | Tag | 08  b6  dd                                                      |     |
  152937168 |  152939536 | Tag | 04  00                                                          |     |
  152960368 |  152963888 | Tag | 08  b6  dd                                                      |     |
  154870672 |  154873040 | Tag | 04  00                                                          |     |
  154893856 |  154897376 | Tag | 08  b6  dd                                                      |     |
  156709024 |  156711392 | Tag | 04  00                                                          |     |
  156732208 |  156735728 | Tag | 08  b6  dd                                                      |     |
  158568096 |  158570464 | Tag | 04  00                                                          |     |
  158591312 |  158594832 | Tag | 08  b6  dd                                                      |     |
  160399792 |  160402160 | Tag | 04  00                                                          |     |
  160422976 |  160426496 | Tag | 08  b6  dd                                                      |     |
  162236576 |  162238944 | Tag | 04  00                                                          |     |
  162259760 |  162263280 | Tag | 08  b6  dd                                                      |     |
  164157248 |  164159616 | Tag | 04  00                                                          |     |
  164180448 |  164183968 | Tag | 08  b6  dd                                                      |     |
  166061632 |  166064000 | Tag | 04  00                                                          |     |
  166084816 |  166088336 | Tag | 08  b6  dd                                                      |     |
  167934016 |  167936384 | Tag | 04  00                                                          |     |
  167957232 |  167960752 | Tag | 08  b6  dd                                                      |     |
  169911968 |  169914336 | Tag | 04  00                                                          |     |
  169935168 |  169938688 | Tag | 08  b6  dd                                                      |     |
  171771344 |  171773712 | Tag | 04  00                                                          |     |
  171794544 |  171798064 | Tag | 08  b6  dd                                                      |     |
  172983888 |  172988560 | Tag | 00  00  00  00                                                  |     |
  173009040 |  173013712 | Tag | f2  39  66  59                                                  |     |
  175093680 |  175096048 | Tag | 04  00                                                          |     |
  175116864 |  175120384 | Tag | 08  b6  dd                                                      |     |
  176925440 |  176927808 | Tag | 04  00                                                          |     |
  176948640 |  176952160 | Tag | 08  b6  dd                                                      |     |
  178764396 |  178765388 | Rdr | 52                                                              |     | WUPA
  178766640 |  178769008 | Tag | 04  00                                                          |     |
  178789840 |  178793360 | Tag | 08  b6  dd                                                      |     |
  180699020 |  180700012 | Rdr | 52                                                              |     | WUPA
  180701264 |  180703632 | Tag | 04  00                                                          |     |
  180724464 |  180727984 | Tag | 08  b6  dd                                                      |     |
  182622112 |  182624480 | Tag | 04  00                                                          |     |
  182645312 |  182648832 | Tag | 08  b6  dd                                                      |     |
  184529360 |  184531728 | Tag | 04  00                                                          |     |
  184552576 |  184556096 | Tag | 08  b6  dd                                                      |     |
  186414016 |  186416384 | Tag | 04  00                                                          |     |
  186437216 |  186440736 | Tag | 08  b6  dd                                                      |     |
  188218524 |  188223292 | Rdr | 50  00  57  cd                                                  |  ok | HALT
  188265596 |  188266588 | Rdr | 52                                                              |     | WUPA
  188267840 |  188270208 | Tag | 04  00                                                          |     |
  188291040 |  188294560 | Tag | 08  b6  dd                                                      |     |
  190092768 |  190095136 | Tag | 04  00                                                          |     |
  190115968 |  190119488 | Tag | 08  b6  dd                                                      |     |
  190180832 |  190185504 | Tag | 00  00  00  00                                                  |     |
  190206064 |  190210736 | Tag | c9  ec  35  8d                                                  |     |
  192330160 |  192332528 | Tag | 04  00                                                          |     |
  192353360 |  192356880 | Tag | 08  b6  dd                                                      |     |
  194185312 |  194187680 | Tag | 04  00                                                          |     |
  194208512 |  194212032 | Tag | 08  b6  dd                                                      |     |
  196060220 |  196061212 | Rdr | 52                                                              |     | WUPA
  196062464 |  196064832 | Tag | 04  00                                                          |     |
  196085664 |  196089184 | Tag | 08  b6  dd                                                      |     |
  197965440 |  197967808 | Tag | 04  00                                                          |     |
  197988640 |  197992160 | Tag | 08  b6  dd                                                      |     |
  199747772 |  199748188 | Rdr | 01                                                              |     | ?
  199748412 |  199749276 | Rdr |22!                                                              |     | ?
  199794544 |  199796912 | Tag | 04  00                                                          |     |
  199817744 |  199821264 | Tag | 08  b6  dd                                                      |     |
  201621184 |  201623552 | Tag | 04  00                                                          |     |
  201644384 |  201647904 | Tag | 08  b6  dd                                                      |     |
  203450896 |  203453264 | Tag | 04  00                                                          |     |
  203474096 |  203477616 | Tag | 08  b6  dd                                                      |     |
  205277440 |  205279808 | Tag | 04  00                                                          |     |
  205300640 |  205304160 | Tag | 08  b6  dd                                                      |     |
  207108976 |  207111344 | Tag | 04  00                                                          |     |
  207132192 |  207135712 | Tag | 08  b6  dd

**Comment by pwpiwi** [comment]
Would you please ask questions not related to the source code in the forum instead of the code repository.

**Comment by maxben14** [comment]
@pwpiwi , this is not a question, it's a bug report in the proxmark sniffer. I do not understand why the proxmark often does not want to capture data from the reader and captures only from the card. Can you fix this bug in the proxmark?

**Comment by marshmellow42** [comment]
your snoop sometimes captured the reader.  it all depends on your antenna and the positioning to capture the best snoop.  is it possible to improve the sensitivity with code, with the pm3's cpu realtime? not likely..  but i don't know.  but overall i wouldn't consider this a bug, more of a requested enhancement...

**Comment by maxben14** [comment]
@marshmellow42 , problem that proxmark often don't capture answer from my Android. How increase timing waiting in proxmark software ?

**Comment by marshmellow42** [comment]
android phones have terrible interference and signal strength.  i'm impressed we can read anything at all from them...
