### ISSUE TITLE
Cloning a mifare card 

### ISSUE THREAD

**Issue by h00282019** [Proxmark/proxmark3#581]
I am doing my graduation project on RFID Cloning. the main objective is to take the data from one card and create an exact copy of it using the proxmark3 and use the cloned card to successfully access the faculty door. 

I would appreciate if anyone can help me with the steps to do so. I managed to read the data from the original card but got stuck there. I don't know which blank cards I'm supposed to use and what codes should I use. couldn't find any step by step guide online.

Any help is extremely appreciated.

**Comment by pwpiwi** [comment]
This is the proxmark code repository. The forum to ask questions like this can be found here:

http://www.proxmark.org/forum/index.php
