### ISSUE TITLE
getting started with proxmark 3 for windows

### ISSUE THREAD

**Issue by 5H3P** [Proxmark/proxmark3#608]
Hi all

I have a problem getting started, followed this guide and stuck at stage 8 there is no arrow to click on?

Download (and install) 7-ZIP from here: http://www.7-zip.org/download.html
Download (and install) GitHub for Windows from here: http://windows.github.com/
Download "ProxSpace-master.zip" from: https://github.com/Gator96100/ProxSpace/archive/master.zip
"ProxSpace-master.zip" should be extracted wherever you want to keep the Proxmark project. Additionally, the location should not include spaces. For instance - "C:\Projects\Proxmark" would be acceptable whereas "C:\Users\Administrator\My Projects\Proxmark" would not.
Assuming you installed 7-ZIP using all of the default options, you should have 7-ZIP context menu items.
Right-click "ProxSpace-master.zip" and select 7-Zip > Extract Here.
Assuming you installed GitHub for Windows using all of the default options, you should open it and drag&drop https://github.com/Proxmark/proxmark3 link into "drag a repository here to add" button.
**_**Click on the right arrow next to "Proxmark/proxmark3**_**" name and let it sync with the repository; source code will be downloaded here: "C:\Users\USERNAME\Documents\GitHub\proxmark3".

**Comment by pwpiwi** [comment]
Well, the Github for Windows GUI changes from time to time. The sync button is in the upper right corner now. A sync is automatically done when you clone the repository first time.
