### ISSUE TITLE
Provide OS X instructions to use brew (instead of macports)

### ISSUE THREAD

**Issue by borjaburgos** [Proxmark/proxmark3#61]
Hey! Got it working using [brew.sh](brew.sh) for OS X, would it be of interest for me to document and do a PR with additional instructions for the wiki?

**Comment by holiman** [comment]
Sure, documentation is always nice!

**Comment by iceman1001** [comment]
@borjaburgos  It would be nice if you make a PR with your documentation.  In any case, isn't it time to close this issue?
