### ISSUE TITLE
proxmark3 doesn't mount

### ISSUE THREAD

**Issue by CedricBouchard** [Proxmark/proxmark3#612]
Hi,
I've just acquired a Proxmark3 Kit, and it can't seem to mount. Fresh out of the box it was correctly showing up under COM ports in device manager on my windows machine. I've followed the getting started guide for windows and encountered no problem. When I was finished setting it up, I was able to connect to it and all was working great. The problem came out when I plugged in the LF antenna. Once I've plugged it in, my proxmark3 showed up under USB devices in device manager and wasn't recognized. I then unplugged it, unplugged the antenna, and plugged it back in again. At this point it wasn't showing up at all. I then decided to plug it in my Kali Linux 2018.1 machine and didn't showed up either when I typed "dmesg | grep ttyACM". I've read a lot about issues on the internet and every time they mentioned the function button on the proxmark3 and that when they keep it pressed down it shows up, so I tried it and again, nothing was showing up.
At this point I don't know what to do and could use some help haha!
Anyways, kind regards.

**Comment by pwpiwi** [comment]
This is the Proxmark code repository. You can find the forum here: http://www.proxmark.org/forum/index.php
