### ISSUE TITLE
mfkeys.lua broken

### ISSUE THREAD

**Issue by TomHarkness** [Proxmark/proxmark3#628]
When running the mfkeys I get the following output. Tried with both pm3 easy and RDV3.

proxmark3> script run mfkeys
--- Executing: mfkeys.lua, args ''
This script implements check keys.
It utilises a large list of default keys (currently 92 keys).
If you want to add more, just put them inside mf_default_keys.lua.
Found a NXP MIFARE CLASSIC 1k | Plus 2k tag
Testing block 3, keytype 0, with 85 keys
.../client/scripts/mfkeys.lua:60: invalid value (nil) at index 93 in table for 'concat'

**Comment by pwpiwi** [comment]
In line 72 of mfkeys.lua, try replacing
```
start = start+n+1
```
with
```
start = start+n
```

**Comment by TomHarkness** [comment]
This seems to fix the issue.

**Comment by pwpiwi** [comment]
Are you going to raise a Pull Request with the fix?

**Comment by TomHarkness** [comment]
Apologies for delay on that - been a bit flat out with work.

**Comment by pwpiwi** [comment]
No problem. I pushed the fix - in the end it wasn't too much work.
