### ISSUE TITLE
Make targets OS X

### ISSUE THREAD

**Issue by TomHarkness** [Proxmark/proxmark3#633]
Firstly - still getting my head around the codebase, don't hate me if this is an obvious thing that I am missing :P.

OSX High Sierra.

I can compile fine via "make clean; make" on the command line. However:

I get an error "No target exists for 'all clean" when executing the make file from within Atom editor with the popular build-make plugin to execute makefile targets.

If I change the entries in the makefile to be seperate like:

all: %: client/% bootrom/% armsrc/% recovery/% mfkey/% nonce2key/%
clean: %: client/% bootrom/% armsrc/% recovery/% mfkey/% nonce2key/%

I can separately run clean and make all to compile.

**Comment by pwpiwi** [comment]
I don't know "Atom editor" and the "popular build-make plugin" (OSX is misrepresented among the developers - mostly Linux and Windows here) and therefore cannot provide a solution for your issue. But it seems not to be related to the Proxmark code. I suggest to post your question in a relevant (Atom editor?) forum.

**Comment by TomHarkness** [comment]
Will follow up on Atom the Atom forums. Thanks pwpiwi! 

My main environment is OS X so had hoped to be able to set up a reasonable development environment for pm3 stuff. I can otherwise compile everything, debug and run fine. Just this one "nice feature" that I can't get to work in the IDE. No issues though I will press on!

**Comment by pwpiwi** [comment]
If you can solve your issue, please come back here and write a short note. I will keep this open for a few weeks.

**Comment by pwpiwi** [comment]
any news?

**Comment by TomHarkness** [comment]
Not yet sorry. Been focusing on some custom antennas that will be released soon. I’ll get back to the software side of things soon :) I do intend to fix this eventually lol.

**Comment by pwpiwi** [comment]
Any news? Close?

**Comment by pwpiwi** [comment]
@TomHarkness: still around? What happened to your issue with the Atom Editor?
