### ISSUE TITLE
Mifare sniffer card.

### ISSUE THREAD

**Issue by maxben14** [Proxmark/proxmark3#688]
Is there a card that can get the key mifare 1k using an attack on the reader ?
There are no validators in my city, want crack key on 1k card which use in transport.

**Comment by merlokk** [comment]
it was at china shops, but it not a issue of proxmark3
http://www.proxmark.org/forum/viewforum.php?id=5

**Comment by maxben14** [comment]
@merlokk, can give link on shop where buy this card.

**Comment by merlokk** [comment]
http://www.proxmark.org/forum/viewtopic.php?id=1649
lets go to the forum.
