### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by seufa** [Proxmark/proxmark3#71]
Hello

I tried to compile commit 188b2dbec4594e057a981d1d2b85b1a0c8745d78 from 2/26/15. I am getting errors due to a missing file. optimized_cipher.h
Is this file somewhere else in the project or on the internet?

**Comment by holiman** [comment]
My bad, I'll fix in a few hours

**Comment by holiman** [comment]
Fixed in c99dc845b1057be4ba2e535730345b4e6e8bfc58
