### ISSUE TITLE
Mifare authentication error in step 2.

### ISSUE THREAD

**Issue by HLimbada** [Proxmark/proxmark3#710]
Hello folks,
I've been working on mifare classic 1 from last few days by using ST25R3911B with crypto library of **Nohl** (here on Github : [).](https://github.com/ralfhartmann/GLOR/tree/master/AS3911_GP_Src_2.0.6%20with%20Mifare/AS3911/firmware/application/mifare_src)
Everytime i'm getting **tag nonce** as the answer of first step, but when i'm going to perform 2nd step with encrypted 8 byte of data to transmit and i'm getting nothing in return(actually one byte only which is similar to the 1st byte of data that i have transmitted).
Here is the few logs of my communication,

`Welcome to DISCO-STM32L4x6
RFAL initialization succeeded..
MifareInitialize : ERR_NONE
-----------------------------------
processIso14443a err : ERR_NONE
ISO14443A/NFC-A card found. 
ATQA: 0400
SAK: 080008 UID: A34856B5
-----------------------------------
mifareAuthenticate
mifareAuthenticationStep1
37 5e 8d c8 
Initialization ok
uid: 41333438
Card nonce: 0x375E8DC8
Auth step 1 Successfull
tag_nonce : 0X375E8DC8
mifareAuthenticationStep2
transmitting: f8,154,d6,127,119,1b8,1ab,6e,
  raw: f8,a8,5a,3b,99,11,f7,6a,37,
extracting : f8 
!! received 0x1 bytes, expected 4 bytes and 0 bits. Abort.
AuthenticationError : ERR_NOTFOUND
-----------------------------------
processIso14443a err : ERR_NONE
ISO14443A/NFC-A card found. 
ATQA: 0400
SAK: 080008 UID: A34856B5
-----------------------------------
mifareAuthenticate
mifareAuthenticationStep1
38 79 98 ab 
Initialization ok
uid: 41333438
Card nonce: 0x387998AB
Auth step 1 Successfull
tag_nonce : 0X387998AB
mifareAuthenticationStep2
transmitting: 1bc,ae,158,180,1d0,191,105,179,
  raw: bc,5d,61,5,c,3d,72,c1,bc,
extracting :  bc 
!! received 0x1 bytes, expected 4 bytes and 0 bits. Abort.
AuthenticationError : ERR_NOTFOUND
-----------------------------------
processIso14443a err : ERR_NONE
ISO14443A/NFC-A card found. 
ATQA: 0400
SAK: 080008 UID: A34856B5
-----------------------------------
`
Does anyone have idea about this or else guide me where i'm lagging to perform proper steps.
Thanks in advance!

**Comment by HLimbada** [comment]
Hello @merlokk 
Thanks for your reply!
Already tried but didn't find any proper solution.
Huzaifah

**Comment by merlokk** [comment]
just find a sample like that
https://github.com/Proxmark/proxmark3/issues/412
```
33061958 | 33072422 | Rdr | 93 70 0e b7 d9 b7 d7 dc 48 | ok | SELECT_UID
33074106 | 33077626 | Tag | 08 b6 dd | |
35303750 | 35308454 | Rdr | 60 00 f5 7b | ok | AUTH-A(0)
35312954 | 35317690 | Tag | 01 02 03 04 | |
35319084 | 35328396 | Rdr | c9 95! 90! 5d! 71! ec f1 df! | !crc| ?
35337056 | 35341728 | Tag | 84 35 42 93 | |
35546696 | 35551464 | Rdr |30! 00! 02 a8 | ok | READBLOCK(0)
35565884 | 35586684 | Tag |ce! bc! f5 34! df! ee 09! 78 bc 1f b5 f3! 59! 88! 54 2f! | |
| | | a6 36 | !crc|
```
and try your auth with this requests/answers

**Comment by HLimbada** [comment]
Hello @merlokk 
As i mentioned above i'm not using prox library.
I have combinely use rfal library with mifare crypto from [Mifare Library](https://github.com/ralfhartmann/GLOR/tree/master/AS3911_GP_Src_2.0.6%20with%20Mifare/AS3911/firmware/application/mifare_src) so as per my understand i'm not able to find sample like you've mentioned in last post.
Hope you understand.
Thanks for your reply!

**Comment by merlokk** [comment]
the sample is the same....  here is just a communication dump between card and reader. you need just send to your lib values from dump and try to check if lib returns values from dump...

P.S. here is a proxmark issues. on the forum there is the information about auth from like 2010 year as i mentioned above. just read(

**Comment by HLimbada** [comment]
ok, i try and see if anything found helpful.

**Comment by HLimbada** [comment]
Hello @merlokk 
I think you've trying to said that follow below steps, If i'm not wrong as per the [Given](https://github.com/Proxmark/proxmark3/issues/710#issuecomment-435825175).

1. Trace the successful authentication between tag and reader.
2. Being reader trying to get the same nonce as successful step.
3. Than follow the procedure with reply and do the things.

Is i understand wrong?
Thanks in advance!

**Comment by merlokk** [comment]
hi
you can obtain the sample without any efforts....   just launch `hf mf rdbl` and then `hf 14a list`. That's all.
you dont need a card at all. all what you need - just send the obtained responses to your code and look if your code answers the same as legitimate reader.

**Comment by pwpiwi** [comment]
Closed because there seems to be no relation to proxmark code.
