### ISSUE TITLE
Error on Step 11 Windows 10 User

### ISSUE THREAD

**Issue by M4cM4rco** [Proxmark/proxmark3#712]
Hello, 

I got two errors on step 11. I think this is the importen code:
e -lpthread -lm -o fpga_compress
make[1]: Verzeichnis „/pm3/client“ wird verlassen
make -C bootrom  all
make[1]: Verzeichnis „/pm3/bootrom“ wird betreten
/bin/sh: arm-none-eabi-gcc: Kommando nicht gefunden.
/bin/sh: arm-none-eabi-gcc: Kommando nicht gefunden.
/bin/sh: arm-none-eabi-gcc: Kommando nicht gefunden.
/bin/sh: arm-none-eabi-gcc: Kommando nicht gefunden.
/bin/sh: arm-none-eabi-gcc: Kommando nicht gefunden.
perl ../tools/mkversion.pl .. > version.c || cp ../common/default_version.c version.c
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
arm-none-eabi-gcc -c -I../include -I../common -I. -Wall -Werror -pedantic -std=c99 -Os -I. -mthumb -mthumb-interwork -o obj/version.o version.c
make[1]: arm-none-eabi-gcc: Befehl nicht gefunden
make[1]: *** [../common/Makefile.common:90: obj/version.o] Fehler 127
make[1]: Verzeichnis „/pm3/bootrom“ wird verlassen
make: *** [Makefile:29: bootrom/all] Fehler 2

Thanks for help.
Ps.: Maybe some words are german

Kommando nicht gefunden = Comando not found
Fehler=Error

**Comment by pwpiwi** [comment]
Either you did not install the ARM toolchain (it is included in the ProxSpace environment) or it is not in your search path.

**Comment by Gator96100** [comment]
What is the output of `echo $PATH`?
Did you delete the pm3 folder? The pm3 folder contains important files that must not be removed.

**Comment by pwpiwi** [comment]
Can this be closed? @M4cM4rco: would you mind telling us the issue and how (if at all) you solved it?

**Comment by siisko** [comment]
Hi,

Still the same problem here.

```$ gcc -v
Utilisation des specs internes.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Cible : x86_64-redhat-linux
Configuré avec: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Modèle de thread: posix
Algorithmes de compression LTO supportés: zlib zstd
gcc version 10.2.1 20201125 (Red Hat 10.2.1-9) (GCC)

$ arm-none-eabi-gcc --version
arm-none-eabi-gcc (Fedora 10.2.0-2.fc32) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ uname -a
Linux localhost 5.9.16-100.fc32.x86_64 #1 SMP Mon Dec 21 14:10:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
When make clean &&  make all, this error appears:
```
arm-none-eabi-gcc -nostartfiles -nodefaultlibs -Wl,-gc-sections -n -Wl,-T,ldscript-flash,-Map,obj/bootrom.map -o obj/bootrom.elf obj/version.o obj/ram-reset.o obj/flash-reset.o obj/usb_cdc.o obj/bootrom.o -lgcc
/usr/lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: obj/usb_cdc.o: in function `cmd_send':
usb_cdc.c:(.text+0x6f8): undefined reference to `memcpy'
/usr/lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: obj/usb_cdc.o: in function `cmd_send_old':
usb_cdc.c:(.text+0x75e): undefined reference to `memcpy'
/usr/lib/gcc/arm-none-eabi/10.2.0/../../../../arm-none-eabi/bin/ld: obj/bootrom.o: in function `BootROM':
bootrom.c:(.text+0x38e): undefined reference to `memset'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:41: obj/bootrom.elf] Error 1
make[1] : on quitte le répertoire « /home/aaa/tools/proxmark3/bootrom »
make: *** [Makefile:29: bootrom/all] Error 2
```

Someone could help ?
Thanks

**Comment by pwpiwi** [comment]
This is a completely different problem. See issue #949.
