### ISSUE TITLE
forum registration is broken

### ISSUE THREAD

**Issue by sbma44** [Proxmark/proxmark3#719]
authedmine.com has an invalid SSL cert, preventing the captcha from working. Confirmed in Chrome and Safari. The only workaround here is installing a busted cert which seems nonideal.

![image](https://user-images.githubusercontent.com/31717/48852009-70db1880-ed7a-11e8-91e5-e6977d17e382.png)

![image](https://user-images.githubusercontent.com/31717/48851970-602aa280-ed7a-11e8-989f-85c6b43578e7.png)

**Comment by RfidResearchGroup** [comment]
Not ideal,  but it works very well against spam-bots.   Lets see if authedmine updates their SSL cert since it expires 24november 2018..

**Comment by sbma44** [comment]
Actually, ignore me: looks like the network I'm on is running a Cisco firewall thingamajig that has authedmine.com marked as malware. The busted Cisco cert is me getting MITMed by my own LAN. I opened a VPN connection and the captcha works fine. Sorry for the false alarm!
