### ISSUE TITLE
proxmark3 serial not showing up in mac os mojave 10.14.1

### ISSUE THREAD

**Issue by kacipbuah** [Proxmark/proxmark3#737]
result for command: **system_profiler SPUSBDataType**
USB:

    USB 3.0 Bus:

      Host Controller Driver: AppleUSBXHCIWPT
      PCI Device ID: 0x9cb1 
      PCI Revision ID: 0x0003 
      PCI Vendor ID: 0x8086 

        Bluetooth USB Host Controller:

          Product ID: 0x8290
          Vendor ID: 0x05ac (Apple Inc.)
          Version: 1.66
          Speed: Up to 12 Mb/sec
          Manufacturer: Broadcom Corp.
          Location ID: 0x14300000 / 4
          Current Available (mA): 500
          Current Required (mA): 0
          Extra Operating Current (mA): 0
          Built-In: Yes

        proxmark3:

          Product ID: 0x4b8f
          Vendor ID: 0x9ac4
          Version: 0.01
          Speed: Up to 12 Mb/sec
          Manufacturer: proxmark.org
          Location ID: 0x14200000 / 14
          Current Available (mA): 500
          Current Required (mA): 150
          Extra Operating Current (mA): 0

result for command: **ls /dev/cu***
/dev/cu.Bluetooth-Incoming-Port	/dev/cu.MP72872-4tBluetooth	/dev/cu.MP72877-4tBluetooth-1	/dev/cu.MP72878-4tBluetooth-1

result for command: **ls /dev/tty***
/dev/tty				/dev/ttyqd				/dev/ttyse				/dev/ttyv0
/dev/tty.Bluetooth-Incoming-Port	/dev/ttyqe				/dev/ttysf				/dev/ttyv1
/dev/tty.MP72872-4tBluetooth		/dev/ttyqf				/dev/ttyt0				/dev/ttyv2
/dev/tty.MP72877-4tBluetooth-1		/dev/ttyr0				/dev/ttyt1				/dev/ttyv3
/dev/tty.MP72878-4tBluetooth-1		/dev/ttyr1				/dev/ttyt2				/dev/ttyv4
/dev/ttyp0				/dev/ttyr2				/dev/ttyt3				/dev/ttyv5
/dev/ttyp1				/dev/ttyr3				/dev/ttyt4				/dev/ttyv6
/dev/ttyp2				/dev/ttyr4				/dev/ttyt5				/dev/ttyv7
/dev/ttyp3				/dev/ttyr5				/dev/ttyt6				/dev/ttyv8
/dev/ttyp4				/dev/ttyr6				/dev/ttyt7				/dev/ttyv9
/dev/ttyp5				/dev/ttyr7				/dev/ttyt8				/dev/ttyva
/dev/ttyp6				/dev/ttyr8				/dev/ttyt9				/dev/ttyvb
/dev/ttyp7				/dev/ttyr9				/dev/ttyta				/dev/ttyvc
/dev/ttyp8				/dev/ttyra				/dev/ttytb				/dev/ttyvd
/dev/ttyp9				/dev/ttyrb				/dev/ttytc				/dev/ttyve
/dev/ttypa				/dev/ttyrc				/dev/ttytd				/dev/ttyvf
/dev/ttypb				/dev/ttyrd				/dev/ttyte				/dev/ttyw0
/dev/ttypc				/dev/ttyre				/dev/ttytf				/dev/ttyw1
/dev/ttypd				/dev/ttyrf				/dev/ttyu0				/dev/ttyw2
/dev/ttype				/dev/ttys0				/dev/ttyu1				/dev/ttyw3
/dev/ttypf				/dev/ttys000				/dev/ttyu2				/dev/ttyw4
/dev/ttyq0				/dev/ttys1				/dev/ttyu3				/dev/ttyw5
/dev/ttyq1				/dev/ttys2				/dev/ttyu4				/dev/ttyw6
/dev/ttyq2				/dev/ttys3				/dev/ttyu5				/dev/ttyw7
/dev/ttyq3				/dev/ttys4				/dev/ttyu6				/dev/ttyw8
/dev/ttyq4				/dev/ttys5				/dev/ttyu7				/dev/ttyw9
/dev/ttyq5				/dev/ttys6				/dev/ttyu8				/dev/ttywa
/dev/ttyq6				/dev/ttys7				/dev/ttyu9				/dev/ttywb
/dev/ttyq7				/dev/ttys8				/dev/ttyua				/dev/ttywc
/dev/ttyq8				/dev/ttys9				/dev/ttyub				/dev/ttywd
/dev/ttyq9				/dev/ttysa				/dev/ttyuc				/dev/ttywe
/dev/ttyqa				/dev/ttysb				/dev/ttyud				/dev/ttywf
/dev/ttyqb				/dev/ttysc				/dev/ttyue
/dev/ttyqc				/dev/ttysd				/dev/ttyuf

**Comment by drandreas** [comment]
On MacOS the Proxmark3 usually shows up as /dev/tty.usbmodemXXXXX.

Does your Proxmark3 show up on other operating systems (Linux, Windows...)?

**Comment by drandreas** [comment]
see also #650
