### ISSUE TITLE
invalid serial port

### ISSUE THREAD

**Issue by patpat19** [Proxmark/proxmark3#740]
i'm using a mac. Each time i try to flash my proxmark rdv4 it gives me invalid serial port
![image1](https://user-images.githubusercontent.com/45771459/50305219-2a073e00-0460-11e9-86eb-b2f2482233e1.png)

**Comment by pwpiwi** [comment]
Are you sure that your proxmark is on /dev/tty.usbmodem1411 (try ls /dev/tty*)? 

Does it work with the official software (this repository)?

**Comment by patpat19** [comment]
Yes it was on /dev/tty.usbmodem1411 but i was flashing it from the new rfidresearchgroup repository, with version 0.1, but now it works. Thank you
