### ISSUE TITLE
ISO 15693

### ISSUE THREAD

**Issue by owengombas** [Proxmark/proxmark3#742]
I'm currently searching how to copy/write/emulate an UID of an ISO 15693 card. What's is possible for the moment with a Proxmark and 15693 ?

**Comment by pwpiwi** [comment]
You are lucky. I am currently working on the ISO15693 functions. Simulating an UID is possible since a few weeks. 

I don't have UID changeable cards and therefore cannot confirm that UID copying works.

**Comment by OwenCalvin** [comment]
Good news ! I've buy a proxmark on Aliexpress, I hope it will work haha...
I found some websites who sell ISO 15693 UID changeable cards, maybe I will buy it to try to copy/write UID
(low budget proxmark3 rdv4: https://s.click.aliexpress.com/e/0IWDI12)

**Comment by pwpiwi** [comment]
Indeed, low budget. You get what you pay for.

**Comment by OwenCalvin** [comment]
I found this topic http://www.proxmark.org/forum/viewtopic.php?id=5633
with UID changeable cards. Do you think that I can change the UID as many times as I want ?

**Comment by pwpiwi** [comment]
Don't know. What about asking in the forum?

**Comment by OwenCalvin** [comment]
Yes I sent an email to iceman about that :)
