### ISSUE TITLE
Step 11 fails: make clean && make all

### ISSUE THREAD

**Issue by Chris-Devine** [Proxmark/proxmark3#772]
Followed the windows "Development environment installation" instructions but fails on step 11.

Any ideas? iv posted the output below

`pm3 ~$ make clean && make all
make -C client  clean
make[1]: Entering directory `/pm3/client'
rm -f proxmark3 flasher fpga_compress  proxmark3.exe  flasher.exe  fpga_compress.exe obj/uart_posix.o obj/uart_win32.o obj/util.o obj/util_posix.o obj/ui.o obj/comms.o obj/cmdsmartcard.o obj/pcsc.o obj/crapto1/crapto1.o obj/crapto1/crypto1.o obj/crypto/libpcrypto.o obj/crypto/asn1utils.o obj/crypto/asn1dump.o obj/cliparser/argtable3.o obj/cliparser/cliparser.o obj/fido/additional_ca.o obj/fido/cose.o obj/fido/cbortools.o obj/fido/fidocore.o obj/mfkey.o obj/loclass/cipher.o obj/loclass/cipherutils.o obj/loclass/ikeys.o obj/loclass/elite_crack.o obj/loclass/fileutils.o obj/whereami.o obj/mifarehost.o obj/mifare4.o obj/parity.o obj/crc.o obj/crc16.o obj/crc64.o obj/iso14443crc.o obj/iso15693tools.o obj/graph.o obj/cmddata.o obj/lfdemod.o obj/emv/crypto_polarssl.o obj/emv/crypto.o obj/emv/emv_pk.o obj/emv/emv_pki.o obj/emv/emv_pki_priv.o obj/emv/test/cryptotest.o obj/emv/apduinfo.o obj/emv/dump.o obj/emv/tlv.o obj/emv/emv_tags.o obj/emv/dol.o obj/emv/emvjson.o obj/emv/emvcore.o obj/emv/test/crypto_test.o obj/emv/test/sda_test.o obj/emv/test/dda_test.o obj/emv/test/cda_test.o obj/emv/cmdemv.o obj/emv/emv_roca.o obj/cmdhf.o obj/cmdhflist.o obj/cmdhf14a.o obj/cmdhf14b.o obj/cmdhf15.o obj/cmdhfepa.o obj/cmdhflegic.o obj/cmdhficlass.o obj/cmdhfmf.o obj/cmdhfmfp.o obj/cmdhfmfu.o obj/cmdhfmfhard.o obj/hardnested/hardnested_bruteforce.o obj/cmdhftopaz.o obj/cmdhffido.o obj/cmdhw.o obj/cmdlf.o obj/cmdlfawid.o obj/cmdlfcotag.o obj/cmdlfem4x.o obj/cmdlffdx.o obj/cmdlfgproxii.o obj/hidcardformatutils.o obj/hidcardformats.o obj/cmdlfhid.o obj/cmdlfhitag.o obj/cmdlfio.o obj/cmdlfindala.o obj/cmdlfjablotron.o obj/cmdlfnexwatch.o obj/cmdlfnoralsy.o obj/cmdlfparadox.o obj/cmdlfpcf7931.o obj/cmdlfpresco.o obj/cmdlfpyramid.o obj/cmdlfsecurakey.o obj/cmdlft55xx.o obj/cmdlfti.o obj/cmdlfviking.o obj/cmdlfvisa2000.o obj/cmdlfpac.o obj/cmdparser.o obj/cmdmain.o obj/scripting.o obj/cmdscript.o obj/pm3_binlib.o obj/pm3_bitlib.o obj/protocols.o  obj/deflate.o obj/adler32.o obj/trees.o obj/zutil.o obj/inflate.o obj/inffast.o obj/inftrees.o obj/proxgui.o obj/proxguiqt.o obj/proxguiqt.moc.o obj/hardnested/hardnested_bf_core_NOSIMD.o obj/hardnested/hardnested_bitarray_core_NOSIMD.o obj/hardnested/hardnested_bf_core_MMX.o obj/hardnested/hardnested_bitarray_core_MMX.o obj/hardnested/hardnested_bf_core_SSE2.o obj/hardnested/hardnested_bitarray_core_SSE2.o obj/hardnested/hardnested_bf_core_AVX.o obj/hardnested/hardnested_bitarray_core_AVX.o obj/hardnested/hardnested_bf_core_AVX2.o obj/hardnested/hardnested_bitarray_core_AVX2.o obj/*.o *.moc.cpp ui/ui_overlays.h lualibs/usb_cmd.lua
cd ../liblua && make clean
make[2]: Entering directory `/pm3/liblua'
rm -f liblua.a lua luac lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lbitlib.o lcorolib.o ldblib.o liolib.o lmathlib.o loslib.o lstrlib.o ltablib.o loadlib.o linit.o  lua.o luac.o
make[2]: Leaving directory `/pm3/liblua'
cd ./jansson && make clean
make[2]: Entering directory `/pm3/client/jansson'
rm -f dump.o error.o hashtable.o hashtable_seed.o load.o memory.o pack_unpack.o strbuffer.o strconv.o utf.o path.o value.o
rm -f libjansson.a
make[2]: Leaving directory `/pm3/client/jansson'
cd ../common/mbedtls && make clean
make[2]: Entering directory `/pm3/common/mbedtls'
rm -f aes.o asn1parse.o asn1write.o base64.o bignum.o ctr_drbg.o entropy_poll.o entropy.o error.o timing.o ecp.o ecp_curves.o certs.o camellia.o blowfish.o cipher_wrap.o cipher.o cmac.o des.o ecdsa.o md.o md_wrap.o md5.o oid.o pem.o arc4.o pk.o pk_wrap.o pkwrite.o pkcs5.o pkcs12.o pkparse.o platform.o platform_util.o rsa.o rsa_internal.o sha1.o sha256.o sha512.o threading.o x509.o x509_crl.o x509_crt.o
rm -f libmbedtls.a
make[2]: Leaving directory `/pm3/common/mbedtls'
cd ./tinycbor && make clean
make[2]: Entering directory `/pm3/client/tinycbor'
rm -f cborencoder.o cborencoder_close_container_checked.o cborerrorstrings.o cborparser.o cborparser_dup_string.o cborpretty.o cbortojson.o cborvalidation.o
rm -f tinycbor.a
make[2]: Leaving directory `/pm3/client/tinycbor'
make[1]: Leaving directory `/pm3/client'
make -C bootrom  clean
make[1]: Entering directory `/pm3/bootrom'
make[1]: Leaving directory `/pm3/bootrom'
make[1]: Entering directory `/pm3/bootrom'
rm -rf obj/*.o
rm -rf obj/*.elf
rm -rf obj/*.s19
rm -rf obj/*.map
rm -rf obj/*.d
rm -rf version.c
make[1]: Leaving directory `/pm3/bootrom'
make -C armsrc  clean
make[1]: Entering directory `/pm3/armsrc'
make[1]: Leaving directory `/pm3/armsrc'
make[1]: Entering directory `/pm3/armsrc'
rm -rf obj/*.o
rm -rf obj/*.elf
rm -rf obj/*.s19
rm -rf obj/*.map
rm -rf obj/*.d
rm -rf obj/*.z
rm -rf obj/*.bin
rm -rf version.c
make[1]: Leaving directory `/pm3/armsrc'
make -C recovery  clean
make[1]: Entering directory `/pm3/recovery'
rm -f bootrom.bin fullimage.bin proxmark3_recovery.bin
make[1]: Leaving directory `/pm3/recovery'
make -C tools/mfkey  clean
make[1]: Entering directory `/pm3/tools/mfkey'
rm -f crypto1.o crapto1.o parity.o util_posix.o mfkey.o mfkey32 mfkey64  mfkey32.exe  mfkey64.exe
make[1]: Leaving directory `/pm3/tools/mfkey'
make -C client  all
make[1]: Entering directory `/pm3/client'
Compiling liblua, using platform mingw
cd ../liblua && make mingw
make[2]: Entering directory `/pm3/liblua'
make "LUA_A=lua52.dll" "LUA_T=lua.exe" \
        "AR=gcc -shared -o" "RANLIB=strip --strip-unneeded" \
        "SYSCFLAGS=-DLUA_BUILD_AS_DLL" "SYSLIBS=" "SYSLDFLAGS=-s" lua.exe
make[3]: Entering directory `/pm3/liblua'
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lua.o lua.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lapi.o lapi.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lcode.o lcode.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lctype.o lctype.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ldebug.o ldebug.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ldo.o ldo.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ldump.o ldump.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lfunc.o lfunc.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lgc.o lgc.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o llex.o llex.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lmem.o lmem.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lobject.o lobject.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lopcodes.o lopcodes.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lparser.o lparser.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lstate.o lstate.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lstring.o lstring.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ltable.o ltable.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ltm.o ltm.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lundump.o lundump.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lvm.o lvm.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lzio.o lzio.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lauxlib.o lauxlib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lbaselib.o lbaselib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lbitlib.o lbitlib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lcorolib.o lcorolib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ldblib.o ldblib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o liolib.o liolib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lmathlib.o lmathlib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o loslib.o loslib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lstrlib.o lstrlib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ltablib.o ltablib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o loadlib.o loadlib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o linit.o linit.c
gcc -shared -o lua52.dll lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lbitlib.o lcorolib.o ldblib.o liolib.o lmathlib.o loslib.o lstrlib.o ltablib.o loadlib.o linit.o
strip --strip-unneeded lua52.dll
gcc -o lua.exe -s  lua.o lua52.dll -lm
make[3]: Leaving directory `/pm3/liblua'
make "LUAC_T=luac.exe" luac.exe
make[3]: Entering directory `/pm3/liblua'
gcc -O2 -Wall -DLUA_COMPAT_ALL     -c -o luac.o luac.c
ar rcu liblua.a lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lbitlib.o lcorolib.o ldblib.o liolib.o lmathlib.o loslib.o lstrlib.o ltablib.o loadlib.o linit.o
ranlib liblua.a
gcc -o luac.exe   luac.o liblua.a -lm
make[3]: Leaving directory `/pm3/liblua'
make[2]: Leaving directory `/pm3/liblua'
Compiling jansson
cd ./jansson && make all
make[2]: Entering directory `/pm3/client/jansson'
gcc -DHAVE_STDINT_H -I. -O2 -Wall -Wno-unused-variable -Wno-unused-function -c -o dump.o dump.c -lm
In file included from jansson_private.h:16,
                 from dump.c:12:
jansson.h: In function 'json_incref':
jansson.h:124: warning: implicit declaration of function '__atomic_add_fetch'
jansson.h:124: error: '__ATOMIC_ACQUIRE' undeclared (first use in this function)
jansson.h:124: error: (Each undeclared identifier is reported only once
jansson.h:124: error: for each function it appears in.)
jansson.h: In function 'json_decref':
jansson.h:134: warning: implicit declaration of function '__atomic_sub_fetch'
jansson.h:134: error: '__ATOMIC_RELEASE' undeclared (first use in this function)
make[2]: *** [dump.o] Error 1
make[2]: Leaving directory `/pm3/client/jansson'
make[1]: *** [jansson_build] Error 2
make[1]: Leaving directory `/pm3/client'
make: *** [client/all] Error 2
pm3 ~$ make clean && make all
make -C client  clean
make[1]: Entering directory `/pm3/client'
rm -f proxmark3 flasher fpga_compress  proxmark3.exe  flasher.exe  fpga_compress.exe obj/uart_posix.o obj/uart_win32.o obj/util.o obj/util_posix.o obj/ui.o obj/comms.o obj/cmdsmartcard.o obj/pcsc.o obj/crapto1/crapto1.o obj/crapto1/crypto1.o obj/crypto/libpcrypto.o obj/crypto/asn1utils.o obj/crypto/asn1dump.o obj/cliparser/argtable3.o obj/cliparser/cliparser.o obj/fido/additional_ca.o obj/fido/cose.o obj/fido/cbortools.o obj/fido/fidocore.o obj/mfkey.o obj/loclass/cipher.o obj/loclass/cipherutils.o obj/loclass/ikeys.o obj/loclass/elite_crack.o obj/loclass/fileutils.o obj/whereami.o obj/mifarehost.o obj/mifare4.o obj/parity.o obj/crc.o obj/crc16.o obj/crc64.o obj/iso14443crc.o obj/iso15693tools.o obj/graph.o obj/cmddata.o obj/lfdemod.o obj/emv/crypto_polarssl.o obj/emv/crypto.o obj/emv/emv_pk.o obj/emv/emv_pki.o obj/emv/emv_pki_priv.o obj/emv/test/cryptotest.o obj/emv/apduinfo.o obj/emv/dump.o obj/emv/tlv.o obj/emv/emv_tags.o obj/emv/dol.o obj/emv/emvjson.o obj/emv/emvcore.o obj/emv/test/crypto_test.o obj/emv/test/sda_test.o obj/emv/test/dda_test.o obj/emv/test/cda_test.o obj/emv/cmdemv.o obj/emv/emv_roca.o obj/cmdhf.o obj/cmdhflist.o obj/cmdhf14a.o obj/cmdhf14b.o obj/cmdhf15.o obj/cmdhfepa.o obj/cmdhflegic.o obj/cmdhficlass.o obj/cmdhfmf.o obj/cmdhfmfp.o obj/cmdhfmfu.o obj/cmdhfmfhard.o obj/hardnested/hardnested_bruteforce.o obj/cmdhftopaz.o obj/cmdhffido.o obj/cmdhw.o obj/cmdlf.o obj/cmdlfawid.o obj/cmdlfcotag.o obj/cmdlfem4x.o obj/cmdlffdx.o obj/cmdlfgproxii.o obj/hidcardformatutils.o obj/hidcardformats.o obj/cmdlfhid.o obj/cmdlfhitag.o obj/cmdlfio.o obj/cmdlfindala.o obj/cmdlfjablotron.o obj/cmdlfnexwatch.o obj/cmdlfnoralsy.o obj/cmdlfparadox.o obj/cmdlfpcf7931.o obj/cmdlfpresco.o obj/cmdlfpyramid.o obj/cmdlfsecurakey.o obj/cmdlft55xx.o obj/cmdlfti.o obj/cmdlfviking.o obj/cmdlfvisa2000.o obj/cmdlfpac.o obj/cmdparser.o obj/cmdmain.o obj/scripting.o obj/cmdscript.o obj/pm3_binlib.o obj/pm3_bitlib.o obj/protocols.o  obj/deflate.o obj/adler32.o obj/trees.o obj/zutil.o obj/inflate.o obj/inffast.o obj/inftrees.o obj/proxgui.o obj/proxguiqt.o obj/proxguiqt.moc.o obj/hardnested/hardnested_bf_core_NOSIMD.o obj/hardnested/hardnested_bitarray_core_NOSIMD.o obj/hardnested/hardnested_bf_core_MMX.o obj/hardnested/hardnested_bitarray_core_MMX.o obj/hardnested/hardnested_bf_core_SSE2.o obj/hardnested/hardnested_bitarray_core_SSE2.o obj/hardnested/hardnested_bf_core_AVX.o obj/hardnested/hardnested_bitarray_core_AVX.o obj/hardnested/hardnested_bf_core_AVX2.o obj/hardnested/hardnested_bitarray_core_AVX2.o obj/*.o *.moc.cpp ui/ui_overlays.h lualibs/usb_cmd.lua
cd ../liblua && make clean
make[2]: Entering directory `/pm3/liblua'
rm -f liblua.a lua luac lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lbitlib.o lcorolib.o ldblib.o liolib.o lmathlib.o loslib.o lstrlib.o ltablib.o loadlib.o linit.o  lua.o luac.o
make[2]: Leaving directory `/pm3/liblua'
cd ./jansson && make clean
make[2]: Entering directory `/pm3/client/jansson'
rm -f dump.o error.o hashtable.o hashtable_seed.o load.o memory.o pack_unpack.o strbuffer.o strconv.o utf.o path.o value.o
rm -f libjansson.a
make[2]: Leaving directory `/pm3/client/jansson'
cd ../common/mbedtls && make clean
make[2]: Entering directory `/pm3/common/mbedtls'
rm -f aes.o asn1parse.o asn1write.o base64.o bignum.o ctr_drbg.o entropy_poll.o entropy.o error.o timing.o ecp.o ecp_curves.o certs.o camellia.o blowfish.o cipher_wrap.o cipher.o cmac.o des.o ecdsa.o md.o md_wrap.o md5.o oid.o pem.o arc4.o pk.o pk_wrap.o pkwrite.o pkcs5.o pkcs12.o pkparse.o platform.o platform_util.o rsa.o rsa_internal.o sha1.o sha256.o sha512.o threading.o x509.o x509_crl.o x509_crt.o
rm -f libmbedtls.a
make[2]: Leaving directory `/pm3/common/mbedtls'
cd ./tinycbor && make clean
make[2]: Entering directory `/pm3/client/tinycbor'
rm -f cborencoder.o cborencoder_close_container_checked.o cborerrorstrings.o cborparser.o cborparser_dup_string.o cborpretty.o cbortojson.o cborvalidation.o
rm -f tinycbor.a
make[2]: Leaving directory `/pm3/client/tinycbor'
make[1]: Leaving directory `/pm3/client'
make -C bootrom  clean
make[1]: Entering directory `/pm3/bootrom'
make[1]: Leaving directory `/pm3/bootrom'
make[1]: Entering directory `/pm3/bootrom'
rm -rf obj/*.o
rm -rf obj/*.elf
rm -rf obj/*.s19
rm -rf obj/*.map
rm -rf obj/*.d
rm -rf version.c
make[1]: Leaving directory `/pm3/bootrom'
make -C armsrc  clean
make[1]: Entering directory `/pm3/armsrc'
make[1]: Leaving directory `/pm3/armsrc'
make[1]: Entering directory `/pm3/armsrc'
rm -rf obj/*.o
rm -rf obj/*.elf
rm -rf obj/*.s19
rm -rf obj/*.map
rm -rf obj/*.d
rm -rf obj/*.z
rm -rf obj/*.bin
rm -rf version.c
make[1]: Leaving directory `/pm3/armsrc'
make -C recovery  clean
make[1]: Entering directory `/pm3/recovery'
rm -f bootrom.bin fullimage.bin proxmark3_recovery.bin
make[1]: Leaving directory `/pm3/recovery'
make -C tools/mfkey  clean
make[1]: Entering directory `/pm3/tools/mfkey'
rm -f crypto1.o crapto1.o parity.o util_posix.o mfkey.o mfkey32 mfkey64  mfkey32.exe  mfkey64.exe
make[1]: Leaving directory `/pm3/tools/mfkey'
make -C client  all
make[1]: Entering directory `/pm3/client'
Compiling liblua, using platform mingw
cd ../liblua && make mingw
make[2]: Entering directory `/pm3/liblua'
make "LUA_A=lua52.dll" "LUA_T=lua.exe" \
        "AR=gcc -shared -o" "RANLIB=strip --strip-unneeded" \
        "SYSCFLAGS=-DLUA_BUILD_AS_DLL" "SYSLIBS=" "SYSLDFLAGS=-s" lua.exe
make[3]: Entering directory `/pm3/liblua'
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lua.o lua.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lapi.o lapi.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lcode.o lcode.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lctype.o lctype.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ldebug.o ldebug.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ldo.o ldo.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ldump.o ldump.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lfunc.o lfunc.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lgc.o lgc.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o llex.o llex.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lmem.o lmem.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lobject.o lobject.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lopcodes.o lopcodes.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lparser.o lparser.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lstate.o lstate.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lstring.o lstring.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ltable.o ltable.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ltm.o ltm.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lundump.o lundump.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lvm.o lvm.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lzio.o lzio.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lauxlib.o lauxlib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lbaselib.o lbaselib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lbitlib.o lbitlib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lcorolib.o lcorolib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ldblib.o ldblib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o liolib.o liolib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lmathlib.o lmathlib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o loslib.o loslib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o lstrlib.o lstrlib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o ltablib.o ltablib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o loadlib.o loadlib.c
gcc -O2 -Wall -DLUA_COMPAT_ALL -DLUA_BUILD_AS_DLL    -c -o linit.o linit.c
gcc -shared -o lua52.dll lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lbitlib.o lcorolib.o ldblib.o liolib.o lmathlib.o loslib.o lstrlib.o ltablib.o loadlib.o linit.o
strip --strip-unneeded lua52.dll
gcc -o lua.exe -s  lua.o lua52.dll -lm
make[3]: Leaving directory `/pm3/liblua'
make "LUAC_T=luac.exe" luac.exe
make[3]: Entering directory `/pm3/liblua'
gcc -O2 -Wall -DLUA_COMPAT_ALL     -c -o luac.o luac.c
ar rcu liblua.a lapi.o lcode.o lctype.o ldebug.o ldo.o ldump.o lfunc.o lgc.o llex.o lmem.o lobject.o lopcodes.o lparser.o lstate.o lstring.o ltable.o ltm.o lundump.o lvm.o lzio.o lauxlib.o lbaselib.o lbitlib.o lcorolib.o ldblib.o liolib.o lmathlib.o loslib.o lstrlib.o ltablib.o loadlib.o linit.o
ranlib liblua.a
gcc -o luac.exe   luac.o liblua.a -lm
make[3]: Leaving directory `/pm3/liblua'
make[2]: Leaving directory `/pm3/liblua'
Compiling jansson
cd ./jansson && make all
make[2]: Entering directory `/pm3/client/jansson'
gcc -DHAVE_STDINT_H -I. -O2 -Wall -Wno-unused-variable -Wno-unused-function -c -o dump.o dump.c -lm
In file included from jansson_private.h:16,
                 from dump.c:12:
jansson.h: In function 'json_incref':
jansson.h:124: warning: implicit declaration of function '__atomic_add_fetch'
jansson.h:124: error: '__ATOMIC_ACQUIRE' undeclared (first use in this function)
jansson.h:124: error: (Each undeclared identifier is reported only once
jansson.h:124: error: for each function it appears in.)
jansson.h: In function 'json_decref':
jansson.h:134: warning: implicit declaration of function '__atomic_sub_fetch'
jansson.h:134: error: '__ATOMIC_RELEASE' undeclared (first use in this function)
make[2]: *** [dump.o] Error 1
make[2]: Leaving directory `/pm3/client/jansson'
make[1]: *** [jansson_build] Error 2
make[1]: Leaving directory `/pm3/client'
make: *** [client/all] Error 2`

**Comment by pwpiwi** [comment]
Old version of gcc?

**Comment by Chris-Devine** [comment]
I was using dev enviroment that comes in the .7zip. I fixed it in the end by using "https://github.com/Gator96100/ProxSpace/" enviroment

**Comment by pwpiwi** [comment]
Which .7zip ?

**Comment by Chris-Devine** [comment]
ProxSpace-130613.7z

Its doing it will
"https://github.com/Gator96100/ProxSpace/"

again now :/ so confussed

**Comment by pwpiwi** [comment]
This is from year 2013! Where did you find it?
