### ISSUE TITLE
FIDO U2F authenticator not detected anymore since PR #769

### ISSUE THREAD

**Issue by Fl0-0** [Proxmark/proxmark3#773]
Since PR #769 my NFC FIDO2 is not detected: `FIDO2 version not exists (6700 - Wrong length)`

 ```
FIDO U2F authenricator detected. Version: U2F_V2          
FIDO2 version not exists (6700 - Wrong length). 
```

Reverted to  #437035a75b2737d0b36886bc2bacaeb0219c6325 it works:

```
FIDO U2F authenricator detected. Version: U2F_V2          
FIDO2 version CBOR decoded:          
Map[
  1 (versions): Array[
    U2F_V2
    FIDO_2_0
  ]
  2 (extensions): Array[
    hmac-secret
  ]
...
```

I think the cause  is the changes made in client/fido/fidocore.c .

**Comment by merlokk** [comment]
I'll look.  What authenticator do you have?

**Comment by Fl0-0** [comment]
I use a YubiKey 5 NFC.

**Comment by merlokk** [comment]
works

**Comment by Fl0-0** [comment]
Yes ! Thanks @merlokk
