### ISSUE TITLE
Compile Error - Winscard.h not found

### ISSUE THREAD

**Issue by Axlbuld** [Proxmark/proxmark3#774]
Hi,
cloned today. Compiling on recently installed kali Rolling I get the following error:

pcsc.c:27:10: fatal error: winscard.h: No such file or directory
 #include <winscard.h>
          ^~~~~~~~~~~~
compilation terminated.

Tried to comment the part out, it is missing Reader.h.

Can't find neither of both files in the clones files... Am I missing something here?

**Comment by Fl0-0** [comment]
libpcsclite libraries are missing.

On a debian like system:
`apt install libpcsclite-dev`

Maybe the wiki should be updated too.

**Comment by iceman1001** [comment]
The wiki should be free for everyone to update,   :)    Don't forget the readme, install files aswell :)
The install is also needed on Ubuntu.

**Comment by pwpiwi** [comment]
Correct. And if not already installed you would also need libpcsclite1 and pcscd.

**Comment by Axlbuld** [comment]
Thanks all. Works like a charm.
Thanks for updating the wiki.

**Comment by rahulbajaj0509** [comment]
Does anyone know the fedora/centos equivalent of `pcscd` and `libpcsclite-dev`?

**Comment by Kevin-Nakamoto** [comment]
I have installed the following pcsc packages on my CentOS 7 and it works fine.

$rpm -qa | grep pcsc
pcsc-tools-1.4.25-1.el7.x86_64
pcsc-lite-ccid-1.4.10-15.el7.x86_64
pcsc-perl-1.4.14-2.el7.x86_64
pcsc-lite-libs-1.8.8-8.el7.x86_64
pcsc-lite-devel-1.8.8-8.el7.x86_64
pcsc-lite-1.8.8-8.el7.x86_64

Maybe you can try: 
yum install pcsc-lite pcsc-lite-devel pcsc-tools pcsc-lite-libs

**Comment by WilmerSuarez** [comment]
How can this error be resolved on MAC OS?

**Comment by gmurdocca** [comment]
> I have installed the following pcsc packages on my CentOS 7 and it works fine.
> 
> $rpm -qa | grep pcsc
> pcsc-tools-1.4.25-1.el7.x86_64
> pcsc-lite-ccid-1.4.10-15.el7.x86_64
> pcsc-perl-1.4.14-2.el7.x86_64
> pcsc-lite-libs-1.8.8-8.el7.x86_64
> pcsc-lite-devel-1.8.8-8.el7.x86_64
> pcsc-lite-1.8.8-8.el7.x86_64
> 
> Maybe you can try:
> yum install pcsc-lite pcsc-lite-devel pcsc-tools pcsc-lite-libs

Thankyou, `dnf install pcsc-lite-devel` produced a successful build on Fedora 31

**Comment by totekuh** [comment]
> 
> 
> libpcsclite libraries are missing on your system.
> 
> On a Debian like system: `apt install libpcsclite-dev`
> 
> Maybe the wiki should be updated too. @pwpiwi, @iceman1001 ?

thanks a lot!
