### ISSUE TITLE
Error flashin cdc on unbuntu

### ISSUE THREAD

**Issue by Zer0-Case** [Proxmark/proxmark3#779]
So when i go to do the flashin for cdc it (the specific command is client/flasher /dev/ttyACM0 -b bootrom/obj/bootrom.elf armsrc/obj/fullimage.elf) and it tells me "bash: client/flasher: No such file or directory" and i have no idea why. I tried running the command in the proxmark3 director and outside of it to no avail. I'm sure i'm just making a silly error but i'm really at a lose.

**Comment by pwpiwi** [comment]
Your working directory may not be in your PATH environment. Try `./client/flasher`

**Comment by pwpiwi** [comment]
Can be closed?

**Comment by Zer0-Case** [comment]
No such luck i still get the same error.

**Comment by pwpiwi** [comment]
Most probably this is not an issue with the code. Please check the forum and then ask your question there (http://www.proxmark.org/forum/index.php).
