### ISSUE TITLE
script commands do not take working directory into account

### ISSUE THREAD

**Issue by lesbeben** [Proxmark/proxmark3#79]
Just a small bug I've encountered,

"script list" and "script run" both use relative path "./scripts/" to find scripts to list and/or run. This makes the script command unusable if you run the client from anywhere but the "client" folder.

**Comment by holiman** [comment]
Correct. However, this same problem also affects several other ops, such as eload and a few other iirc. General recommendation is to always run from client folder, but I agree it could be more user friendly in this regars.

**Comment by iceman1001** [comment]
time to close?
