### ISSUE TITLE
what is the "PM3 easy" which is sold in xxxbao.com by lots of seller

### ISSUE THREAD

**Issue by sgf201** [Proxmark/proxmark3#792]
I got a PM3 board named" easy version"which is compatible with firmware of this project. Who knows where could I find the sch file of that version? And better, tell me who made that version

**Comment by pwpiwi** [comment]
This is the Proxmark code repository. Your question is better suited for (and has a bigger audience on) the Proxmark forum http://www.proxmark.org/forum/index.php.
