### ISSUE TITLE
How do I get the value of a t55xx block programatically?

### ISSUE THREAD

**Issue by sgama** [Proxmark/proxmark3#805]
I'm trying to read the values of block programmatically into my code in Appmain.c

How would I do something like this?
```
for (;;) {
		if (usb_poll()){
			rx_len = usb_read(rx, sizeof(UsbCommand));
			if (rx_len)
				UsbPacketReceived(rx, rx_len);
		}
		WDT_HIT();

                int res = T55xxReadBlock(block, value, password)
                Dbprintf("[+] RES %x", res);
```

All I would like to do is to read the value of the block (any block) to operate on.

Unfortunately, I was unable to figure this out on my own. Could someone point me in the right direction?

**Comment by pwpiwi** [comment]
Closed due to double posting in proxmark forum (http://www.proxmark.org/forum/viewtopic.php?id=6364)
