### ISSUE TITLE
LF broken since #803

### ISSUE THREAD

**Issue by Fl0-0** [Proxmark/proxmark3#806]
LF commands are broken since PR #803 .
Tested `lf search, lf t55xx, lf em, lf hid, lf viking` ...

Somethings to do with armsrc changes, i think .

```
proxmark3> lf search
NOTE: some demods output possible binary
  if it finds something that looks like a tag          
False Positives ARE possible
          

Checking for known tags:
          
Waiting for a response from the proxmark...          
You can cancel this operation by pressing the pm3 button 
```

**Comment by pwpiwi** [comment]
Interesting. Didn't touch any LF-related source but broke everything. Please try PR #807.

**Comment by Fl0-0** [comment]
Tested it's OK now,
Thx
