### ISSUE TITLE
Proxmark 3 can't read new iClass 2000 cards

### ISSUE THREAD

**Issue by Supercodegames** [Proxmark/proxmark3#820]
It seems certain variation of iClass 2000 cards (Programmed and Configured, non- ISO ISO14443B, + and = ) cannot be read by the Proxmark3

When trying to read, the  voltage drop when doing `hw tune`, but it returns "no known card found".

Is there a planned fix for this?

![image](https://user-images.githubusercontent.com/15661896/57588834-8d197000-74e8-11e9-8d1e-440795d96270.png)

Threads with this issue:
http://www.proxmark.org/forum/viewtopic.php?id=5307
http://www.proxmark.org/forum/viewtopic.php?id=5798
http://www.proxmark.org/forum/viewtopic.php?id=6223
http://www.proxmark.org/forum/viewtopic.php?id=6311
http://www.proxmark.org/forum/viewtopic.php?id=6144

**Comment by pwpiwi** [comment]
First someone needs to identify the root cause. Only then we can think about a fix.

Looks like no one has a clue up to now.

**Comment by Supercodegames** [comment]
It seems its mainly the new cards with the serial number with a +
The old ones with a * work fine

**Comment by Supercodegames** [comment]
HID surprised the Proxmark community when it quietly refreshed its iClass card.

We all assumed it was a "bug" but its seems its a whole new card card that the proxmark can't read. As of now, the Proxmark only supports the legacy card.

The legacy cards start with a *
The newer cards start with a +

The new mac calculation might be what's causing the issue (don't know for sure though).

**Comment by pwpiwi** [comment]
I thought that iClass uses ISO15693 communication, instead the table talks about ISO14443B? Do we know at all which communication standard is used by the new "+" cards?

**Comment by Supercodegames** [comment]
I think iClass support both, but maybe the + only support ISO15693

**Comment by pwpiwi** [comment]
... but then it should work with the PM3.

**Comment by Supercodegames** [comment]
Updated OP. Its not new cards, it happens by certain programmed and configured card running under this “non-ISO14443B”.  Someone has to figure out the codec...

**Comment by pwpiwi** [comment]
Can you please check if the card responds to an ISO15693 inventory request? Try
```
hf 15 cmd raw -c 26 01 00
hf plot
```
and check the graph. If it contains more than noise, please post it here.

**Comment by pwpiwi** [comment]
any results?

**Comment by vpr1982** [comment]
Hi pwpiwi! 
Since TS had seemingly abandoned this issue here's my result.

Looks like some problem with the command.

proxmark3> hf 15 cmd raw -c 26 01 00
received 0 octets          
          
proxmark3> hf plot
#db# unknown command:: 0x0801          
Waiting for a response from the proxmark...          
You can cancel this operation by pressing the pm3 button

**Comment by marshmellow42** [comment]
It should be 
data plot

**Comment by vpr1982** [comment]
I can tell it should. But that's what it is in my case.

**Comment by pwpiwi** [comment]
It is indeed "hf plot". You have to update your firmware if it is yet unknown.

**Comment by vpr1982** [comment]
proxmark3> hf 15 cmd raw -c 26 01 00
received 0 octets          
          
proxmark3> hf plot
proxmark3> 

Where do I look for the graph?

**Comment by pwpiwi** [comment]
In the graph window. The same window as with 'data plot'.

**Comment by patrickdk77** [comment]
Not sure if this is the same card, the only id is HID iCLASS Px G9P XT, but it doesn't show up in proxmark3 with anything I have done
![Screenshot from 2019-07-18 16:32:00](https://user-images.githubusercontent.com/8078633/61489908-c9020300-a979-11e9-8f42-cb38b4fb8d8e.png)

**Comment by pwpiwi** [comment]
Did you scroll to the right?

**Comment by edlovesiraq** [comment]
Any further work on this? I think i have the same issue. I can see the card under HF tune. writing on the side is HID iCLASS DL, but when I do hf search, or hf iclass reader i get nothing. I tried the commands listed but they don't seem to be the right syntax in the latest build. 
proxmark3> hf 15 cmd raw -c 26 01 00
received 0 octets

proxmark3> hf plot
proxmark3>
I tried in pm3, and tried with proxmark3, no dice either time.  Open to testing this issue please let me know what else I can do. New to the community and hoping to be value added.

**Comment by pwpiwi** [comment]
OK, I am a bit further down the road. Please try latest changes including PR #876. And I stand corrected, the correct commands to check for an iClass ISO15693 card is 
```
hf 15 cmd raw 0c
hf plot
```
and you should see at least the tag response to the right and eventually the reader command or parts of it to the left - if the card answers at all.

You may also try 'hf iclass reader' again. I have improved it a lot. Be aware what is lying on your table because the PM3 now even reads iClass cards lying *beside* the antenna. The RDV4 needs a minimum distance between antenna and card (maybe because of the wild oscillations caused by the high Q antenna - if you look at the plot you know what I mean).

![image](https://user-images.githubusercontent.com/7026004/67239780-43965f00-f450-11e9-8c34-4f859a92072d.png)

**Comment by pwpiwi** [comment]
Again wrong command. Previous post edited. Correct command is
```
hf 15 cmd raw 0a
hf plot
```

**Comment by patrickdk77** [comment]
Sorry, I bricked my proxmark attempting to load this firmware somehow. just got it fixed up.

I'm not seeing any changes in the hf plot on mine but the results of the commands with the PR #876 are:
proxmark3> hf 15 cmd raw 0a
received SOF only. Maybe Picopass/iCLASS?         

proxmark3> hf iclass reader
   CSN: b8 c4 7c 0f ff ff 12 e0           
    CC: ff ff ff ff 63 ff ff ff           
  Mode: Application [Locked]          
Coding: ISO 14443-2 B/ISO 15693          
 Crypt: Secured page, keys not locked          
    RA: Read access not enabled          
   Mem: 16 KBits/16 App Areas (255 * 8 bytes) [1F]          
   AA1: blocks 06-12          
   AA2: blocks 13-FF          
 AppIA: ff ff ff ff ff ff ff ff           
      : Possible iClass (legacy tag)          
   CSN: b8 c4 7c 0f ff ff 12 e0           
    CC: ff ff ff ff 63 ff ff ff           
  Mode: Application [Locked]          
Coding: ISO 14443-2 B/ISO 15693          
 Crypt: Secured page, keys not locked          
    RA: Read access not enabled          
   Mem: 16 KBits/16 App Areas (255 * 8 bytes) [1F]          
   AA1: blocks 06-12          
   AA2: blocks 13-FF          
 AppIA: ff ff ff ff ff ff ff ff           
      : Possible iClass (legacy tag)

**Comment by pwpiwi** [comment]
This looks pretty much like a standard legacy iClass card. I am wondering why this should have created issues?

**Comment by aaronmaxlevy** [comment]
@pwpiwi HID is no longer using PicoPass chips for iCLASS, as they have been discontinued. If you take a look at the chip in a current card, it looks like something custom from NXP, likely running a “PicoPass Emulator” of sorts from HID. My guess is perhaps there are differences in timing, etc. Between those and real PicoPass cards.

**Comment by patrickdk77** [comment]
My issue might be unrelated, but when I initially looked up the issue I had, it seemed like this was related.
My card says on it
HID iCLASS Px G9P XT
I can read the hid lf part fine, but have not been able to read the iclass part of the card.

**Comment by pwpiwi** [comment]
I am not sure about the current status of this issue and if it can be closed. @patrickdk77: you report "have not been able to read the iclass part of the card" but shows a perfect read two posts above. Does it mean that the issue is fixed for you?

Any feedback from @Supercodegames, @vpr1982 or @edlovesiraq ?

**Comment by steve-embling** [comment]
So I also have a card that suffers from this and can confirm that this patch (for me at least) fixes
```
hf search
```
and 
```
hf iclass readblk
```
But I haven't had a chance to confirm other read commands or writing yet.

**Comment by steve-embling** [comment]
@pwpiwi In response to the other thread, I did have a card that could not be read with proxmark (0/20 hf search detected the card) to one that reliably reads (10/10) on the same card, after updating to the version given here.

I can't say for sure my issue was the same as the original poster, but it looks to be closed to me as the scope of this issue only covered reading of the cards.

Also - thank you for all the work on this.

**Comment by vpr1982** [comment]
This patch fixes this problem. New issue #907
