### ISSUE TITLE
RDV4 - smartcard reader absent

### ISSUE THREAD

**Issue by KarlLovink** [Proxmark/proxmark3#825]
I have connected the smartcard reader to my proxmark3 RDV4. 
The proxmark3 cannot find the smartcard reader for some reader.

Any idea what could be wrong?

hw version output:
 [ Proxmark3 RFID instrument ] 
          

 [ CLIENT ]          
  client: RRG/Iceman          

 [ PROXMARK RDV4 ]          
  external flash:                  present           
  smartcard reader:                absent           

 [ PROXMARK RDV4 Extras ]          
  FPC USART for BT add-on support: present           
          
 [ ARM ]
 bootrom: RRG/Iceman/master/48621159 2019-05-22 15:05:30
      os: RRG/Iceman/master/48621159-dirty-unclean 2019-05-22 20:52:36

 [ FPGA ]
 LF image built for 2s30vq100 on 2019/ 5/22 at 15: 6: 9
 HF image built for 2s30vq100 on 2019/ 5/22 at 15: 6:26          

 [ Hardware ]           
  --= uC: AT91SAM7S512 Rev B          
  --= Embedded Processor: ARM7TDMI          
  --= Nonvolatile Program Memory Size: 512K bytes, Used: 250825 bytes (48%) Free: 273463 bytes (52%)          
  --= Second Nonvolatile Program Memory Size: None          
  --= Internal SRAM Size: 64K bytes          
  --= Architecture Identifier: AT91SAM7Sxx Series          
  --= Nonvolatile Program Memory Type: Embedded Flash Memory

**Comment by pwpiwi** [comment]
You are using the RRG software and therefore you should open your issue on the RRG repository: https://github.com/RfidResearchGroup/proxmark3/issues
