### ISSUE TITLE
Need help buying this product?

### ISSUE THREAD

**Issue by cefedrific** [Proxmark/proxmark3#831]
Hello all I would like to work on this product so I need advice from someone I know he already knows.
My question is the following then I buy this product saying that I made the right choice report quality price?

Proxmark3 V2.0 Kits RFID Clone Programmer Copy Reader Writer Card Duplicator UID T5577 NFC Clone Proxmark 3 Crack

https://www.aliexpress.com/item/Newest-Update-Proxmark-3-RDV2-0-Kits-RFID-NFC/32398951956.html

Thanks.

**Comment by pwpiwi** [comment]
Better ask this question in the forum (http://www.proxmark.org/forum/index.php). You will reach much more people there. This here is the github software repository and is the place to report issues with the software.
