### ISSUE TITLE
PM3 SRX4K don't write anymore

### ISSUE THREAD

**Issue by badtime** [Proxmark/proxmark3#835]
Hi, i have some trouble with my PM3 RDV2 anc SRX4K writing.

So, if I use this old firmware firmware:

Prox/RFID mark3 RFID instrument
bootrom: master-rysc/v3.0.1 2017-09-21 19:05:39
os: master-rysc/v3.0.1 2017-09-21 19:05:45
LF FPGA image built for 2s30vq100 on 2015/03/06 at 07:38:04
HF FPGA image built for 2s30vq100 on 2017/05/17 at 17:48:26

uC: AT91SAM7S512 Rev B
Embedded Processor: ARM7TDMI
Nonvolatile Program Memory Size: 512K bytes. Used: 192390 bytes (37%). Free: 331898 bytes (63%).
Second Nonvolatile Program Memory Size: None
Internal SRAM Size: 64K bytes
Architecture Identifier: AT91SAM7Sxx Series
Nonvolatile Program Memory Type: Embedded Flash Memory
 
I can write SRX4K without problems, but if i upgrade at the lastest firmware version from this git, i can't anymore 

when I do : hf 14b sriwrite 1 7f 11223344 (for example), the system give me back
[SRIX4K] Write block 7F [ 11 22 33 44  ]
received 0 octets

but when i read the TAG....nothing change at block 7F.

This issue is client indipendent and OS indipendent, i have tried many combinations, but is a firmware trouble.

What's wrong?

**Comment by pwpiwi** [comment]
Interesting finding. The 'hf 14b sriwrite 1 7f 11223344' is realized as a 'hf 14b raw -c 09 7f 11223344'. I would say that the issue is the lack of a card select before the write command.  But there never had been a select in the code. Why did it ever work then? What do I miss?
