### ISSUE TITLE
PM3 emulating Mifare UL version is always 0's

### ISSUE THREAD

**Issue by hornyd** [Proxmark/proxmark3#836]
Using the latest PM3 and PM firmware 
[ FPGA ]
 LF image built for 2s30vq100 on 2019/ 4/18 at  9:35:32
 HF image built for 2s30vq100 on 2018/ 9/ 3 at 21:40:23

I am trying to emulate Mifare Ultralight. I read first the Ultralight card to get the JSON file with the content

{
  "Created": "proxmark3",
  "FileType": "mfu",
  "Card": {
    "UID": "04472F9A795981",
    "Version": "0004030101000B03",
    "TBO_0": "0000",
    "TBO_1": "00",
    "Signature": "72E57914C4ACDD2C8C96008BA0B76477E7E62F2477A87F696823533D935A8BD8",
    "Counter0": "000000",
    "Tearing0": "BD",
    "Counter1": "000000",
    "Tearing1": "BD",
    "Counter2": "000000",
    "Tearing2": "BD"
  },
  "blocks": {
    "0": "04472FE4",
    "1": "9A795981",
    "2": "3B4800F0",
    "3": "BFEBFFFF",
    "4": "C8002001",
    "5": "300541D0",
..

When I first load the image to the memory
hf mfu eload u hf-mfu-04472F9A795981-dump-4.eml

then enable the sniff  hf 14a sniff

then emulate the card hf mfu sim t 2 u 04472F9A795981

When I read the emulated card with a contactless reader:
- EV1 version is Always 00
34843976 |   34847592 | Rdr |60  f8  32                        |  ok | EV1 VERSION
34848764 |   34860348 | Tag |00  00  00  00  00  00  00  00  3a  55                |  ok | 

but I was expecting 00 04 03 01 01 00 0B 03

Any suggestion?

**Comment by pwpiwi** [comment]
You are most probably using a software which is not from this repository. Please report your issue in the correct repository (https://github.com/RfidResearchGroup/proxmark3/issues ?).
