### ISSUE TITLE
cloning my 4k /2k tag error

### ISSUE THREAD

**Issue by pittihomme** [Proxmark/proxmark3#854]
Hi guys 

I just received my 4k writable tags and i just did a try to copy my dump on it . 

As we spoke about it , there are 18 sectors on my tag and 1 is not readeable at all even if i have the keys . 

I did a try to restore my dump / keys but i have an error with the dump 

Writing to block  63: 48 45 58 41 43 54 07 87 8f 00 a6 ca c2 88 64 12           
#db# Authentication failed. Card timeout.          
#db# Auth error          
#db# WRITE BLOCK FINISHED          
isOk:00          
File reading error (dumpdata.bin).   

The writable tag has not magic chinese backdoor . ( the seller told me it was illegal? )

Anyway i'm stuck ...

**Comment by pwpiwi** [comment]
Please post this question to the forum. This is not a code issue.
