### ISSUE TITLE
Flasher program do not flashing the firmware on linux

### ISSUE THREAD

**Issue by assasinfil** [Proxmark/proxmark3#857]
Bootloader normally flash, but firmware didn't flash. The firmware program freezes during the firmware upgrade, as proxmark restarts and is assigned a different com port. Such a problem is observed only under Linux.

**Comment by iceman1001** [comment]
kill modem manager....

**Comment by pwpiwi** [comment]
... or press the PM3 button. This question has been asked and answered many times in the forum. Reading the Wiki helps too.

**Comment by assasinfil** [comment]
Pressing the button does not help, I will try with the modem, thanks.
