### ISSUE TITLE
Proxmark III "getting started guide" devkitARM

### ISSUE THREAD

**Issue by Leseratte10** [Proxmark/proxmark3#871]
Hello, 

this github issue is not strictly related to this repository but I hope someone will be able to help me anyways

I found on the internet the "Proxmark III getting started guide"
https://initrd.net/stuff/proxmark3/doc/Proxmark%20III%20-%20Ubuntu%20GSG%20v1.pdf

That guide mentions devkitARM and that it needs to be installed in version "release 32". Unfortunately, the link to this version is down, and I need exactly this version for another project of mine (unrelated to proxmark). I searched your forum and wiki, and found this old revision of a wiki page where it says you need devkitARM r41 (but the download link is dead as well): 
https://github.com/Proxmark/proxmark3/wiki/Ubuntu-Linux/1c06bcc8487e76eb4285096dcec17e42922af61c

I looked through the forum and found various mentions that devkitARM is required (or isn't required in some cases, I guess that's why it was removed from the github wiki page), but I was unable to find a working download link and I really need that version of devkitARM (r32). 

Does anyone of the proxmark3 team still happen to have a working download link for devkitARM_r32-i686-linux.tar.bz2? If not, does anyone have a working link for any other version? Maybe I can get it to work with some other older version as well, but it doesn't work with the versions that are currently available for download from the devkitPro team.

I really need that old r32, and the PDF file I found is the only hit on Google that contains any information about that, so I'm hoping anyone reading this issue report will be able to help me. 
I'm sorry for using this bugtracker for a request that has nothing to do with proxmark3 itself, but the mail address on the webpage (http://www.proxmark.org/) wasn't working (I received a "Undelivered Mail returned to sender" error mail) and I wasn't sure how to best contact you. 

(This current situation aside, I am maintaining an archive of all devkitARM / devkitPro versions I could ever find at https://wii.leseratte10.de/devkitPro/devkitARM/ , but most of the old versions are only Windows builds. Maybe some of this will be helpful for you at some point, and I would be glad if you could help me complete this as well if you have any versions that aren't in there yet).

Best regards, 
Leseratte10

**Comment by RfidResearchGroup** [comment]
Wayback the proxmark repo was hosted on Google code.  You find it still here
https://code.google.com/archive/p/proxmark3/downloads

If you are extremely lucky you might find the devKitARM that you are looking for in one of the old proxspace zipfiles.
like this one.
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/proxmark3/ProxSpace-20100226-r390.7z

**Comment by Leseratte10** [comment]
Thanks a lot for your reply, I really appreciate the help. I downloaded all the archives from google code and looked through them, but sadly I was only able to find some windows binaries of devkitARM in there, no linux ones. I'm hoping that one of the developers might still have the original archive somewhere on their computer from when it was required ...

**Comment by RfidResearchGroup** [comment]
Proxspace is mingw setup.  And I have no idea whom actually put it together the first time.
@Gator96100  does maintain the most updated proxspace versions.  He might have an old archive laying around but I wouldn't count on it.

Happy huntin'

**Comment by Gator96100** [comment]
I only have Windows binaries of devkitARM. For the proxmark firmware devkitARM was only used on Windows, so I doubt anyone here has the linux binaries.

**Comment by Leseratte10** [comment]
Well in the "proxmark 3 Ubuntu getting starting guide" it mentions the need to download the linux version so it looks like at some point it was used on Linux as well.
