### ISSUE TITLE
Broken after upgradig Proxmark3 to CDC Bootloader

### ISSUE THREAD

**Issue by bobby-2019** [Proxmark/proxmark3#877]
After following instructions to upgrade Proxmark 3 to CDC Bootloader, I am not able to connect to the device it is not detectable. Both A and C red light on the Proxmark3 are permanently on when connected however Kali Linux is not able to detect the USB device. 
-https://github.com/Proxmark/proxmark3/wiki/Kali-Linux 

During the upgrade, I did not received any error as you can see below. Looking forward in receiving your advise, many thanks. 
![proxmark3_upgrade_cdc](https://user-images.githubusercontent.com/56905196/67356429-e0b6dc00-f5a5-11e9-803c-f5c85e4f64e1.PNG)

**Comment by pwpiwi** [comment]
LED A and C are switched on by the bootloader. So your Proxmark isn't broken and still starting the bootloader. But it cannot start the firmware.

Read about the modem manager issue in the Wiki and on the forum.

Then try the following: 
* disconnect the PM3
* press the button on the PM3 and keep it pressed.
* connect the PM3 to the USB port. Keep the button pressed.
* Check with `dmesg | grep -i usb` if your PC now recognises the PM3 and which USB-Port it uses. Keep the button pressed
* Flash the firmware (not the bootrom again). Keep the button pressed.
* Release the button after flashing is completed.

**Comment by bobby-2019** [comment]
Many thanks for your assistance, PM3 is back online :)
