### ISSUE TITLE
SRI512, SRX4k sriwrite code issue 

### ISSUE THREAD

**Issue by Antho59** [Proxmark/proxmark3#878]
Hello,

I've opened a new issue cause the last one about sriwrite started to be a bit too old and didn't know if it was still followed.

I faced the same isssue for a 14443-3b SRI512 tag when trying to write via "sriwrite" function

I managed to write on the tag manually using "raw" command, because it seems "cmdhf14braw" function in "cmdhf14b.c" file does not manage the WRITE_BLOCK sequence request.

Regarding the doc, it says that before being able to write on a block, the tag have to receive a SELECT request (0e), but the "-s" option in the code do a REQB request (05) for sri512, and an INITIATE request (06 00) for SRX tag.
 
But to successfuly perform an SELECT request, we have to know the CHIP_ID (2nd byte parameter of the SELECT request -> 0e [chid_id] )

Here the tricky part comes, some SRI512 and SRX tags use random Chip ID (some others have a fixed one, depend on tags configuration)
This CHIP_ID is obtained in the tag reply after an INITIATE request, once obtained, we can perform the SELECT request, and then the WRITE_BLOCK command. 

More precisely:
To be able to write on a SRI512, SRT512 or SRX tag, we need to:
1- Perform an INITIATE command (First byte of the tag reply is the [CHIP_ID] )
2- Perform a SELECT command using [CHIP_ID] value obtained before
3- Then perform your WRITE_BLOCK command

Below a sequence exemple:
1- hf 14b raw -c -p 06 00       (initiate command [06 00] with auto CRC calculation and append)
---> Tag reply: 64 5a d5         (64 = chip_id)

2- hf 14b raw -c -p 0e 64 (select command [0e xx] where "xx" = chip_id, here 64)
---> Tag reply : 64 5a d5

3- hf 14b raw -c -p 09 05 11 10 00 11 (write_block command)
--> Regarding documentation, tags do not reply to write_request, so "received 0 octets" is normal

4- Write is performed successfuly

Can someone update the code in order to make sriwrite function, or at least raw "-s" option to handle this ?

Thanks a lot for your work

PS: For those who can't successfuly write on block 05 and 06, it's because regarding the datasheet, those blocks are "counter down block", that means only lower value will be accepted by the chip (chip logic security).

**Comment by pwpiwi** [comment]
The `-ss` (instead of `-s`) option in `hf 14b raw` should exactly do what you describe (initiate, then select). Can you please confirm?

**Comment by Antho59** [comment]
Hello,

Thanks for your reply.

-ss seems to do first a initiate then a select but only for SRx tag and not SRI, i own an SRI which have the same write_block sequence.

**Comment by pwpiwi** [comment]
Is there a difference in the initiate/select sequence for SRI and SRIx?

**Comment by Antho59** [comment]
no the initiate and select sequence required before a write_block command are the same for both SRI512 SRx (and SRT512)

**Comment by pwpiwi** [comment]
So why would `-ss` not work for you?

**Comment by pwpiwi** [comment]
There is no autodetect.
`-s` always sends REQB/ATTRIB (05 00 08 / 1D \<UID\> 00 08 01 00)
`-ss` always sends INITIATE/SELECT (06 00 /  0E \<chipID\>)
(all with additional CRC)

**Comment by pwpiwi** [comment]
OK, found the issue. Will fix tomorrow morning.

**Comment by pwpiwi** [comment]
Please test PR #880. This should fix both `hf 14b sriwrite` and `hf 14b raw -ss`

**Comment by Antho59** [comment]
thanks, i'll test it on Tuesday and come back to you

**Comment by Antho59** [comment]
Hello,

I've tested your PR #880 and now it's working fine:

hf 14b raw -ss -c 09 [block] [data] result:
