### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by LorenzoAlluminio** [Proxmark/proxmark3#882]
Hi,
I'm trying to compile the source code on ubuntu 16.04, I followed all the steps into the wiki but the makefile fails with this error.
`iso15693.c: In function 'SetTag15693Uid':
iso15693.c:1695:2: error: missing braces around initializer [-Werror=missing-braces]
  uint8_t cmd[4][9] = {0x00};
  ^
iso15693.c:1695:2: error: (near initialization for 'cmd[0]') [-Werror=missing-braces]
cc1: all warnings being treated as errors
`
The executable in proxmark3/client seems to work though.
Any idea of why?

**Comment by pwpiwi** [comment]
Which compiler version do you use? Please run
`arm-none-eabi-gcc --version`

**Comment by LorenzoAlluminio** [comment]
This is the output:
`arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

**Comment by pwpiwi** [comment]
Hmmm, prerelease anno 2015. I suggest that you upgrade to a newer version.

**Comment by LorenzoAlluminio** [comment]
Updated, but now it fails like this:
`make[1]: uscita dalla directory "/home/allu/proxmark3/client"
make -C bootrom  all
make[1]: ingresso nella directory "/home/allu/proxmark3/bootrom"
arm-none-eabi-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
arm-none-eabi-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
arm-none-eabi-gcc: fatal error: cannot execute 'cc1': execvp: No such file or directory
compilation terminated.
`

**Comment by LorenzoAlluminio** [comment]
I tried to update it but I couldn't do it, it still gave me errors, but I managed to install correctly the Iceman fork. Thanks for the help anyway, really appreciated

**Comment by LorenzoAlluminio** [comment]
I tried also with this fix and It solves my problem! Thanks!
