### ISSUE TITLE
About HF snoop

### ISSUE THREAD

**Issue by ewangsoft** [Proxmark/proxmark3#885]
proxmark3> hf snoop
#db# Buffer cleared (40000 bytes)
#db# Skipping first 0 sample pairs, Skipping 0 triggers.

#db# Trigger kicked! Value: 255, Dumping Samples Hispeed now.
#db# HF Snoop end

Why can't I eavesdrop data

**Comment by pwpiwi** [comment]
You probably did. Use 'data plot' to see the result.

**Comment by ewangsoft** [comment]
> You probably did. Use 'data plot' to see the result.

Use 'data plot'，It's empty.

**Comment by pwpiwi** [comment]
What do you mean with "empty"? Obviously there had been a trigger value. At least this one should be visible in 'data plot'.
Maybe it helps if you describe what you are trying to achieve, how you are trying to achieve it, and which commands you are using. And please post the results.

**Comment by ewangsoft** [comment]
> What do you mean with "empty"? Obviously there had been a trigger value. At least this one should be visible in 'data plot'.
> Maybe it helps if you describe what you are trying to achieve, how you are trying to achieve it, and which commands you are using. And please post the results.

I used to snoop data between PCD and PICC with “hf 14a snoop", but I couldn't snoop PCD data. I thought it might be that PCD didn't conforming to 14443a standard , so I wanted to snoop PCD data with ”hf snoop",but I can't snoop the data.

I'm Chinese, I can't speak English. I translate it with translation software. I'm sorry.

**Comment by pwpiwi** [comment]
If you see iso14443a PICC responses then definitely there had been iso14443a PCD requests. You need to change antenna position and distances until you see both PCD and PICC data after 'hf 14a snoop'.
