### ISSUE TITLE
Bricked Proxmark3 rdv4 - can't fix!

### ISSUE THREAD

**Issue by jp50pr** [Proxmark/proxmark3#891]
I have a Proxmark3 rdv 4 I bricked...well because I have no idea what I am doing. I purchased a j-link EDU, I also purchased the lab 401 adapter. I thought I followed the guide on how to fix it but I keep getting an error.
Any assistance would be greatly appreciated. 

![Screen Shot 2019-12-02 at 6 58 10 PM](https://user-images.githubusercontent.com/6788104/70005076-4ea3db00-1536-11ea-961e-385b45a9de7b.png)

**Comment by merlokk** [comment]
Looks like you don't connect jtag correctly. One of errors - it can't see vcc voltage

**Comment by iceman1001** [comment]
Did you follow these instructions?  https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/jtag_notes.md   I see your jtag configured for AT91SAM7S256 ,  where RDV4 uses AT91SAM7S512

**Comment by pwpiwi** [comment]
> I have no idea what I am doing

In such a case you should stop and breath slowly instead of connecting wires randomly. What makes you think that your proxmark is bricked? What do you observe when you connect it to your PC? LEDs?

**Comment by jp50pr** [comment]
Sorry I could not get it all in the picture. The reason I think it is bricked it because my system does not recognize it and all lights turn on when there is power.

I am using the adapter to "avoid" wiring issues.

![Screen Shot 2019-12-03 at 9 18 33 AM](https://user-images.githubusercontent.com/6788104/70059198-58692500-15ae-11ea-9861-46586a2574dc.png)

**Comment by jp50pr** [comment]
I used https://github.com/Proxmark/proxmark3/wiki/De-Bricking-Segger for the guide, which is where I saw "exec device = AT91SAM7S256". I did just try using "exec device = AT91SAM7S512" but no luck still.

**Comment by iceman1001** [comment]
I recommend you use the jtag instructions I linked.

**Comment by jp50pr** [comment]
Thank you all for the help and responses. Iceman1001, I used your recommendation and used the guide provided. I appreciate the help. Now that it is no longer bricked time to get this guy working again.
