### ISSUE TITLE
proxmark3 driver is not installed

### ISSUE THREAD

**Issue by riseemsi** [Proxmark/proxmark3#893]
driver is not installed
 Hello, I did everything as indicated in your installation instructions, I can’t install the driver, no matter how I try, help solve the problem
![Безымянный123](https://user-images.githubusercontent.com/58441257/70079659-3905e280-1616-11ea-8b02-98ec13e26500.png)
![Безымянный12323](https://user-images.githubusercontent.com/58441257/70079661-3905e280-1616-11ea-94cb-cf129b82f794.png)

**Comment by riseemsi** [comment]
proxmark3 V3.0 Easy ELECHOUSE/ windows 7x64

**Comment by pwpiwi** [comment]
Can you translate to English please?
