### ISSUE TITLE
wrong dictionary path

### ISSUE THREAD

**Issue by mashrum** [Proxmark/proxmark3#897]
[usb] pm3 --> hf mf fchk 1 **mfc_default_keys.dic**
[+] Loaded 865 keys from mfc_default_keys.dic           
[+] Running strategy 1          
....          

---- but ----

[usb] pm3 --> hf mf autopwn f **mfc_default_keys.dic**
[!] no known key was supplied, key recovery might fail          
[+] loaded  0 keys from dictionary file **/usr/local/Cellar/proxmark3/HEAD-5773919/bin/../share/proxmark3/dictionaries/mfc_default_keys.dic           
[-] An error occurred while loading the dictionary! (we will use the default keys now)**          
[+] loaded 23 keys from hardcoded default array          
[=] running strategy 1

**Comment by pwpiwi** [comment]
You are using RRG repo. You need to raise your issues there: https://github.com/RfidResearchGroup
