### ISSUE TITLE
proxmark on ubuntu 18.04 64bit error by CLOCK_REALTIME

### ISSUE THREAD

**Issue by linux0ne-su** [Proxmark/proxmark3#924]
comms.c: In function ‘getCommand’:
comms.c:152:17: error: storage size of ‘tv’ isn’t known
  struct timeval tv;
                 ^~
comms.c:153:2: warning: implicit declaration of function ‘gettimeofday’ [-Wimplicit-function-declaration]
  gettimeofday(&tv,NULL);
  ^~~~~~~~~~~~
comms.c:152:17: warning: unused variable ‘tv’ [-Wunused-variable]
  struct timeval tv;
                 ^~
Makefile:348: recipe for target 'obj/comms.o' failed
make[1]: *** [obj/comms.o] Error 1
make[1]: 离开目录“/home/ooooo/proxmark3/client”
Makefile:33: recipe for target 'client/all' failed
make: *** [client/all] Error 2
.......

我按照#917的方法进行了源代码更改，但是在make的时候，还是出现了上方的错误。我的代码更改如下：

// Code for communicating with the proxmark3 hardware.
//-----------------------------------------------------------------------------

#define _POSIX_C_SOURCE 199309L // need clock_gettime()

#include "comms.h"

#include <stdio.h>
@@ -145,14 +147,7 @@ static void storeCommand(UsbCommand *command) {
static int getCommand(UsbCommand* response, uint32_t ms_timeout) {

	struct timespec end_time;
#if (_POSIX_TIMERS > 0)
	clock_gettime(CLOCK_REALTIME, &end_time);
#else
	struct timeval tv; ---------------------------->why ??????
	gettimeofday(&tv, NULL);
	end_time.tv_sec = tv.tv_sec;
	end_time.tv_nsec = tv.tv_usec * 1000;
#endif
	end_time.tv_sec += ms_timeout / 1000;
	end_time.tv_nsec += (ms_timeout % 1000) * 1000000;
	if (end_time.tv_nsec > 1000000000) {

**Comment by linux0ne-su** [comment]
是因为变量tv没有声明么？

**Comment by pwpiwi** [comment]
Did you try the fix in PR #917 ?

**Comment by linux0ne-su** [comment]
@pwpiwi 
Yes.  This is how I operate.
Detailed steps ：
Add the following code to the commas.c file, save and compile.

-----------------------------code----------------------------------------------------
#define _POSIX_C_SOURCE 199309L // need clock_gettime()

#include "comms.h"

#include <stdio.h>

static int getCommand(UsbCommand response, uint32_t ms_timeout) {

struct timespec end_time;
#if (_POSIX_TIMERS > 0)
clock_gettime(CLOCK_REALTIME, &end_time);
#else
struct timeval tv;
gettimeofday(&tv, NULL);
end_time.tv_sec = tv.tv_sec;
end_time.tv_nsec = tv.tv_usec * 1000;
#endif
end_time.tv_sec += ms_timeout / 1000;
end_time.tv_nsec += (ms_timeout % 1000) * 1000000;
if (end_time.tv_nsec > 1000000000) {
...........

**Comment by pwpiwi** [comment]
No, This doesn't reflect the latest commit in PR #917.  

Just add
```
#define _POSIX_C_SOURCE 199309L // need clock_gettime()
```
and
```
include <sys/time.h>
```

**Comment by linux0ne-su** [comment]
https://github.com/Proxmark/proxmark3/pull/917/commits/9dd8c2af44dc79101c4fc07ced60c38e76e25045#

我是按照上方链接的代码进行更改的。

![a](https://user-images.githubusercontent.com/60182556/77907215-d36fed00-72bb-11ea-8b7b-00bf5878f1c3.png)
![b](https://user-images.githubusercontent.com/60182556/77907232-dbc82800-72bb-11ea-933f-ec9832e84643.png)

**Comment by pwpiwi** [comment]
Green lines have to be added, and red lines to be removed. In this case this reverts the changes made in the first commit of the PR. Select "Files changed" to see the final files after applying all commits:

![image](https://user-images.githubusercontent.com/7026004/77908620-2467ed00-728c-11ea-8150-7320efc0c4cf.png)

Or even better: create a separate branch in your local repository and pull the PR:
```
git checkout -b pwpiwi-fix_get_clocktime master
git pull https://github.com/pwpiwi/proxmark3.git fix_get_clocktime
```

**Comment by linux0ne-su** [comment]
Thank you. You've been a great help already.
I will compile the latest code tomorrow evening.

git checkout -b pwpiwi-fix_get_clocktime master
git pull https://github.com/pwpiwi/proxmark3.git fix_get_clocktime

There is no computer by my side now.

If there is still a problem, I'll ask you again.

Thank you so.....

**Comment by pwpiwi** [comment]
> If there is still a problem, I'll ask you again.

If this fixes the problem, please tell us too.

**Comment by pwpiwi** [comment]
Taking no feedback as positive feedback. Merged #917.

**Comment by linux0ne-su** [comment]
非常抱歉，我最近一段工作特别忙，没有及时回复您，抱歉！

1、我回到电脑前，我按照您的方式调整了代码，即将被标注为绿色的代码添加到comms.c文件中，将标注为红色的代码从comms.c文件中删除。

2、但，即使是这样做了之后，还是提示错误，如图所示。

![2020-04-08-220314_1052x380_scrot](https://user-images.githubusercontent.com/60182556/78793317-d027e000-79e4-11ea-8bfc-549cbf5255e4.png)


3、因为中国网络的原因，我们访问github.com网站的时候非常的慢，下载源代码也非常的慢，并且因为我之前更改了已下载好的proxmark3代码，所以在使用git pull --rebase的时候，就显示不成功。也就是说，您如果因为我的提问，而回归代码到最初的状态的话，那因为网络的原因，导致我不能下载这个更新后的源码。

**Comment by linux0ne-su** [comment]
![2020-04-08-220422_455x368_scrot](https://user-images.githubusercontent.com/60182556/78793421-f9487080-79e4-11ea-9319-4928624e3691.png)


![2020-04-08-220441_643x399_scrot](https://user-images.githubusercontent.com/60182556/78793427-fc436100-79e4-11ea-9dcd-9affad6532ff.png)

**Comment by pwpiwi** [comment]
There is no need to download all source code again. Just do `git pull` on master branch. It will only download the differences.

**Comment by linux0ne-su** [comment]
(base) ooooo@Guo-desktop:~/proxmark3/client$ git pull --rebase
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 8 (delta 2), reused 6 (delta 2), pack-reused 0
展开对象中: 100% (8/8), 完成.
来自 https://github.com/Proxmark/proxmark3
   5bc3841..c85805b  master     -> origin/master
更新 5bc3841..c85805b
Fast-forward
 CI/.travis.yml | 27 ++++++++++++++++-----------
 client/comms.c |  3 +++
 2 files changed, 19 insertions(+), 11 deletions(-)
当前分支 master 是最新的。
(base) ooooo@Guo-desktop:~/proxmark3/client$ 


------------------------------------------------------------------------------------------------------
make clean  && make
.........
pcsc.c:27:10: fatal error: winscard.h: 没有那个文件或目录
 #include <winscard.h>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:348: recipe for target 'obj/pcsc.o' failed
make[1]: *** [obj/pcsc.o] Error 1
make[1]: 离开目录“/home/ooooo/proxmark3/client”
Makefile:33: recipe for target 'client/all' failed
make: *** [client/all] Error 2
(base) ooooo@Guo-desktop:~/proxmark3$

**Comment by linux0ne-su** [comment]
sudo apt-get install libpcsclite-dev

make clean && make
........

make[1]: 离开目录“/home/ooooo/proxmark3/armsrc”
make -C recovery  all
make[1]: 进入目录“/home/ooooo/proxmark3/recovery”
arm-none-eabi-objcopy --gap-fill=0xff --pad-to 0x00102000 -O binary ../bootrom/obj/bootrom.elf bootrom.bin
arm-none-eabi-objcopy --gap-fill=0xff -O binary ../armsrc/obj/fullimage.elf fullimage.bin
cat bootrom.bin fullimage.bin > proxmark3_recovery.bin
make[1]: 离开目录“/home/ooooo/proxmark3/recovery”
make -C tools/mfkey  all
make[1]: 进入目录“/home/ooooo/proxmark3/tools/mfkey”
gcc -std=c99 -D_ISOC99_SOURCE -I../../include -I../../common -I../../client -Wall -O3 -c -o crypto1.o ../../common/crapto1/crypto1.c
gcc -std=c99 -D_ISOC99_SOURCE -I../../include -I../../common -I../../client -Wall -O3 -c -o crapto1.o ../../common/crapto1/crapto1.c
gcc -std=c99 -D_ISOC99_SOURCE -I../../include -I../../common -I../../client -Wall -O3 -c -o parity.o ../../common/parity.c
gcc -std=c99 -D_ISOC99_SOURCE -I../../include -I../../common -I../../client -Wall -O3 -c -o util_posix.o ../../client/util_posix.c
gcc -std=c99 -D_ISOC99_SOURCE -I../../include -I../../common -I../../client -Wall -O3 -c -o mfkey.o ../../client/mifare/mfkey.c
gcc -std=c99 -D_ISOC99_SOURCE -I../../include -I../../common -I../../client -Wall -O3  -o mfkey32 crypto1.o crapto1.o parity.o util_posix.o mfkey.o mfkey32.c
gcc -std=c99 -D_ISOC99_SOURCE -I../../include -I../../common -I../../client -Wall -O3  -o mfkey64 crypto1.o crapto1.o parity.o util_posix.o mfkey.o mfkey64.c
make[1]: 离开目录“/home/ooooo/proxmark3/tools/mfkey”



ok 
done

think you  very very very..........
