### ISSUE TITLE
Can't update Bootloader

### ISSUE THREAD

**Issue by thunderbuns** [Proxmark/proxmark3#927]
When trying to run the 'pm3-flash-all' command during the initial setup, I encountered the error shown below: 
![issue with proxmark 3](https://user-images.githubusercontent.com/24836546/78276202-6def5b00-755e-11ea-9668-7711a2554f62.JPG)

Researching this issue led me to [this](http://www.proxmark.org/forum/viewtopic.php?id=6706) page. However, the suggested action to update the bootloader was to run the following command: 'client/flasher /dev/ttyACM0 -b bootrom/obj/bootrom.elf' This command cannot be run as there is no flasher file contained anywhere within the project. As such, the issue lies within the installation instructions and the necessity for them to be updated. It should be noted that I am operating with root privileges and have already run the 'make clean && make all' and the 'make install' commands.

Is there something that I am missing or does the issue lie in the documentation?

**Comment by iceman1001** [comment]
This is not a question for the offical repo.  

```
./pm3-flash-bootrom
if, ok,
./pm3-flash-fullimage
```

**Comment by thunderbuns** [comment]
For starters, thanks for the speedy response. Your instructions worked perfectly and everything flashed completely fine. As a side note, I was following the guide on the Github page [(link)](https://github.com/RfidResearchGroup/proxmark3/blob/master/doc/md/Use_of_Proxmark/0_Compilation-Instructions.md). Would it be possible to update this page with these instructions?

**Comment by iceman1001** [comment]
The guide is correct as it is.  What would be helpful is a guide when going from offical repo to rrg/iceman repo.  Feel free to contribute.
