### ISSUE TITLE
Cannot get KeyA when using "hf mf rdbl"

### ISSUE THREAD

**Issue by wh201906** [Proxmark/proxmark3#931]
When I try "hf mf rdbl 3 A FFFFFFFFFFFF", the proxmark3 can read the block, but it returns
"isOk:01 data:00 00 00 00 00 00 ff 07 80 69 ff ff ff ff ff ff"
rather than
"isOk:01 data:ff ff ff ff ff ff ff 07 80 69 ff ff ff ff ff ff"
the KeyA doesn't appear in the ReadBlock output.

Then I tried "hf mf rdbl 3 B FFFFFFFFFFFF", and I also got the same result.

However, when I try "hf mf dump"(assuming that I've got all KeyAs and KeyBs),the dumpdata.bin contains the KeyA.

Is this a bug?

**Comment by pwpiwi** [comment]
No, this is not a bug. The standard access conditions don't allow reading of KeyA. Regardless of the key, you will always get 000000000000 when trying to read KeyA.

dumpdata.bin is a mix of data read from the card and the keys from dumpkeys.bin.
