### ISSUE TITLE
 'https://proxmark3.googlecode.com/svn/trunk''/svn/trunk' path not found

### ISSUE THREAD

**Issue by joack81** [Proxmark/proxmark3#942]
Acabo de comenzar con proxmark3 y no puedo configurarlo, tengo este problema y no se como pasar de aquí, alguien puede echarme un cable, gracias!!

**Comment by iceman1001** [comment]
...we are using git nowdays.  not svn.

**Comment by joack81** [comment]
y me podrias indicar como configurarlo con git?? es que voy perdido...

**Comment by iceman1001** [comment]
There is lot of guides how to use git. 

Read the wiki,  https://github.com/Proxmark/proxmark3/wiki/Getting-Started

**Comment by joack81** [comment]
muchas gracias!!
todo lo que leo es para windows 7 o xp, con windows 10 tambien funciona?

**Comment by joack81** [comment]
hola iceman, despues de intentarlo mil veces, no lo consigo, no me podrias hacer un video? 
gracias
