### ISSUE TITLE
Windows GUI Instructions Missing

### ISSUE THREAD

**Issue by CuriousJames** [Proxmark/proxmark3#947]
Hi guys,

 I've found that the heading at the top of this wiki page links to a section that no longer exists :S : https://github.com/Proxmark/proxmark3/wiki/Windows#proxmark-client-gui

I've gone through all the main install steps but now want to get the GUI up and running.

Additionally I tried 'hw tune' and the proxspace cli says 'command not found'

If someone is able to help that would be amazing.

**Comment by pwpiwi** [comment]
I have fixed the broken links.
