### ISSUE TITLE
Proxmark log enhancements

### ISSUE THREAD

**Issue by ralik** [Proxmark/proxmark3#95]
It would be cool to have a time-stamp next to each line in the proxmark.log

Also, it seems that the log only shows the result of a command. The command itself that was issued before the result does not appear in the log.

It would give something like that:

12/04/2015 - 12:00PM: lf hid fskdemod
12/04/2015 - 12:01PM: #db# TAG ID: 2004F66073 (12345)

**Comment by iceman1001** [comment]
If you want it, why don't you add it?

I rarely look inside proxmark.log file,

**Comment by iceman1001** [comment]
You can find sample of how to do it here  https://github.com/Proxmark/proxmark3/blob/master/client/util.c#L94

Closing this one.
