### ISSUE TITLE
Debricking with ST-Link V2

### ISSUE THREAD

**Issue by RayPS** [Proxmark/proxmark3#958]
I was flashing to the latest firmware by following https://github.com/Proxmark/proxmark3/wiki/Windows step by step.
Unfortunately I bricked my device after running `./client/flasher comx -b ./bootrom/obj/bootrom.elf`.
Luckily I have an ST-Link V2, which mentioned in https://github.com/Proxmark/proxmark3/wiki/De-Bricking-Segger.
But I have no clue on how to connect those pins.
![IMG_0054](https://user-images.githubusercontent.com/1941540/100557885-c2fa9100-32e6-11eb-9ebd-3e0e19aa31d6.jpg)

**Comment by marshmellow42** [comment]
while i assume this issue has long been resolved, but if it hasn't the forum or discord is a much better place for this type of question.  i wish you luck.
