### ISSUE TITLE
#winscard.h missing 

### ISSUE THREAD

**Issue by anonanonanonanon** [Proxmark/proxmark3#961]
How do i fix this issue i have found a simmilar problem with solution but that fix unfortunately didnt work out for me

**Comment by pwpiwi** [comment]
Which operating system are you using and with which source file do you get this error? Please paste the output of your make command here.

**Comment by fsota** [comment]
I have the same issue. With Parrot OS:
pcsc.c:27:10: fatal error: winscard.h: No such file or directory
   27 | #include <winscard.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:348: obj/pcsc.o] Error 1
make[1]: Leaving directory '/home/user/proxmark3/client'
make: *** [Makefile:33: client/all] Error 2
┌─[✗]─[user@parrot-virtual]─[~/proxmark3]

**Comment by fsota** [comment]
![image](https://user-images.githubusercontent.com/76115417/105611941-7b592880-5db0-11eb-9d5f-f7ff53636a48.png)

**Comment by fsota** [comment]
working after install libpcsclite-dev
$ apt install libpcsclite-dev

**Comment by pwpiwi** [comment]
Well, as documented in the Wiki (https://github.com/Proxmark/proxmark3/wiki/Ubuntu-Linux#setup-and-build-for-ubuntu)
