### ISSUE TITLE
T55xx block7 password

### ISSUE THREAD

**Issue by DEFCON3187** [Proxmark/proxmark3#962]
Hi,

Hopefully someone can help. Ive been trying to emulate a T55x7 card and have been having difficulty in identifying the block 7 decimal point which is located in the binary. does anyone kwow what this is? Does the reader look at this as an actual password?

Cheers.

[usb] pm3 --> lf t55xx detect
[!] Could not detect modulation automatically. Try setting it manually with 'lf t55xx config'
[usb] pm3 --> lf t55xx detect
[=]      Chip Type      : T55x7
[=]      Modulation     : ASK
[=]      Bit Rate       : 5 - RF/64
[=]      Inverted       : No
[=]      Offset         : 32
[=]      Seq. Term.     : Yes
[=]      Block0         : 0xF01480E8
[=]      Downlink Mode  : default/fixed bit length
[=]      Password Set   : No

[usb] pm3 --> lf t55xx dump
[+] Reading Page 0:
[+] blk | hex data | binary                           | ascii
[+] ----+----------+----------------------------------+-------
[+]  00 | F01480E8 | 11110000000101001000000011101000 | ....
[+]  01 | FF0F002D | 11111111000011110000000000101101 | ...-
[+]  03 | 00000000 | 00000000000000000000000000000000 | ....
[+]  04 | 00000000 | 00000000000000000000000000000000 | ....
[+]  05 | 00000000 | 00000000000000000000000000000000 | ....
[+]  06 | 00000000 | 00000000000000000000000000000000 | ....
[+]  07 | 0000000E | 000000000000000000000000000000.0 | ....
[+] Reading Page 1:
[+] blk | hex data | binary                           | ascii
[+] ----+----------+----------------------------------+-------
[+]  00 | F01480E8 | 11110000000101001000000011101000 | ....
[+]  01 | E0150A44 | 11100000000101010000101001000100 | ...D
[usb] pm3 --> lf t55 dump
[+] Reading Page 0:
[+] blk | hex data | binary                           | ascii
[+] ----+----------+----------------------------------+-------
[+]  03 | 00000000 | 00000000000000000000000000000000 | ....
[+]  04 | 00000000 | 00000000000000000000000000000000 | ....
[+]  05 | 00000000 | 00000000000000000000000000000000 | ....
[+]  06 | 00000000 | 00000000000000000000000000000000 | ....
[+]  07 | 00000000 | 00000000000000000000000000000000 | ....
[+] Reading Page 1:
[+] blk | hex data | binary                           | ascii
[+] ----+----------+----------------------------------+-------
[+]  03 | 00000000 | 00000000000000000000000000000000 | ....

**Comment by pwpiwi** [comment]
You are using the RRG build. Please raise your issue in the respective github repository: https://github.com/RfidResearchGroup/proxmark3
