### ISSUE TITLE
Can't download windows client gui from website

### ISSUE THREAD

**Issue by FurryJack0420** [Proxmark/proxmark3#972]
I'm going through the windows guide but when going to the windows gui part where it talks about the gui that's been build from scratch in the first sentence, when I click on the link to go to the website it says I don't have permission to view it, and when I go to register it just gives me a 404 error

**Comment by pwpiwi** [comment]
The GUI is here: https://github.com/Proxmark/Gaucho-GUI

But it isn't maintained since years and probably would need some refresh. I never tested it.
