### ISSUE TITLE
Error Cloning card 

### ISSUE THREAD

**Issue by aleemladha** [Proxmark/proxmark3#976]
Hi , i was trying to write to a blank card and got this error. Using proxmark easy.

![image](https://user-images.githubusercontent.com/26311391/116531734-29acc680-a8e8-11eb-91b3-63911c00f730.png)

**Comment by pwpiwi** [comment]
You are using the RRG-Software and therefore should report your issue on the respective repository: https://github.com/RfidResearchGroup/proxmark3
