### ISSUE TITLE
Flash Issue

### ISSUE THREAD

**Issue by bad4dayz** [Proxmark/proxmark3#979]
Hello all, I'm very new to all of this, I just purchased my ProxMark 3 RVD 4 last week and have run into a few small issues.
FYI the reason that I purchased this unit, was because I'm looking to do FOB replication/cloning as a business, I had a small business, but he one I was using was very limited, and I wanted to expand and everywhere I was direct to ProxMark 3 RVD 4, so my issue... when I run the 
pm3 ~$ client/flasher.exe com3 -b bootrom/obj/bootrom.elf armsrc/obj/fullimage.elf
I get... bash: client/flasher.exe: No such file or directory, and I can't find the flasher.exe anywhere... did I miss something in the compiling? 
Any assistance would be great
Allen
![clientflasher](https://user-images.githubusercontent.com/85775053/122494412-5069ae00-cfb7-11eb-8a38-95b2724de5af.jpg)

**Comment by mwalker33** [comment]
For the RDV4 you might be better off on the RRG repo as it was designed with the RDV4 in mind.

https://github.com/RfidResearchGroup/proxmark3

The follow the setup guide on that repo.
The setup of the environment (proxspace at a guess) should be the same, just git clone and compile and follow the install guides on the rrg site.

if you scroll down on that page from the link above, you should be able to find the correct setup guides for your environment.

Note: If you decide to say with this repo, I will leave it there and let someone else help out.
If you go over to the RRG remember to update this to a closed state.
