### ISSUE TITLE
Make Script Help

### ISSUE THREAD

**Issue by DzMassi** [Proxmark/proxmark3#980]
Hello,

I wish made a script for the brute force em4x50 function in order to find the password.

the function already exists but does not work : 
[usb] pm3 --> lf em 4x50 brute --first 00000000 --last 00009999
[=] Trying 39322 passwords in range [0x00000000, 0x00009999]
[=] Estimated duration: 0h24m16s
[=] You can cancel this operation by pressing the pm3 button

[!] Communicating with Proxmark3 device failed

my wish is a sript which launches the command lf em 4x50 brute --first 00000000 --last 00000150 then increment the same function by +150 (lf em 4x50 brute --first 00000000 --last 00000300) until the password is found.

and save a log file.

thanks a lot for your help

**Comment by pwpiwi** [comment]
You are most probably using the RRG Client Software. Therefore please post your issue there: https://github.com/RfidResearchGroup/proxmark3
