### ISSUE TITLE
Running hardnested attack error

### ISSUE THREAD

**Issue by mrmoonshine24** [Proxmark/proxmark3#986]
HI, 

I am currently trying to hardnested a tag of mine. but whenever i try to launch it, the following error will occur.

[usb] pm3 --> hf mf hardnested --blk 0 -a -k ffffffffffff --tblk 6 --ta
[=] Target block no   6, target key type: A, known target key: 000000000000 (not set)
[=] File action: none, Slow: No, Tests: 0
[+] Using no SIMD core.

 time    | #nonces | Activity                                                | expected to brute force
         |         |                                                         | #states         | time 
------------------------------------------------------------------------------------------------------
       0 |       0 | Start using 8 threads and no SIMD core                  |                 |
       0 |       0 | Brute force benchmark: 610 million (2^29.2) keys/s      | 140737488355328 |    3d
       2 |       0 | Using 235 precalculated bitflip state tables            | 140737488355328 |    3d
       5 |     112 | Apply bit flip properties                               |  10213523456000 |    5h
       6 |     223 | Apply bit flip properties                               |   8664185307136 |    4h
       7 |     335 | Apply bit flip properties                               |   8378623459328 |    4h
       8 |     447 | Apply bit flip properties                               |   8378623459328 |    4h
       9 |     559 | Apply bit flip properties                               |   8378623459328 |    4h
      10 |     670 | Apply bit flip properties                               |   8378623459328 |    4h
      11 |     781 | Apply bit flip properties                               |   8378623459328 |    4h
      11 |     892 | Apply bit flip properties                               |   8378623459328 |    4h
      12 |    1004 | Apply bit flip properties                               |   8378623459328 |    4h
      13 |    1111 | Apply bit flip properties                               |   8378623459328 |    4h
      15 |    1220 | Apply bit flip properties                               |   8378623459328 |    4h
/opt/homebrew/bin/pm3: line 246: 68917 Segmentation fault: 11  $CLIENT "$@"

anyone knows how to solve this problem? 

thankss

**Comment by pwpiwi** [comment]
You are most probably using RRG's software and therefore have to raise this issue in their repository: https://github.com/RfidResearchGroup/proxmark3
