### ISSUE TITLE
List of SMT components to use with the PCB files?

### ISSUE THREAD

**Issue by peddy22** [Proxmark/proxmark3#993]
Does this exist? I've spent hours searching but couldn't find it anywhere online.

**Comment by pwpiwi** [comment]
This one? https://github.com/Proxmark/proxmark3/blob/master/doc/proxmark3.xls

**Comment by peddy22** [comment]
Yes... However it only lists a mini-USB receptacle, and I need a new micro-usb one.. Thanks anyway

Edit: just noticed I have the PM3-Easy which is made for the Chinese market, doubt I will be able to find any public BOM for it
